### ISSUE TITLE
Getting a crash on master with executeSync from a background thread

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto#1031]
Using addRef to obtain a reference that's owned off-thread. Then I come back around and do executeSync so that I can interrupt the KJ loop.

```
kj::_::Mutex::lock(kj::_::Mutex::Exclusivity exclusivity, kj::Maybe<kj::Quantity<__int64,kj::_::NanosecondLabel>> timeout) Line 481	C++
kj::MutexGuarded<kj::Executor::Impl::State>::lockShared() Line 506	C++
kj::Executor::getLoop() Line 1131	C++
kj::_::XThreadEvent::XThreadEvent(kj::_::ExceptionOrValue & result, const kj::Executor & targetExecutor) Line 775	C++
kj::_::XThreadEventImpl<void <lambda>(void),kj::_::Void>::XThreadEventImpl<void <lambda>(void),kj::_::Void>(Server::interrupt::__l3::void <lambda>(void) && func, const kj::Executor & target) Line 1407	C++
kj::Executor::executeSync<void <lambda>(void)>(Server::interrupt::__l3::void <lambda>(void) && func) Line 1459	C++
```

Exception thrown at 0x00007FFC63D9A958 (ntdll.dll): 0xC0000005: Access violation writing location 0x000000DDDDDDDDDD.

The `interrupt` function is being invoked as part of the thread instance shutdown so I'm pretty sure it's not anything like me happening to release the underlying executor.

**Comment by vlovich** [comment]
In `EventLoop& Executor::getLoop() const`, 

```
disposer | 0xdddddddddddddddd {...} | const kj::Disposer *
ptr | 0x000000dddddddddd {state={mutex={srwLock=??? waitersHead={ptr=??? } waitersTail=??? } value={loop={...} ...} } } | kj::Executor::Impl *
```

**Comment by vlovich** [comment]
Maybe something related is that I moved the Executor & Canceler but for some reason the underlying pointer value's have changed?

**Comment by kentonv** [comment]
Hmm what do you mean you "moved" the Executor? It's not meant to be movable. It looks like I forgot to mark it with KJ_DISALLOW_COPY, but there's also no way to get a non-const reference to it, and a const reference shouldn't be movable anyway...

**Comment by vlovich** [comment]
I move the class that has the kj::own of the executor. I took a break from looking at it for a bit because it was frustrating me a bit. I hope there isn’t a copy happening accidentally. Where’s the missing copy deletion?

**Comment by vlovich** [comment]
The snippet is something like this:

```
MyClass foo;
DISPATCH_ASYNC([foo = std::move(foo)] {
   // now destroy
});
```

MyClass contains a valid `kj::Own<const kj::Exector>` at the end. The constructor blocks on the internal thread it creates. There is no explicit destructor. The thread is owned by an RAII class that joins on destructions. That thread instance variable is declared after the executor (it'll get destroyed first) and the destruction has a callback registered to executeSync onto the executor.

DISPATCH_ASYNC is some internal code seemingly inspired from libdispatch. The lambda gets converted into a folly::Function (this isn't a part of the code I'm as familiar with). I'm hoping it's unlikely it's there.

Annoyingly putting my class into a unique_ptr instead fixes the issue:
```
auto foo = std::make_unique<MyClass>;
DISPATCH_ASYNC([foo = std::move(foo)] {
   // now destroy
});
```

It would seem like the underlying move support within those pieces works OK. I don't see anything obviously wrong in kj::Own either. I'm really stumped.

**Comment by vlovich** [comment]
I'm going to assume this is either some bug in the version we're using or some nuance of folly::Function.

**Comment by vlovich** [comment]
Bah I figured it out. I was capturing `this` in my lambda that I ran on thread destruction. However `this` was pointing to the wrong thing after a move.

**Comment by kentonv** [comment]
Glad you figured it out!

Oddly enough, we're also seeing a bug with cross-thread events when the target thread has exited, but I suspect it's a problem in our internal codebase, not KJ.
