### ISSUE TITLE
Internal compiler error on Visual Studio 2019 16.7.0

### ISSUE THREAD

**Issue by SMelanko** [capnproto/capnproto#1041]
Using [build instruction](https://capnproto.org/install.html#installation-windows) I got

```bash
1>C:\capnproto-0.8.0\c++\src\kj\compat\http.c++(2616,1): fatal error C1001: Internal compiler error.
1>(compiler file 'msc1.cpp', line 1591)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>If possible please provide a repro here: https://developercommunity.visualstudio.com
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\CL.exe'
1>    Please choose the Technical Support command on the Visual C++
1>    Help menu, or open the Technical Support help file for more information
```

Do you have any suggestions?

[Topic developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/content/problem/1143733/internal-compiler-error-on-v1670.html)

**Comment by kentonv** [comment]
Hi @SMelanko,

Hmm, we test every Cap'n Proto change using Visual Studio 16 and I haven't seen this before, but it looks like the version that GitHub Actions has installed might be slightly older.

I'm not too familiar with specific minor releases. Is 16.7.0 a new release? Maybe this release has a regression?

Probably this should be reported to Microsoft, I think.

I definitely won't be able to test with this new release at least until the GitHub Actions runners start using it. But, if you can find a work-around that's not too bad, I'm happy to consider a PR.
