### ISSUE TITLE
Using `eof` as an enum discriminant generates invalid code in C++

### ISSUE THREAD

**Issue by NeoLegends** [capnproto/capnproto#1051]
We just stumbled over the issue where if you have an enum discriminant `eof` in a capnp file and try to generate C++ sources, the generator will output invalid C++ code. This is because the variant will be named `EOF`, which is actually a macro http://www.cplusplus.com/reference/cstdio/EOF/. Perhaps those cases should be caught and, for example, `EOF_` generated instead. I'm sure you cannot accomodate for all macros that exist, but avoiding clashes with some very common ones would already be helpful.

**Comment by kentonv** [comment]
Hi Moritz,

You can fix this by renaming the enumerant for C++ purposes:

    using Cxx = import "/capnp/c++.capnp";

    enum Foo {
      eof @0 $Cxx.name("eof_");
    }

Unfortunately it's not feasible for us to track down every possible name conflict and avoid them automatically, and any systematic approach that prevents all possible conflicts (like, say, adding a prefix or suffix to every enum) would result in ugly naming conventions that nobody likes.

**Comment by NeoLegends** [comment]
That's why I would like to suggest only renaming the really common cases, like EOF.

**Comment by kentonv** [comment]
I've seen lots and lots of bug reports like this and this is honestly the first time I've seen `EOF` come up. I'm not sure it's as common as you think.

Also, people who don't use stdio.h don't actually need this rename and might be confused by it.

**Comment by NeoLegends** [comment]
Okay, then it's fine to leave it as is. Thank you for the quick support!
