### ISSUE TITLE
capnproto 0.8.0 OSX: link error, kj symbols undefined for x86_64

### ISSUE THREAD

**Issue by koverton** [capnproto/capnproto#1053]
Built and installed according to the installation instructions. Ran `capnp` successfully over the sample `addressbook.capnp` from https://capnproto.org/cxx.html and wrote an extremely simple program to test it out.

I'm building the test program with clang++ 11.0.3, target x86_64-apple-darwin19.6.0. The c++ code compiles fine, but when I link I get link error "Undefined symbols for architecture x86_64:" for all kj::... symbols.

clang++ -lcapnp -std=c++17 *.cpp *.c++
Undefined symbols for architecture x86_64:
  "kj::heapString(unsigned long)", referenced from:
      ...
  "kj::AutoCloseFd::~AutoCloseFd()", referenced from:
      ...

I've tried this with 0.8.0 I built and installed myself, and with `brew install capnp`

Am I missing something obvious?

**Comment by koverton** [comment]
SOLVED: Yes, I was missing something obvious on https://capnproto.org/cxx.html:

```
As of v0.3, KJ is distributed with Cap’n Proto but built as a separate library. You may need to explicitly link against libraries: -lcapnp -lkj
```

It works fine when I link KJ.

**Comment by kentonv** [comment]
Glad you figured it out. We also support `pkg-config` as a mechanism to automatically generate the necessary list of linker flags, FWIW.
