### ISSUE TITLE
Unaligned Stores in BuilderArena/ReaderArena constructors

### ISSUE THREAD

**Issue by erikmchut** [capnproto/capnproto#1054]
I was debugging our Emscripten stack to ultimately track down some unrelated heap corruption issues, and in the process I noticed that the BuilderArena constructor was doing an unaligned store.

I have an older capnproto version, but I assume the underlying issue is still the same:

The `void* arenaSpace` member in MessageBuilder and MessageReader is missing an alignment parameter such as `alignas(8)`. When BuilderArena constructor is run on this memory through kj::ctor, it ends up storing its members in unaligned data which is undefined behavior and miffs llvm sanitizers. Adding alignas specifiers to each arenaSpace declaration resolves the issue. Happy to send a PR, but I wanted to get your feedback before doing so.

**Comment by kentonv** [comment]
Some Cap'n Proto code makes the assumption that the platform's minimum alignment is the size of a pointer, but maybe that isn't universal? Does this environment have 32-bit pointers but still require 64-bit alignment for 64-bit values?

I'm happy to accept a PR adding alignment annotations where needed.

**Comment by dwrensha** [comment]
@kentonv I think that property is not universal. Consider, for example, 32-bit RISC-V https://godbolt.org/z/16Gcz7

**Comment by erikmchut** [comment]
Yes that sounds right. WebAssembly is a 32-bit architecture, but it it expects 8-byte alignment for 64-bit types. Since message.h doesn't include the actual type information for BuilderArena and ReaderArena, it can end up with 64-bit stores/loads shifted when constructing these types in the char array. FWIW, I've only observed issues with BuilderArena.
