### ISSUE TITLE
VS2019: Compiling Cap'nProto Crashes C++ Compiler

### ISSUE THREAD

**Issue by fritzone** [capnproto/capnproto#1061]
Hey, I managed to crash VS2019 while compiling Cap'nProto. Any chance that you can take a look into this?

https://stackoverflow.com/questions/63916528/vs2019-compiling-capnproto-crashes-c-compiler

**Comment by chronoxor** [comment]
Here is a workaround in PR on review - https://github.com/capnproto/capnproto/pull/1058

**Comment by harrishancock** [comment]
Closing, as the workaround for this was merged.
