### ISSUE TITLE
Message has too many segments

### ISSUE THREAD

**Issue by Timmmm** [capnproto/capnproto#1078]
Hi, we're using Capnp via the C++ library to serialise some data. It is giving this error:

```
kj::ExceptionImpl, what():  capnp/serialize.c++:186: failed: expected segmentCount < 512; Message has too many segments.
```

Which appears to come from [here](https://github.com/capnproto/capnproto/blob/b656e5968bae4f2895050b764c6e51b2d64bf31f/c%2B%2B/src/capnp/serialize.c%2B%2B#L176)

    // Reject messages with too many segments for security reasons.

The file size is not huge (I think only ~200 kB, but don't quote me on that). The code is unfortunately not open source, but it's roughly like this:

```
void serializeExecutable(std::ostream &out, const Executable &exe) {
  // .. write a load of stuff to `out` first ...

  capnp::MallocMessageBuilder message;
  auto exeBuilder = message.initRoot<Executable>();

  {
    auto builder = exeBuilder.initFoo(exe.foo.size());
    std::size_t i = 0;
    for (const auto &foo : exe.foo) {
      builder.set(i, foo);
      ++i;
    }
  }

  {
    auto taiBuilder = exeBuilder.initTai();
    auto serializeTai =
        [&](capnp::List<cap::Tai>::Builder builder,
            const Tai::Map &data) {
          std::size_t i = 0;
          for (const auto &t : data) {
            builder[i].setHandle(t.first);
            builder[i].setProgram(t.second.first);
            builder[i].setStreamId(t.second.second);
            ++i;
          }
        };

    serializeTai(taiBuilder.initReads(exe.tai.read.size()),
                 exe.tai.read);
    serializeTai(taiBuilder.initWrites(exe.tai.write.size()),
                 exe.tai.write);
  }

  // .. Loads more stuff is written but it follows similar patterns..

  kj::std::StdOutputStream sos(out);
  capnp::writePackedMessage(sos, message);
}
```

Can you explain what this error means, and if we are doing something wrong?

**Comment by kentonv** [comment]
This usually indicates some sort of corruption -- the very first thing in the message is a count of how many segments there are, and if for some reason that count is wrong or corrupt then it's likely you'd get this error.

You included your writing code, but not your reading code. It looks like your writing code serializes in packed format, so on the reading side you should be using `PackedMessageReader`. Is it possible you accidentally used `InputStreamMesasgeReader` (or some other non-packed reader) instead?

**Comment by Timmmm** [comment]
> Is it possible you accidentally used InputStreamMesasgeReader (or some other non-packed reader) instead?

I forgot to mention, this code has been working fine for ages - just one particular user had this issue. I think you might be right about corruption. Seems like this file was generated by tests and it might be the case that lots of tests are running concurrently and writing to the same file. Maybe we should add a checksum.

Thanks!
