### ISSUE TITLE
capnp convert incorrectly rejects messages whose root pointer is an empty struct (offset -1)

### ISSUE THREAD

**Issue by zenhack** [capnproto/capnproto#1084]
The check here:

https://github.com/capnproto/capnproto/blob/056f88f393d10bc4d49250bfebb442d7515c95c7/c%2B%2B/src/capnp/compiler/capnp.c%2B%2B#L1245-L1248

causes capnp convert to reject input messages if the offset in the root pointer is negative. This is actually valid for empty structs, and is the only way to encode them (as a zero offset would indicate a null pointer). We should probably update that check to allow -1 as an offset.

I caught this while doing some property testing of the Haskell implementation.

**Comment by kentonv** [comment]
Yeah I guess that code should be adjusted to accept an offset of -1 if the struct size is zero.
