### ISSUE TITLE
Canonicalization algorithm does not specify what the offset should be for lists with C = 0

### ISSUE THREAD

**Issue by zenhack** [capnproto/capnproto#1085]
When a list pointer has C = 0 (list of void), the canonicalization algorithm does not specify what its offset should be. ~From testing it appears that the reference implementation uses zero here (haven't looked at the code~ Edit: I've seen other offsets now), but the spec doesn't state this explicitly.

**Comment by zenhack** [comment]
Ok, looks like it's just doing the obvious thing and allocating at the next available offset -- which you could perhaps glean from the spec but given there's an exception called out for zero-sized structs maybe it should still be stated explicitly. It occurs to me that this also arises in the case of any empty non-composite list.

**Comment by kentonv** [comment]
Yeah we should standardize on zero...

**Comment by zenhack** [comment]
Quoting Kenton Varda (2020-10-16 17:30:36)

>    Yeah we should standardize on zero...

Hm, I think the current behavior is fine, and changing it would mean
breaking users who have existing data that hits this case. I think it
probably makes more sense to just make the docs more explicit.

**Comment by kentonv** [comment]
Oh I see, it is allocating a zero-sized list but still following preorder? So it is actually consistent, just unspecified? Then yeah, I agree we should specify the existing behavior.
