### ISSUE TITLE
Support for List(Capability)?

### ISSUE THREAD

**Issue by JonasVautherin** [capnproto/capnproto#1089]
I was trying to use a `List(Capability)` in a schema, and ended up with the following error:

```
error: 'List(AnyPointer)' is not supported.
```

I found [an e-mail from 2017](https://www.mail-archive.com/capnproto@googlegroups.com/msg00599.html) where you say:

> These days we also have AnyStruct, AnyList, and Capability. I think
> List(AnyList) and List(Capability) ought to be made legal if they aren't
> already (can't remember). Or in some use cases, it makes sense to replace
> List(AnyPointer) with AnyList -- thus supporting lists of any type, as long
> as all the elements are the same type.

Looking at [schema.c++](https://github.com/capnproto/capnproto/blob/b4f0a7116a02146592e6d4445346695977d394ae/c%2B%2B/src/capnp/schema.c%2B%2B#L742), it seems like the error comes from that file:

```
case schema::Type::ANY_POINTER:
      KJ_FAIL_REQUIRE("List(AnyPointer) not supported.");
```

However, I can create a struct wrapping the Capability, say `CapabilityHolder`, and successfully use a `List(CapabilityHodler)`, which works as a workaround.

Is it tricky to enable the use of `List(Capability)` (or, as you mention, "lists of any type, as long as all the elements are the same type"), or could it qualify for a first contribution in the codebase? With some pointers, I would be happy to have a look at this.

BTW, I am new to capabilities, but I'm quickly becoming a big fan (and I love that capnproto's documentation gives reference to capabilities-related publications, that is invaluable). Same for capnproto, thanks a lot for all the work there!

**Comment by kentonv** [comment]
Historically, `AnyPointer` predated `AnyStruct`, `AnyList`, and `Capability`. So, when those three types were introduced, `schema.capnp` was extended in a backwards-compatible way so that existing code would treat them all as `AnyPointer`. Here's the relevant section of `schema.capnp`:

https://github.com/capnproto/capnproto/blob/3a9a72d4619c63403a8a1e54f81ead67feaf4868/c++/src/capnp/schema.capnp#L348-L360

So the trick is to update the various places in the code such that when they see `schema::Type::ANY_POINTER`, they drill down to see if it's type `unconstrained` and then within that type `anyKind`, `struct`, `list`, or `capability`. `anyKind` should still be an error, as should `struct`, but `list` and `capability` should be allowed.

I would guess that this is _probably_ just a matter of fixing the error-checking code -- I don't think any new logic is needed. If that's the case then it seems like a reasonable PR for a newcomer. :)

**Comment by JonasVautherin** [comment]
I tried with the following patch, which essentially checks if the `AnyPointer` is an `AnyKind` or a `Struct`, and fail in that case:

```cpp
diff --git a/c++/src/capnp/compiler/node-translator.c++ b/c++/src/capnp/compiler/node-translator.c++
index 8789618d..31a92570 100644
--- a/c++/src/capnp/compiler/node-translator.c++
+++ b/c++/src/capnp/compiler/node-translator.c++
@@ -970,10 +970,19 @@ bool NodeTranslator::BrandedDecl::compileAsType(
         }
 
         if (elementType.isAnyPointer()) {
-          addError(errorReporter, "'List(AnyPointer)' is not supported.");
-          // Seeing List(AnyPointer) later can mess things up, so change the type to Void.
-          elementType.setVoid();
-          return false;
+          auto unconstrained = elementType.getAnyPointer().getUnconstrained();
+
+          if (unconstrained.isAnyKind()) {
+            addError(errorReporter, "'List(AnyKind)' is not supported.");
+            // Seeing List(AnyKind) later can mess things up, so change the type to Void.
+            elementType.setVoid();
+            return false;
+          } else if (unconstrained.isStruct()) {
+            addError(errorReporter, "'List(Struct)' is not supported.");
+            // Seeing List(Struct) later can mess things up, so change the type to Void.
+            elementType.setVoid();
+            return false;
+          }
         }
 
         return true;
```

When trying with my `:List(Capability)` in my schema, it now gets accepted because `unconstrained.isCapability()` is true. But then, when compiling my code, I get:

```
error: invalid use of incomplete type ‘struct capnp::List<capnp::Capability, capnp::Kind::OTHER>’

...

include/capnp/common.h:200:8: note: declaration of ‘struct capnp::List<capnp::Capability, capnp::Kind::OTHER>’
  200 | struct List;
      |        ^~~~
```

What am I missing? Is my approach reasonable?

**Comment by JonasVautherin** [comment]
Aha!

I don't quite understand `Kind` and `Style` yet, but it seems like [a `Capability` is an `INTERFACE`](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/common.h#L194), and not an [`OTHER`](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/common.h#L93). So I was thinking that my list should look more like `struct capnp::List<capnp::Capability, capnp::Kind::INTERFACE>`, and indeed in turns out that [this is defined in capability.h](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/capability.h#L745)!

When I change that manually in the generated code, then it compiles :raised_hands:. So now I'm trying to find where this gets generated and why it is `OTHER` and not `INTERFACE` :slightly_smiling_face:.

**Comment by JonasVautherin** [comment]
Hmm so I tried the following patch, which checks if an unconstrained is a capability and, in this case, sets its type as `Which::INTERFACE`:

```cpp
diff --git a/c++/src/capnp/schema.h b/c++/src/capnp/schema.h
index 5cc20b5e..ffdcbfc5 100644
--- a/c++/src/capnp/schema.h
+++ b/c++/src/capnp/schema.h
@@ -926,7 +926,20 @@ inline Type::Type(ImplicitParameter param)
       paramIndex(param.index), scopeId(0) {}
 
 inline schema::Type::Which Type::which() const {
-  return listDepth > 0 ? schema::Type::LIST : baseType;
+  if (listDepth > 0) {
+      return schema::Type::LIST;
+  }
+
+  if (baseType != schema::Type::ANY_POINTER) {
+      return baseType;
+  }
+
+  switch (whichAnyPointerKind()) {
+      case schema::Type::AnyPointer::Unconstrained::CAPABILITY:
+          return schema::Type::INTERFACE;
+      default:
+          return schema::Type::ANY_POINTER;
+  }
 }
 
 inline schema::Type::AnyPointer::Unconstrained::Which Type::whichAnyPointerKind() const {
```

But it fails with:

```
[ 69%] Compiling Cap'n Proto schema test.capnp
*** Uncaught exception ***
capnp/schema.c++:811: failed: expected isInterface(); Tried to interpret a non-interface type as an interface.
```

But now I'm confused, maybe I am completely off. I'll open a PR to show what I have tried, in case somebody can review.

**Comment by JonasVautherin** [comment]
Ok I'm giving up.

I probably don't translate between `AnyPointer` and `INTERFACE` in the right places, because I end up without a `schema` when `isInterface()` is called:

```cpp
InterfaceSchema Type::asInterface() const {
  KJ_REQUIRE(isInterface(), "Tried to interpret a non-interface type as an interface.") {
    return InterfaceSchema();
  }
  KJ_ASSERT(schema != nullptr);
  return InterfaceSchema(Schema(schema));
}
```

It somehow feels like [`Type` doesn't get a `schema` for an `AnyPointer`](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/schema.h#L620), and so maybe I should convert it earlier, but I can't seem to find a way.

Well, I tried, and I think I learned a few things, but I'm not there yet.

**Comment by zenhack** [comment]
It probably makes sense to keep this issue open, even if you're not going to tackle it yourself.

**Comment by JonasVautherin** [comment]
I'm honestly not convinced this is really needed on itself. It's just that there is no particular reason to not support it, and I hoped it could be a good exercise to start learning the codebase. So it was mainly about sharing my work and possibly getting feedback, but I don't think it makes sense to keep it open just for the sake of it.

Feel free to reopen, though, of course.

**Comment by kentonv** [comment]
Keeping this open because it is actually a bug.
