### ISSUE TITLE
Compilation issues with capnp 0.8.0 on CentOS 6

### ISSUE THREAD

**Issue by pavel-odintsov** [capnproto/capnproto#1092]
Hello!

Thank you for your hard work on Cap'n'Proto! It's impressive protocol!

To address issue explained in https://github.com/capnproto/capnproto/issues/743 I've migrated to capnp 0.8.0.

Unfortunately, I hit another issue with it:
```
libtool: link: ranlib .libs/libcapnpc.a
libtool: link: ( cd ".libs" && rm -f "libcapnpc.la" && ln -s "../libcapnpc.la" "libcapnpc.la" )
/bin/sh ./libtool  --tag=CXX   --mode=link /opt/gcc920/bin/g++ -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR='"/opt/capnproto_0_8_0/include"' -pthread -O2 -DNDEBUG -pthread -pthread  -o capnpc-c++ src/capnp/compiler/capnpc-c++.o libcapnp.la libkj.la -lpthread -lpthread 
libtool: link: /opt/gcc920/bin/g++ -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/opt/capnproto_0_8_0/include\" -pthread -O2 -DNDEBUG -pthread -pthread -o .libs/capnpc-c++ src/capnp/compiler/capnpc-c++.o  ./.libs/libcapnp.so ./.libs/libkj.so -lpthread -pthread -Wl,-rpath -Wl,/opt/capnproto_0_8_0/lib
./.libs/libkj.so: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make: *** [capnpc-c++] Error 1
make: *** Waiting for unfinished jobs....
Command finished with code 512
```

Is it possible to disable this logic for CentOS 6? I understand that this platform is extremely old but we still have installations on it. I use gcc 9.2 built from source as standard one is dead old. 

Thank you!

**Comment by jclee** [comment]
This StackOverflow answer suggests that old versions of glibc might require librt to have access to clock_gettime: 
 https://stackoverflow.com/a/32649327

Perhaps it might work better to do something like `export LIBS="-lrt"` before running `./configure` and `make`?

**Comment by kentonv** [comment]
Indeed, clock_gettime() has been around for decades, so it's probably as @jclee says. Try running configure like:

    ./configure LIBS="-lrt"

**Comment by pavel-odintsov** [comment]
Thank you! Let me check!

**Comment by pavel-odintsov** [comment]
Thank you! It works!
