### ISSUE TITLE
Security review before 1.0 release

### ISSUE THREAD

**Issue by Radrik5** [capnproto/capnproto#1157]
In 2015 you wrote:

> We will commission a professional security review before any 1.0 release. Until that time, we continue to recommend against using Cap’n Proto to interpret data from potentially-malicious sources.

https://capnproto.org/news/2015-03-02-security-advisory-and-integer-overflow-protection.html

In 2020 you talked about a couple of small fixes before 1.0 release:

> Still, there are a couple smaller things I want to do for an upcoming 1.0 release:
> 1. Properly document KJ, independent of Cap’n Proto. KJ has evolved into an extremely useful general-purpose C++ toolkit library.
> 2. Fix a mistake in the design of KJ’s AsyncOutputStream interface. The interface currently does not have a method to write EOF; instead, EOF is implied by the destructor. This has proven to be the wrong design. Since fixing it will be a breaking API change for anyone using this interface, I want to do it before declaring 1.0.

https://capnproto.org/news/2020-04-23-capnproto-0.8.html

Is professional security review still in your roadmap for 1.0 release?

**Comment by kentonv** [comment]
Cap'n Proto is used extensively inside Cloudflare Workers and is therefore in-scope for the security reviews and adversarial testing we have commissioned against Workers. No bugs in Cap'n Proto have been discovered by any of these reviews. If one were discovered, I would of course disclose it in the same format as the past disclosures.

That said, sadly, I've learned that "professional security reviews" don't realistically produce the kinds of results I had imagined when I originally wrote that statement. Security reviewers for hire will generally run some automated tools and look for some obvious checklist items. The industry is set up to check boxes for compliance, not to do actual interesting security research. When you have code that is written by security-conscious developers in the first place, it's unlikely to have any of those obvious problems, and finding deeper bugs will require creativity and cleverness. The kind of people capable of doing that aren't so easy to hire.

If any really good offensive security people reading this would like a job attacking Workers and Cap'n Proto, let me know!
