### ISSUE TITLE
Mechanism to generate schema "fingerprint"

### ISSUE THREAD

**Issue by sobomax** [capnproto/capnproto#1166]
Hi. This is not so much of an issue report, but more of a feature request. It would be really nice to have some future-proof way to generate unique 64- or even 128-byte ID that would identify particular schema that has been compiled in. This need arises when you think about typical two-way session setup scenario (say bunch of IoT devices talking to a cloud app), where on one end you might have a fat up to date distributed application running in a well maintained environment, and on the other - multiple generations of clients in a field, some of which are not  capable of updating themselves too often if at all. In that case it's quite helpful if a client can introduce its supported schema(s) in a way that is concise, yet unambiguous, let server run its gears and either accept or possibly deny a session it if the schema is not recognized.  On a server side this would allow supporting as many generations of clients as needed by matching the "fingerprint" against its latest and possibly few older supported schema version(s) and loading appropriate handler.

**Comment by kentonv** [comment]
Hi @sobomax,

Thanks for the suggestion.

In my opinion, though, I don't think this can be based on the schema alone. The schema captures the "shape" of the protocol, but not the full semantics. It's possible for the interpretation of a particular field to change, without its type changing. So I think for the kind of system you describe, you really want more than just a fingerprint of the schema. You probably want to communicate some sort of version number or release timestamp instead.

**Comment by sobomax** [comment]
Hi @kentonv thank you for the feedback! I agree that this hypothetical feature is probably not going to magically solve all API compatibility issues for everyone. However in my view it might as well be a very helpful piece of the puzzle on that path. In my experience working on private and public APIs, the cases when existing field is given a new meaning without changing its formal type is quite rare compared to a more common case of adding/removing existing values.

As such, with the "fingerprint" one can approach solution to this issue differently - by having schema "fingerprint" as a basic building block and then within the schema itself placing a monotonically incrementing "logical revision" flag to handle those rare cases when meaning  of one field needs to be changed for whatever reason. Then you can always identify a schema(s) and locate version number within each of them, just given the binary packet itself. No other extra storage is necessary. Assuming of course you can recover fingerprint from the binary representation.

Think for example about the cases when the binary data needs to be stored for extended period of time - in my scenario all you need to store is the binary data itself, while in the case when version number is tracked externally one would need to keep track of that version for every bit of data if ability to access data later is required.

**Comment by kentonv** [comment]
> Think for example about the cases when the binary data needs to be stored for extended period of time - in my scenario all you need to store is the binary data itself, while in the case when version number is tracked externally one would need to keep track of that version for every bit of data if ability to access data later is required.

Hmm I think I'm lost here. Aren't you proposing that you'd need to store this "schema fingerprint" along with the data? How is that less onerous than storing a version number?

**Comment by sobomax** [comment]
@kentonv yes, you are right, I think I went little circular.

Pardon my ignorance, is not the top level id described here https://capnproto.org/language.html#unique-ids serves a somewhat similar  purpose? Except instead of having it randomly generated my idea is to have it a function of the high-level schema structure (+random element).

**Comment by kentonv** [comment]
> is not the top level id described here https://capnproto.org/language.html#unique-ids serves a somewhat similar purpose?

The unique IDs described there are specifically intended to be stable across schema changes. The point is to be able to identify that two declarations in different schemas are intended to be different versions of the same type, even if the type has been renamed, fields added, etc.

In any case, those IDs don't actually appear anywhere in the serialization of the types themselves. They appear in the schema, and they are available for the application to use if it chooses. The RPC protocol sends interface IDs when making method calls. But struct IDs generally never appear on the wire.

**Comment by sobomax** [comment]
Thanks, @kentonv for a explanation, I'll rest my case for now. 👍
