### ISSUE TITLE
Float32 constant with only integer part produces error "unable to find numeric literal operator ‘operator"" f’"

### ISSUE THREAD

**Issue by jfgo20** [capnproto/capnproto#119]
When there is a Float32 constant in the .capnp file and there is only an integer part in the float, capnpc produces this kind of code in the x.capnp.h file:

static constexpr float VALUE = 10f;

When compiling my project, I have this error: unable to find numeric literal operator ‘operator"" f’

The compiler should output 10.0f instead.

**Comment by llongint** [comment]
hi @jfgo20  , how did you solve it? I had the same problem as you.

**Comment by kentonv** [comment]
@llongint This problem was fixed in version 0.5 of Cap'n Proto -- released more than 6 years ago. If you're using an older version, you should really upgrade.
