### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [capnproto/capnproto#1196]
It is almost year since last release and almost 350 commits on top of last tag.
I think that it would be good to flush currently committed changes and make new release :)

**Comment by kentonv** [comment]
Yeah, I definitely should. I just... have to find... the time...

**Comment by vaci** [comment]
Very much looking forward to using `kj::newCrossThreadPromiseAndFulfiller()`, rather than keeping track of Executors everywhere!

**Comment by kentonv** [comment]
FWIW, you're right, I should do a release. I have had this thread starred in my e-mail inbox (which is my todo list), but am persistently swamped... trying to find time soon...

**Comment by kloczek** [comment]
THx :)

**Comment by kentonv** [comment]
Release candidate:

https://capnproto.org/capnproto-c++-0.9.0-rc1.tar.gz
https://capnproto.org/capnproto-c++-win32-0.9.0-rc1.zip

**Comment by kentonv** [comment]
Final release: https://capnproto.org/news/2021-08-14-capnproto-0.9.html

https://capnproto.org/capnproto-c++-0.9.0.tar.gz
https://capnproto.org/capnproto-c++-win32-0.9.0.zip
