### ISSUE TITLE
I cannot compile multiple capnp file in cmake file

### ISSUE THREAD

**Issue by alphamarket** [capnproto/capnproto#1199]
I am having two `.capnp` file in two different locations `src/adapters/input/capnp` and `src/adapters/output/capnp` I have came up with the following inside the cmake but it only compiles the first file not the second one, why?

```cmake
set(INTERFACE_DIR ${CMAKE_SOURCE_DIR}/src/adapters/input/capnp)
set(CAPNPC_SRC_PREFIX "${INTERFACE_DIR}")
set(CAPNPC_OUTPUT_DIR "${INTERFACE_DIR}")
capnp_generate_cpp(ADAPTERS_CAPNP_COMPILE_INPUT INTERFACE_HDRS ${INTERFACE_DIR}/input.capnp)

set(INTERFACE_DIR ${CMAKE_SOURCE_DIR}/src/adapters/output/capnp)
set(CAPNPC_SRC_PREFIX "${INTERFACE_DIR}")
set(CAPNPC_OUTPUT_DIR "${INTERFACE_DIR}")
capnp_generate_cpp(ADAPTERS_CAPNP_COMPILE_OUTPUT INTERFACE_HDRS ${INTERFACE_DIR}/output.capnp)
```

**Comment by kentonv** [comment]
Note that the cmake files are unofficial third-party contributions. I personally don't know anything about cmake. So, you may have to track down one of those contributors or possibly debug this yourself. Sorry. :confused:

**Comment by harrishancock** [comment]
@alphamarket, `capnp_generate_cpp()` won't generate anything unless a target depends on the generated source files. So, one possibility could be that a target exists which depends on `${ADAPTERS_CAPNP_COMPILE_INPUT}`, but no target exists which depends on `${ADAPTERS_CAPNP_COMPILE_OUTPUT}`.

If that's not it, then I think we'd need to see a minimal example that reproduces the behavior to diagnose what's going on.

**Comment by alphamarket** [comment]
@harrishancock Never mind I moved to compile the scripts using the capnp's compile tool manually! :)
