### ISSUE TITLE
Getting SIGSEGV while trying to serializing and deserializing in Cap'n Proto

### ISSUE THREAD

**Issue by alphamarket** [capnproto/capnproto#1202]
I am having the following capnproto structure

```capnproto
@0xcdb5a2642c01d59a;

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("Adapters::Output");

struct CapnpOutput {
    struct Dariush {
        id               @0 : UInt64;
        firstName        @1 : Text;
        lastName         @2 : Text;
    }

    result               @0: Bool;
    dariush 			 @1: Dariush;	
}
```

and there is a container class which I am passing data using that class to the capnproto, as following:

```cpp
class Dariush
{
public:
    size_t
        id = 0;

    std::string
        first_name,
        last_name;
};

class OutputPack
{
public:
    bool result;
    Dariush dariush;
};
```

And there is an adapter that is responsible to serialize the `OutputPack` class using capnproto as following:

```cpp
struct CapnpBuffer {
    size_t size = 0;
    const char* array = nullptr;
};

class CapnpAdapter {
    CapnpBuffer
        _identity_buffer;

    capnp::MallocMessageBuilder
        _builder,
        _identity_builder;

    kj::Array<capnp::word>
        _clientFlatArray,
        _outputFlatArray;
public:
    CapnpAdapter(const OutputPack& packet) {
        _packet = packet;
        init(packet);   
    }

    inline const CapnpBuffer& buffer() const { return _buffer; }
    inline const CapnpBuffer& identity_buffer() const { return _identity_buffer; }

protected:
    void init(const OutputPack& packet) {
        CapnpOutput::Builder output = _builder.initRoot<CapnpOutput>();
        output.setBool(packet.result);
        {
            auto output = _identity_builder.initRoot<CapnpOutput::Dariush>();
            output.setId(_packet.dariush.id);
            output.setFirstName(_packet.dariush.first_name);
            output.setLastName(_packet.dariush.last_name);
            _clientFlatArray = capnp::messageToFlatArray(_identity_builder);
            _identity_buffer.size = _clientFlatArray.asChars().size();
            _identity_buffer.array = _clientFlatArray.asChars().begin();
        }
        output.setDariush(_identity_builder.getRoot<CapnpOutput::Dariush>());
        _outputFlatArray = capnp::messageToFlatArray(_builder);
        _buffer.size = _outputFlatArray.asChars().size();
        _buffer.array = _outputFlatArray.asChars().begin();
    }
};
```

and I use the following function to deserialize the serialized data

```cpp
Adapters::Output::CapnpOutput::Reader capnpArrayToCapnpObject(CapnpBuffer data)
{
    auto received_array = kj::ArrayPtr<const capnp::word>(reinterpret_cast<const capnp::word*>(data.array), data.size / sizeof(capnp::word));
    ::capnp::FlatArrayMessageReader message_receiver_builder(received_array);
    auto message_receiver = message_receiver_builder.getRoot<Adamo::AdEngine::Adapters::Output::CapnpOutput>();
    return message_receiver;
}
```

when I want to perform a serialize and then deserializing the `OutputPack` object I get segment fault when trying to assert the `Dariush` object!

```cpp
Adapters::Output::OutputPack outputPacket;
auto id = 101ul;
bool result = true;
std::string fn = "My First Name!", ln = "The Last Name!";
outputPacket.result = result;
outputPacket.dariush.id = id;
outputPacket.dariush.last_name = ln;
outputPacket.dariush.first_name = fn;

auto buf = Adapters::Output::CapnpAdapter(outputPacket);
auto output = capnpArrayToCapnpObject(buf.buffer());
IS_EQUAL(result, output.getBool());
IS_EQUAL(id, output.getDariush().getId()); // <<------ I get SIGSEGV here
IS_EQUAL(fn, output.getDariush().getFirstName().cStr());
IS_EQUAL(ln, output.getDariush().getLastName().cStr());
```

What is the problem with the implementation?

**Comment by alphamarket** [comment]
I was trying to make a reproducible test case for my issue and I have encountered even more strange behavior of the capnproto library which you can see in the following gif:

![execution](https://user-images.githubusercontent.com/2348936/113678718-31f05800-96d4-11eb-84e0-f09969d82a9c.gif)

If before I try to access capnp's properties I make a simple `std::cerr` it gives me the `SIGSEGV`!

I attach the test case with this comment! 

[capnp-test.zip](https://github.com/capnproto/capnproto/files/6263096/capnp-test.zip)

**Comment by kentonv** [comment]
```cpp
Adapters::Output::CapnpOutput::Reader capnpArrayToCapnpObject(CapnpBuffer data)
{
    auto received_array = kj::ArrayPtr<const capnp::word>(reinterpret_cast<const capnp::word*>(data.array), data.size / sizeof(capnp::word));
    ::capnp::FlatArrayMessageReader message_receiver_builder(received_array);
    auto message_receiver = message_receiver_builder.getRoot<Adamo::AdEngine::Adapters::Output::CapnpOutput>();
    return message_receiver;
}
```

A struct `Reader` object is like a pointer -- it points into the buffer owned by a `MessageReader`. [This is documented here.](https://capnproto.org/cxx.html#structs)

Your function, `capnpArrayToCapnpObject()`, is returning a `Reader` that points into a `FlatArrayMessageReader` which was allocated as a local variable. When the function returns, the `FlatArrayMessageReader` is destroyed, and hence the returned `Reader` is now a dangling pointer. Accessing it would then be expected to segfault.

```
    void init(const OutputPack& packet) {
        CapnpOutput::Builder output = _builder.initRoot<CapnpOutput>();
        output.setBool(packet.result);
        {
            auto output = _identity_builder.initRoot<CapnpOutput::Dariush>();
            output.setId(_packet.dariush.id);
            output.setFirstName(_packet.dariush.first_name);
            output.setLastName(_packet.dariush.last_name);
            _clientFlatArray = capnp::messageToFlatArray(_identity_builder);
            _identity_buffer.size = _clientFlatArray.asChars().size();
            _identity_buffer.array = _clientFlatArray.asChars().begin();
        }
        output.setDariush(_identity_builder.getRoot<CapnpOutput::Dariush>());
        _outputFlatArray = capnp::messageToFlatArray(_builder);
        _buffer.size = _outputFlatArray.asChars().size();
        _buffer.array = _outputFlatArray.asChars().begin();
    }
```

This isn't related to your segfault, but FWIW, it's not necessary to have `_identity_builder` here. You can use `output.initDariush()` to create the "Dariush" struct in-place, and then fill in its fields. The code you have here creates the "Dariush" struct in a whole separate message, then copies it over into the first message; that is very expensive.

**Comment by alphamarket** [comment]
Thank you for your complete answer, can you help me with what is the correct way of writing `capnpArrayToCapnpObject(CapnpBuffer)` function to convert the char array to `Adapters::Output::CapnpOutput` object? I am bit confused now

**Comment by kentonv** [comment]
@alphamarket There's no way to write that function with exactly the signature you gave it.

Typically, what you want to do here is allocate the `FlatArrayMessageReader` on the stack in the calling function, so that it lives as long as the `Reader` does.

Alternatively, you could have your `capnpArrayToCapnpObject` function return `kj::Own<Adapters::Output::CapnpOutput::Reader>` instead, in order to return a value that has ownership of the backing buffer. To get a `kj::Own`, you could use `kj::attachVal()` to attach ownership of the `FlatArrayMessageReader` to the reader, or you could use `capnp::clone(reader)` to make a copy that owns its backing data (easier, but slower).
