### ISSUE TITLE
Ugly API

### ISSUE THREAD

**Issue by Spide85** [capnproto/capnproto#1207]
Hi,

this is a little rant about your API. Yes, I like your concept and library in general (I'm new to it). But it's very hard to get started. Where is an example of the most simple use-case: Create a message as a std::string(_view)? I tried at first something like:
```cpp
    std::ofstream of(filename, std::ios::binary);
    for (const auto &seg : message.getSegmentsForOutput()) {
        std::string_view sw(seg.asChars().begin(), seg.asChars().size());
        of << sw;
    }
```
It creates a file with some data, but reading it back in generates the error "Exception: capnp/layout.c++:560: failed: expected segment != nullptr; Message contains far pointer to unknown segment.", that does not help me at all.
```cpp
    auto raw_data = read_whole_file(filename); // returns a std::string of the whole file

    spdlog::info("size: {}", raw_data.size()); // gives the correct size

    kj::ArrayPtr<const capnp::word> arr {reinterpret_cast<const capnp::word *>(raw_data.c_str()), raw_data.size() / sizeof(capnp::word)};

    capnp::MallocMessageBuilder mb;
    capnp::initMessageBuilderFromFlatArrayCopy(arr, mb); // Error, see top

```

Sorry but I'm hardly missing the function `std::string message_to_string(const capnp::MessageBuilder &builder)` or something similar. And the opposite for reading. Not using the std lib for some arcane reason is really stupid for "normal C++ users". At least a "#ifdef USE_STD_LIB" would help.
I don't want to be unkind, I'm only a bit frustrated, because I think this is a really good library, but I'm totally struggling with the basic things. Using a reinterpret_cast is total ugly too, but I found it somewhere in Stackoverflow, where the author somehow accepted it. [(here)](https://stackoverflow.com/questions/49722870/capn-proto-de-serialize-struct-to-from-stdstring-for-storing-in-leveldb)
The functions with the `int fd` are not useful at all since this is platform dependent and my (web-)socket implementation is not giving me the fd.
Can you help me creating a simple std::string(_view) conversion function? And maybe provide it in the lib (if you really hate the std lib, something with const char* will maybe work too)? I'm sure it will not be as fast as the "native" API, but to get started with the lib, providing this basic function is needed from my perspective. To gain performance it's always possible to switch the implementation to something with the segments and mmap or foo. =)

**Comment by Dr-Emann** [comment]
The issue you're having is that capnproto needs to know where the borders of those segments are, you're writing multiple segments, then reading them back as if it was 1 big segment. You can't do that.

If you just want the easy "Just give me a flat array I can write in 1 call to fwrite", you can use `messageToFlatArray`, like

```c++
void write_file()
{
    capnp::MallocMessageBuilder builder;
    {
        auto my_message = builder.getRoot<MyMessage>();
        my_message.setMyField("hi there");
    }

    std::ofstream of("/tmp/myfile", std::ios::binary);
    kj::Array<capnp::word> flatArray = capnp::messageToFlatArray(builder);
    of.write(flatArray.asChars().begin(), flatArray.asChars().size());
    of.close();
}

void read_file()
{
    std::string s = read_whole_file("/tmp/myfile");

    // Ensure alignment and size
    assert(reinterpret_cast<uintptr_t>(s.c_str()) % sizeof(capnp::word) == 0);
    assert(s.size() % sizeof(capnp::word) == 0);
    kj::ArrayPtr<const capnp::word> word_array(reinterpret_cast<const capnp::word *>(s.c_str()),
                                               reinterpret_cast<const capnp::word *>(s.c_str() + s.size()));

    capnp::FlatArrayMessageReader reader(word_array);

    std::cout << kj::str(reader.getRoot<MyMessage>()).cStr() << '\n';
}
```

In reality, you're probably better off creating a class to wrap your websocket and implement `kj::InputStream` / `kj::OutputStream`, and use `capnp::InputStreamMessageReader(yourStream)` and `capnp::writeMessage(yourStream, yourMessageBuilder)`, which will correctly frame the message (info about number of segments/size of segments should precede the segments themselves) without having to copy to one contiguous array.

**Comment by kentonv** [comment]
Hi @Spide85,

`std::string` is for storing text. Cap'n Proto does not serialize to text, so serializing into an `std::string` seems inappropriate. I'm aware that `std::string` can technically hold arbitrary bytes, but it's not really designed for that. The documentation doesn't cover how to serialize into an `std::string` because we don't really want to lead people down that road.

You can use `capnp::messageToFlatArray()` / `capnp::FlatArrayMessageReader` (as @Dr-Emann demonstrates). Another option is to use [`kj/std/iostream.h`](https://github.com/capnproto/capnproto/blob/master/c++/src/kj/std/iostream.h) which provides implementations of KJ streams directly on top of C++ standard streams. Then you can use the appropriate C++ standard stream type for whatever you want to do (including storing into an `std::string` if that's really what you want). You can use the APIs in [`capnp/serialize.h`](https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/serialize.h) to write a message to / parse a message from a KJ stream.

**Comment by Spide85** [comment]
Hi!

Thanks for your really fast answers! At least I got (with the @Dr-Emann example) my std string function working - even if I'm unhappy with the reinterpret_cast.
Still I'm arguing that the usage of std lib in the API would be a win. You are right, std::string is semantically for storing text. But technically it's used for (raw)buffers all over the place. If you really want, a std::vector\<std::byte\> is semantically more correct. I still don't get, why you don't want to serialize into a std::basic_string or std::string_view or the semantically more correct std::vector\<std::span\<std::byte\>\> (maybe with zero copies!). I can imagine so many use-cases for it.. For example API bindings with Lua or Python, my used [websocket](https://github.com/uNetworking/uWebSockets) lib, databases and so on. Or do I miss some point?
>In reality, you're probably better off creating a class to wrap your websocket and implement kj::InputStream / kj::OutputStream, and use capnp::InputStreamMessageReader(yourStream) and capnp::writeMessage(yourStream, yourMessageBuilder), which will correctly frame the message (info about number of segments/size of segments should precede the segments themselves) without having to copy to one contiguous array.

This looks so complicated to me. Take my websocket lib, it looks like this, and normally I would expect two functions from capnp to bridge to it (to_string, from_string).
```cpp
uWS::App({    
}).get("/hello", [](auto *res, auto *req) {
    res->writeHeader("Content-Type", "text/html; charset=utf-8")
       ->end(capnp::missing_message_to_string_view(my_message)); // <<---
}).listen(9001, [](auto *listenSocket) {
    if (listenSocket) {
        std::cout << "Listening on port " << 9001 << std::endl;
    }
}).run();
```
So flat-serialization needs to be done somewhere in memory. I know, this will not work with 50Gig data, but this is another use-case. Look at [source](https://github.com/uNetworking/uWebSockets/blob/9d8e37d8a44ddbd3916ceaac1db9a70a025b04d0/src/HttpResponse.h#L378) from the socket lib, even for streaming data, it requires a flat array with final size (as std::string_view).

**Comment by kentonv** [comment]
Cap'n Proto is built on a toolkit library called KJ, which offers its own set of basic types as alternatives to the standard library. You can read a little bit about what KJ is and why it exists here:

https://github.com/capnproto/capnproto/blob/master/kjdoc/index.md

I definitely understand that when using libcapnp in a codebase that is std-heavy, the fact that it is based on an alternative toolkit may be annoying and probably hurts more than it helps. But, for projects built from the ground up on KJ, it's pretty nice. libcapnp is not going to be moving away from KJ, because it's biggest user and primary maintainer (Cloudflare Workers) is itself built on KJ. There's definitely room, though, for someone to create an alternative C++ implementation based on std types, if they want. Maybe it could be implemented as a thin wrapper...

**Comment by Dr-Emann** [comment]
How about this:

```c++
std::string message_to_data(capnp::MessageBuilder &message)
{
    std::stringstream stream;
    {
        kj::std::StdOutputStream wrapper{stream};
        capnp::writeMessage(wrapper, message);
    }
    return std::move(stream).str();
}

void message_from_data(const std::string &data, capnp::MessageBuilder &dst)
{
    std::stringstream stream{data};
    kj::std::StdInputStream wrapper{stream};
    capnp::readMessageCopy(wrapper, dst);
}
```

**Comment by Spide85** [comment]
Hi, thanks again for your answers. OK, so KJ lib as it's basis is some kind of political decision, I understand. For my personal use, I think I will get very far with the two functions from @Dr-Emann.

**Comment by kentonv** [comment]
@Spide85 It's not "political". Cap'n Proto is optimized for the use cases of the people who built and maintain it. It would be weird if we optimized for other use cases to the disadvantage of our own...

**Comment by Spide85** [comment]
For sure, this was what I meant. Maybe political is the wrong word. A lot other projects are aimed to serve as many use-cases of the (i.e.) community to get widely used and/or get famous. Cap'n Proto is tied to Cloudflares wishes and aims, so the FOSS Lib is some kind of add-on. (No negative connotation here!) Is was the thing i misunderstood in this ticket.

**Comment by kentonv** [comment]
> A lot other projects are aimed to serve as many use-cases of the community to get widely used and/or get famous.

I think that this is a common misconception. If an open source project is not generating revenue, then it's usually the case that the people building the project are just trying to meet their own needs, not for "fame".

FWIW, Cap'n Proto is my project, not Cloudflare's -- I started it long before joining Cloudflare. But right now I'm the tech lead for Cloudflare Workers, and so my focus right now is on the needs of that project.
