### ISSUE TITLE
Do you use EOT byte in your serialization?

### ISSUE THREAD

**Issue by alphamarket** [capnproto/capnproto#1211]
Hey, we use EOT `(#4  EOT (End Of Transmission))` byte in our socket transmissions to flag that the message ends during transmission, and we want to keep the same standard now that we switched to the Capnproto's serialization, I just wonder to know if you are using the EOT anywhere in your sterilization or not?

**Comment by Dr-Emann** [comment]
Capnproto is a binary protocol, it can (and will) use any byte from 0-255. In the simplest case, sending an integer with the value `4` will end up with a `\x04` byte in the output, but there are many other cases this can happen: (list lengths, size of structs, floating point values with a `\x04` bytes..

**Comment by kentonv** [comment]
@Dr-Emann haha, that's almost word-for-word what I was planning to type when I got back to my computer.

Anyway, yes, any byte can appear. The serialization is described here: https://capnproto.org/encoding.html
