### ISSUE TITLE
How to use command line "capnp encode"?

### ISSUE THREAD

**Issue by sarenameas** [capnproto/capnproto#1212]
The docs say to to use:
```
capnp encode myschema.capnp MyType < message.txt > message.bin
```
to get the final binary output expected by capnp.
But there is no exmaple on what message.txt should look like given the myschema.capnp.

Given the schema
```
struct MyType {
  name @0: Text;
  nickname @1: Text;
  age @2: UInt64;
}
```

How do I put these items in my message.txt?
I tired this:
```
(name="Billiam", nickname="Bill", age=36)
```

This gave me:
```
capnp encode: message.txt: too many arguments
Try 'capnp encode --help' for more information.
```

**Comment by kentonv** [comment]
The error is a command line usage error, not a parsing error.

Based on the error, it sounds like the command you used is not exactly the one you quoted above. You said you did this:

```
capnp encode myschema.capnp MyType < message.txt > message.bin
```

But the error suggests you might have written this:

```
capnp encode myschema.capnp MyType message.txt > message.bin
```

I.e. the `<` is missing. Is that possibly the problem?

**Comment by sarenameas** [comment]
Oh thank you! I thought those arrows were eluding to that needed to be replaced as an example like \<enter-name-here\>. I didn't realize I needed them. Thank you.

**Comment by kentonv** [comment]
Ah, yes, this is Unix shell syntax to redirect input from a file and output to a file. I recommend reading up on "unix shell redirection" to learn what this is doing.
