### ISSUE TITLE
fatal: ::read(fd, buffer, maxBytes): Connection reset by peer

### ISSUE THREAD

**Issue by jbglaw** [capnproto/capnproto#1219]
Hi!

I'm running a Laminar instance (CI build server) and sometimes, it crashes with `fatal: ::read(fd, buffer, maxBytes): Connection reset by peer` in the logs. That's with Debian's libcapnp (0.7.0-7). Seems that's from `src/kj/async-io-unix.c++`, `AsyncStreamFd::tryReadInternal()`, but up to now I didn't really get to debug it. I don't know how to trigger this and in the wild, I see this about once a week...

But maybe anybody has already seen this or knows it there's already a fix for it.

Thanks,
  Jan-Benedict

**Comment by kentonv** [comment]
`Connection reset by peer` indicates that the network connection was randomly lost. This doesn't necessarily indicate any problem with the code being executed, but rather a network connectivity issue. You can probably simulate errors like this by randomly unplugging your network or randomly killing the remote server while you're communicating with it.

Since random network disconnects are common, applications communicating over the network should usually catch them, reconnect, and retry the operation. It sounds like Laminar is not doing that. This would be a bug in Laminar, not in Cap'n Proto.

**Comment by jbglaw** [comment]
But can Laminar react to this?

 > `294   Promise<size_t> tryReadInternal(void* buffer, size_t minBytes, size_t maxBytes,`
 > `295                                   size_t alreadyRead) {`
 > `296     // `alreadyRead` is the number of bytes we have already received via previous reads -- minBytes,`
 > `297     // maxBytes, and buffer have already been adjusted to account for them, but this count must`
 > `298     // be included in the final return value.`
 > `299 `
 > `300     ssize_t n;`
 > `301     KJ_NONBLOCKING_SYSCALL(n = ::read(fd, buffer, maxBytes)) {`
 > `302       // Error.`
 > `303 `
 > `304       // We can't "return kj::READY_NOW;" inside this block because it causes a memory leak due to`
 > `305       // a bug that exists in both Clang and GCC:`
 > `306       //   http://gcc.gnu.org/bugzilla/show_bug.cgi?id=33799`
 > `307       //   http://llvm.org/bugs/show_bug.cgi?id=12286`
 > `308       goto error;`
 > `309     }`
 > `310     if (false) {`
 > `311     error:`
 > `312       return alreadyRead;`
>  `313     }`

With `KJ_NONBLOCKING_SYSCALL()` being:
> `233 #define KJ_NONBLOCKING_SYSCALL(call, ...) \`
> `234   if (auto _kjSyscallResult = ::kj::_::Debug::syscall([&](){return (call);}, true)) {} else \`
> `235     for (::kj::_::Debug::Fault f(__FILE__, __LINE__, \`
> `236              _kjSyscallResult.getErrorNumber(), #call, #__VA_ARGS__, ##__VA_ARGS__);; f.fatal())`

`read()` will have returned -1, resulting in `f.fatal()` being called. Can the caller using a `AsyncStreamFd` prevent that? (And Laminar isn't even directly using `AsyncStreamFd`, but a `kj::HttpServer`.)

**Comment by kentonv** [comment]
KJ_SYSCALL() throws an exception when the syscall fails. The application can catch that exception.

"fatal" here does not mean what you think it means, and in fact in this case `f.fatal()` is not executed because the `goto error` skips it. If you want to understand more about how KJ exceptions work, [here's some extended documentation](https://github.com/capnproto/capnproto/blob/master/kjdoc/tour.md#debugging-and-observability). Suffice to say, though, it is throwing an exception, which the application definitely can catch.

**Comment by ohwgiles** [comment]
This is fair enough, laminar can and will catch and handle this exception.

However, I would like to point out that while what you say makes total sense for (lower level) users of `kj::AsyncIoStream`, this particular case is using the (higher level) `kj::HttpServer` API, and it seems that it stops listening if `ECONNRESET` occurs on one of the client connections. I think a typical expectation would be for the server to keep listening and accepting new connections after having to drop one. If I'm not mistaken, the high level code cannot distinguish between a listening socket failure and a connected client failure, and has to restart the whole `kj::HttpServer` in either case. Not a big deal in this case, but maybe a problem for others.

**Comment by kentonv** [comment]
> and it seems that it stops listening if ECONNRESET occurs on one of the client connections.

Hmm, that shouldn't be the case -- and if it were I would expect we'd have seen severe problems in Sandstorm and Cloudflare Workers, both of which use this library to serve HTTP traffic.

Can you provide some example code which reproduces this problem?

**Comment by ohwgiles** [comment]
> if it were I would expect we'd have seen severe problems

In all likelihood I am just holding it wrong. But to demonstrate, this program:

```
// compile with
//  g++ -lkj-http -lkj-async -lkj

#include <kj/async-unix.h>
#include <kj/compat/http.h>
#include <kj/debug.h>

static const kj::StringPtr helloWorld = "Hello, World!";

class HttpTest final : public kj::TaskSet::ErrorHandler, public kj::HttpService {
public:
    void run() {
        tasks->add(
            ioContext.provider->getNetwork().parseAddress("*:8080")
            .then([this](kj::Own<kj::NetworkAddress>&& addr) {
                auto listener = addr->listen();
                kj::Own<kj::HttpServer> http = kj::heap<kj::HttpServer>(ioContext.lowLevelProvider->getTimer(), headerTable, *this);
                return http->listenHttp(*listener).attach(kj::mv(http)).attach(kj::mv(listener));
            })
        );
        tasks->onEmpty().wait(ioContext.waitScope);
    }
    virtual kj::Promise<void> request(kj::HttpMethod method, kj::StringPtr url, const kj::HttpHeaders& headers,
                                      kj::AsyncInputStream& requestBody, Response& response) override
    {
        kj::HttpHeaders respHdrs(headerTable);
        auto stream = response.send(200, "OK", respHdrs, nullptr);
        return stream->write(helloWorld.cStr(), helloWorld.size()).attach(kj::mv(stream));
    }

    void taskFailed(kj::Exception&& exception) override {
        KJ_LOG(ERROR, "HttpTest taskFailed", exception);
    }
private:
    kj::AsyncIoContext ioContext = kj::setupAsyncIo();
    kj::Own<kj::TaskSet> tasks = kj::heap<kj::TaskSet>(*this);
    kj::HttpHeaderTable headerTable;
};

int main() {
    HttpTest().run();
}
```

will happily accept multiple execs of `curl localhost:8080`. `strace` on this during `curl` shows:

```
accept4(6, {sa_family=AF_INET6, sin6_port=htons(48896), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::ffff:127.0.0.1", &sin6_addr), sin6_scope_id=0}, [128 => 28], SOCK_CLOEXEC|SOCK_NONBLOCK) = 7
setsockopt(7, SOL_TCP, TCP_NODELAY, [1], 4) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 7, {events=EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, data={u32=655562592, u64=94657439799136}}) = 0
read(7, "GET / HTTP/1.1\r\nHost: localhost:"..., 4096) = 78
```

(i.e. the client fd is always 7, for me)

So if I use this shim:

```
// compile with
//  gcc -fPIC -shared -ldl -o readshim.so

#define _GNU_SOURCE
#include <dlfcn.h>
#include <unistd.h>
#include <errno.h>
#include <stdlib.h>

static ssize_t (*real_read)(int fd, void *buf, size_t count);

static int bad_fd;

void __attribute__((constructor)) init(void) {
    real_read = dlsym(RTLD_NEXT, "read");
    bad_fd = atoi(getenv("BAD_FD"));
}

ssize_t read(int fd, void *buf, size_t count) {
    if(fd == bad_fd) {
        errno = ECONNRESET;
        return -1;
    }
    return real_read(fd, buf, count);
}
```

and run with `BAD_FD=7 LD_PRELOAD=./readshim.so ./http-test`, the application exits after the first `curl`, hitting the `taskFailed` handler.

I can work around this by catching the broken `listenHttp` promise and restarting the server, but ideally a read failure of a single client should not cause the `listenHttp` promise to break, right?

**Comment by kentonv** [comment]
@ohwgiles Looks like there is a bug after all. It only applies if the connection is delivered already-broken, which is presumably rare. #1407 has the fix. Sorry about that.
