### ISSUE TITLE
Build fails on latest MSVC headers in C++20 mode (std::uncaught_exception())

### ISSUE THREAD

**Issue by nyanpasu64** [capnproto/capnproto#1230]
In the latest MSVC from Visual Studio 2019, when compiling projects in C++20 mode, building Cap'n Proto fails because it uses `std::uncaught_exception()`, which is omitted from the headers in C++20 mode.

The only usage of `uncaught_exception` (rather than `uncaught_exceptions`) occurs in `ExceptionCallback::RootExceptionCallback::onRecoverableException()`.

https://github.com/capnproto/capnproto/blob/6b5bcc2c6e954bc6e167ac581eb628e5a462a469/c%2B%2B/src/kj/exception.c%2B%2B#L997-L1010

I don't know whether it should be hack-fixed by branching on `(bool) std::uncaught_exceptions()`, or by saving the number of uncaught exceptions or similar.

**Comment by kentonv** [comment]
Switching to `std::uncaught_exceptions() > 0` will restore the existing behavior. Per the comment, it would be nice to pay attention to the difference between the count since the last try block but if that were an easy change I probably would have done it in the first place... :)

**Comment by nyanpasu64** [comment]
Probably fixed in fe30e978ae789c704fb7622173acce4c6878125b, cherry picked to 47b6f9c47d8ee9eae647cdc64592f319356bd630 (unreleased, is it scheduled for 0.9.1?). I didn't test on MSVC though, and my vendored capnp is 0.9.0 (not 0.9.1 or master), so I can't check this exact implementation. But it looks similar to the change I made locally.

I suppose `onRecoverableException` is still not fixed to handle nested exceptions *logically correctly*?

**Comment by kentonv** [comment]
It's in the release candidate here:

https://capnproto.org/capnproto-c++-0.9.1-rc1.tar.gz
https://capnproto.org/capnproto-c++-win32-0.9.1-rc1.zip

I'll release it in a day or two but if you feel like testing before that that would be helpful.

**Comment by nyanpasu64** [comment]
Seems to work without obvious build/test issues. Though I built capnp (and capnpc-c++) from source (and cobbled together a command line with an absolute capnp.exe, -I, and -o) because I forgot about the existence of the prebuilt zip files.
