### ISSUE TITLE
kj/parse/common.h fails to compile on MSVC C++20

### ISSUE THREAD

**Issue by nyanpasu64** [capnproto/capnproto#1233]
kj/parse/common.h currently special-cases MSVC during compilation, but the special case fails to build:

https://github.com/capnproto/capnproto/blob/6b5bcc2c6e954bc6e167ac581eb628e5a462a469/c%2B%2B/src/kj/parse/common.h#L100-L111

- result_of_t was removed in C++20, causing a build failure when you try compiling with MSVC in C++20 mode.
- The non-MSVC branch compiles properly in the latest MSVC shipping with VS2019, and no longer results in a C2064 error. But I don't know if removing the MSVC branch will cause the decltype() expression to fail to build on older MSVC versions. I removed the MSVC branch locally, but I'm not sure if that's an acceptable bugfix to upstream.

**Comment by kentonv** [comment]
I think we can add `&& __cplusplus < 202000L` (or whatever is the right number) to the `#if`. Since the work-around code clearly doesn't work in C++20 mode, this is a strict improvement -- it doesn't break anyone that wasn't already broken.

If someone really wants to be able to compile this code on an older MSVC but with C++20 enabled then I guess they can work on a better fix. :)

Anyway, happy to accept a PR.

**Comment by nyanpasu64** [comment]
As I mentioned in #1232, on MSVC in c++latest mode, __cplusplus is 199711L, not 202000L or greater.

**Comment by kentonv** [comment]
> on MSVC in c++latest mode, __cplusplus is 199711L, not 202000L or greater.

How can that possibly be true? Sorry, I don't believe it.

That said, I'd also accept an `_MSC_VER` check instead. If it passes CI I'm happy.

**Comment by nyanpasu64** [comment]
https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/

oh my god it's real... MSVC unconditionally reports __cplusplus = 199711L, unless you pass in /Zc:__cplusplus in addition to /std:c++... just, what.

I don't know how to write an appropriate check. Do I disable the MSVC path if `std::result_of` is absent? There's no [feature testing flag](https://en.cppreference.com/w/cpp/feature_test#Library_features) for "result_of removed" (and `__cpp_lib_result_of_sfinae` is defined even in MSVC C++20 mode), and I don't know whether to tap into internal Microsoft defines.

Do I disable on recent MSVC? I don't know when the bug was fixed, I never saw the bug firsthand but the source code says it was there once...

I suspect that the MSVC codepath is unnecessary, because it's impossible for users to hit C2064 from decltype... The current version of Cap'n Proto rejects all MSVC versions below 1910 (VS2017). I tried compiling my vendored copy of "kj\parse\char.c++" (0.8.0 with cherry-picked patches, changed to use decltype even on MSVC) on Godbolt, by inlining all non-system header includes into Godbolt's single text field ([link to file](https://gist.github.com/nyanpasu64/9c5f314ce0904b553721bf18d19765f2)). However, even on "x86/x64 msvc v19.10 (WINE)", `decltype(instance<Parser&>()(instance<Input&>()))` didn't cause a compilation error ([link to Godbolt](https://godbolt.org/z/fq61nxzbT)), and "x86 msvc v19.0 (WINE)" instead results in `#error "You need Visual Studio 2017 or better to compile this code."`.

So I think the non-MSVC codepath works fine on MSVC, unless it's an error only triggered by files other than "parse/char.c++" including "parse/common.h". Perhaps the code path can be removed entirely?

**Comment by kentonv** [comment]
If it passes our CI, I'm happy. Try making a PR to remove the work-around an we'll see what happens.

**Comment by nyanpasu64** [comment]
Actually I found out that `_MSVC_LANG` is Microsoft's own version of the `__cplusplus` macro. One option is to check if compiling on MSVC (`_MSC_VER && !__clang__`), and if so, only use `std::result_of_t` on `_MSVC_LANG <= 201703L`. One potential future pitfall is if `std::result_of_t` fails to compile on newer MSVC even in pre-C++20 mode, much like how it fails to compile on Clang in C++14 mode, with error `no type named 'type' in 'std::result_of<kj::parse::Exactly_<char> (kj::parse::IteratorInput<char, const char *>)>'`.

Another approach is to check `_MSC_VER < 1920`, which uses decltype on all versions of VS2019 MSVC. Do you care about people using VS2019's compiler, but not the latest version? Because neither I nor the CI have tested that such compiler versions work, only that the latest VS2017 fails and the latest VS2019 works.

**Comment by kentonv** [comment]
I'm not worried about non-current patch versions... if people can't be bothered to apply patches to their MSVC then it's their problem if the code doesn't compile. :)

But I have heard plenty of people complain that major version updates can be a challenge so I do want to always support the previous major version.

**Comment by kentonv** [comment]
I would say use an `_MSC_VER` check here, so that we only use the work-around when it's really needed.
