### ISSUE TITLE
kj::Directory::tryRemove throws

### ISSUE THREAD

**Issue by ohwgiles** [capnproto/capnproto#1249]
Maybe this is intentional, but `kj::Directory::tryRemove` throws when it cannot complete recursive deletion, e.g. in case of `EACCES`. 

It is especially surprising when the implementing function is named `rmrf` since of course the eponymous command continues to recurse and delete everything it can rather than aborting on the first failure.

It seems there is no native kj way to get `rm -rf` semantics - is this something that is worth addressing? I can provide a PR if so, but in that case it would be good to agree on an API first. For example, since an implementation that continued to recurse could collect many exceptions, how should they be bubbled up if at all?

**Comment by kentonv** [comment]
KJ intentionally doesn't understand file access control. It doesn't know the difference between EACCESS, EIO, ENOMEM, etc. -- these are all just "something went wrong, give up" conditions. Meanwhile, KJ error philosophy is "if something goes wrong in a way you don't understand, stop". So the existing behavior is in fact what I intended.

If you have a use case where it's really important to ignore errors and continue, then I'd suggest writing your own code that traverses the `kj::Directory` tree and does the deletions with an appropriate try/catch wrapper. You can then customize the logic for your use case.

Maybe this is a reason why recursive removal isn't built-in to libc... different people want different things?

**Comment by ohwgiles** [comment]
That's fair enough. So just as passing observations: rmrf in the function name is misleading as the semantics are different; tryRemove is odd for the user because it implies it will not throw, but actually it only tries to avoid ENOENT, other errors will throw.

**Comment by kentonv** [comment]
OK, leaving this open with the action item being to make `tryRemove()`'s docs say more explicitly that the only difference is in the not-found case, other cases will still throw. Probably some other `try` methods should have similar clarifications.

And I suppose we can adjust `rmrf()`'s docs to say it's doesn't have exactly the semantics of `rm -rf`...
