### ISSUE TITLE
Segfault when running ASAN

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto#1252]
Not sure the exact conditions, but running our unit tests under ASAN, I observe a segfault on Worker shutdown. I observe the root exception callback getting destroyed but then a new `ExceptionCallback` is constructed. The destruction of the RootCallback results in threadLocalPointer pointing to garbage memory. Similarly, clearing it out to null wouldn't do any good because `getExceptionCallback` will reference the wrong thing. I'm still investigating it but my hunch is that we should just maybe leak the default callback?

**Comment by kentonv** [comment]
The root callback is a static local. If it's being destroyed, does that imply the process is already exiting, and running global destructors? This seems surprising since we tend to call `_exit()` to skip global destructors.

**Comment by vlovich** [comment]
Yup. That’s exactly what happens (geez, without rr this would be more time consuming)

It’s an ordering problem. At exit we destroy the static local and then we destroy the TestCase which destroys a kj::ListLink which calls throwDestroyedWhileInList. The ordering should be reversed. This might be a problem in EW bin-test harness although the potential brittleness is concerning.

Need to look more into it but clearly appears to be some kind of static order initialization problem.

**Comment by vlovich** [comment]
One way to solve this is to make the root callback global for the module instead of the function or using the constructor attribute. That carries a negative in that we always pay for initializing the root callback. Another alternative is to allocate it on the heap and leak the memory (and annotate it as OK so that LSAN is happy). Maybe just calling the getter that initializes it from the ListLink constructor might work too.

The other approach is to say it’s downstream’s problem to ensure they don’t have a global ListLink (or that if they do, that it’s initialized after the root callback).

My thought is that fixing ListLink to call that getter in the constructor or leaking the callback is a nice robust solution (specially leaking).

**Comment by kentonv** [comment]
> One way to solve this is to make the root callback global for the module instead of the function

We have a strict no-global-constructors rule (i.e., no constructors that run at program startup) -- except for in tests, where it's allowed and used for test registrations.

> fixing ListLink to call that getter

This issue isn't in any way specific to ListLink. The general problem is that, at present, if a global destructor logs or throws (or calls anything that logs or throws), then it accesses the exception callback that has already been destroyed. Of course, a global destructor throwing is still a problem independent of this, but this obscures the underlying issue. It just happens to be that in this case, it's ListLink's destructor that is throwing.

I think the options are:
* Require that any type which is explicitly intended to be globally-constructed calls getExceptionCallback() in its constructor to force the initialization ordering to be right. (I'm not really sure if this actually works...)
* Leak the root exception callback. Kind of ugly but seems generally fine.
* Make sure any test framework that relies on global constructors uses _exit(0) at the end to skip global destruction. But maybe that also disrupts sanitizers...
