### ISSUE TITLE
Json parsing of floating point should not depend on c locale

### ISSUE THREAD

**Issue by pscamodio** [capnproto/capnproto#1257]
Capnproto parseDouble function use internally the c function strtod.
strtod use the current c locale to parse the input string but the locale could use a comma "," and not a dot "." to separate decimals.

If capnproto is used on a host machine with a comma separator locale the json parsing will fail at the first floating point number.

But the json specification mandates the point as a decimal separator, so using strtod to parse floating points for json input is not robust. To keep using strtod at least it would be necessary to enfore a standard locale like "en_US.UTF-8" during the parsing and restore the original locale after the parsing is completed.

**Comment by kentonv** [comment]
Ugh that's ironic considering I personally wrote the code in protobuf that avoids this problem nearly 15 years ago.

https://github.com/protocolbuffers/protobuf/blob/f5fd897c1dccda0d5fca614616452b0ba191a859/src/google/protobuf/stubs/strutil.cc#L2407-L2476

It looks like early in Cap'n Proto's lifetime I carefully copied over the locale-independent serialization code, but at that time we didn't have any need for parsing doubles, so I didn't bother copying that. Later on, the contributor who implemented JSON parsing used plain strtod(), and I forgot about it in the review. I should have remembered that.

I guess we can fix this by copying more of my old Protobuf code.
