### ISSUE TITLE
MinGW static kj-async needs ws2_32

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [capnproto/capnproto#1258]
The dynamic library is linked against ws2_32, but as a static library this needs to be done at the final product, but it is missing in the kj-async.pc.

**Comment by kentonv** [comment]
Note that we don't actually support generating DLLs for the Cap'n Proto libraries at all. But it sounds like you're saying that even when generating static libs, kj-async.pc is incomplete?

**Comment by HazardyKnusperkeks** [comment]
Yes.

When generating static libs there have to be -lws2_32, when I added it manually it worked fine, without I got undefined references.
Then I looked how msys2 does it and they build shared libraries, so I've done that and it works.

**Comment by kentonv** [comment]
You built DLLs of Cap'n Proto, and they actually work? That's very surprising to me since we haven't marked any of the APIs with `dllexport`...

Anyway, OK, the pkg-config file issue seems straightforward enough.
