### ISSUE TITLE
how to install capnp without root authority？

### ISSUE THREAD

**Issue by devil-cry** [capnproto/capnproto#1262]
How to install capnp without root authority？

**Comment by kentonv** [comment]
`./configure` has a `--prefix` option which lets you specify an alternative install location, or you can skip installation step and use the libraries directly from where they were compiled.

Cap'n Proto works exactly the same as any other autotools/automake/autoconf project in this respect, so if you are looking for more information, try Googling for something like "automake install to home directory".
