### ISSUE TITLE
CMake Error: install(EXPORT ...) when using a project-internal copy of openssl

### ISSUE THREAD

**Issue by MixusMinimax** [capnproto/capnproto#1325]
I use CPM.cmake for dependency management, and get the following error when enabling `WITH_OPENSSL` for use in CapnProto::kj-tls:
```
CMAKE ERROR: install(EXPORT "CapnProtoTargets" ...) includes target "kj-tls"
    which requires target "ssl" that is not in any export set.
CMAKE ERROR: install(EXPORT "CapnProtoTargets" ...) includes target "kj-tls"
    which requires target "crypto" that is not in any export set.
```
I have simply disabled the entire "Install" section in `c++/CmakeLists.txt` and was thinking that maybe some kind of "INSTALL_CAPNPROTO" option would be nice. I am not sure about naming conventions there, so any other name would also work.

I have tried to somehow export ssl and crypto, but was unsuccessful, since the openssl folder wouldn't be allowed to be in the same source tree, but I was definitely doing something wrong.

**Comment by kentonv** [comment]
Thanks for the report!

The cmake files are community-maintained (I personally don't know cmake), so to fix this we'll need someone to step up and submit a PR.

**Comment by Sarcasm** [comment]
I would recommend to investigate issues on CPM or SSL side.
A similar error with explanation exists in the CPM bug tracker:

- https://github.com/cpm-cmake/CPM.cmake/issues/245

Maybe the SSL package should install/export the proper library in a similar fashion than `set(FMT_INSTALL YES)`.

**Comment by MixusMinimax** [comment]
Okay I'll look into that.
I'm not using the shorthand syntax.
The problem is that openssl itself doesn't come with a CMakeLists.txt, so I'm using janbar/openssl-cmake, which is better than nothing, but doesn't seem like it has an option for installing. I've tried doing that myself but failed to do so, so if there is another openssl cmake repo, I'd be glad to hear about it :)

**Comment by Sarcasm** [comment]
To my knowledge, KJ use FindOpenSSL correctly: find_package for its own build, find_dependency when imported via find_package  (disclaimer: apparently I'm the one who wrote this part of the kj-ssl CMake config).

I don't know how CPM works, but janbar/openssl-cmake does not export the public target OpenSSL::SSL that kj-tls uses so I guess the target is found by the [FindOpenSSL](https://cmake.org/cmake/help/latest/module/FindOpenSSL.html) module from upstream CMake, unless you are the one providing it?

FYI FindOpenSSL.cmake source code is available here:
- https://gitlab.kitware.com/cmake/cmake/-/blob/f3294e65237a1ac113a047960d3bd21cb68e3078/Modules/FindOpenSSL.cmake#L132

I tried CPM + janbar/openssl-cmake on Linux, but FindOpenSSL checks pkg-config first and it finds my system installation of OpenSSL.
I am under the impression that CPM does not provide any support code for pkg-config, so I'm not sure if it supposed to work.

If both CPM and janbar/openssl-cmake have warts, I'm not sure it is justified to workaround it in CapnProto CMake.

**Comment by MixusMinimax** [comment]
CPM Replaces "FindXXXX.cmake" files to point to the local git checkout in the build folder. This way, the entire project is System-independent, which I like. So this is the problem: this git version of OpenSSL does not create `OpenSSL::` ALIASes. So because of that, your CMake File found your specific system installation of OpenSSL. Instead you would have to create the ALIAS `add_library(OpenSSL::ssl ALIAS ssl)` (and the same for crypto), and then you should run into my problem.

But I agree, this should probably be fixed in the OpenSSL repo, but for now I'll just work with my fork of CapnProto since it was the easiest fix for me.

PS: this is the `Findopenssl.cmake` that CPM created (I guess those names aren't case-sensitive?):
```cmake
include("/mnt/c/Users/maxib/Documents/Uni/06 SoSe21/p2p/DHT-4/cmake/CPM.cmake")
CPMAddPackage(NAME;openssl;VERSION;1.1.1;GITHUB_REPOSITORY;janbar/openssl-cmake;GIT_TAG;1.1.1k-20210430)
set(openssl_FOUND TRUE)
```

**Comment by MixusMinimax** [comment]
Hm.. The FOUND variable is the concatenation the NAME argument from the CPMAddPackage call and `"_FOUND"`, So in your case I don't see why that wouldn't be `OpenSSL_FOUND`, but sure. This is essentially how I add OpenSSL too, so that's fine. The problem still seems to be that `ssl` and `crypto` are not part of any export set, and I don't know why you don't have that problem...

**Comment by MixusMinimax** [comment]
This is in my root CMakeLists.txt:
```cmake
CPMAddPackage(
        NAME capnproto
        VERSION 0.10.0
        GITHUB_REPOSITORY MixusMinimax/capnproto
        OPTIONS "BUILD_TESTING OFF" "WITH_OPENSSL ON" "EXPORT_TARGETS ON"
)
```
This is in the subfolder where I need `kj-tls`:
```cmake
set(LIBRARY_NAME rpc)

set(MODULE_HEADERS rpc.h SecureRpcClient.h SecureRpcContext.h SecureRpcServer.h)

set(MODULE_SOURCES rpc.cpp SecureRpcClient.cpp SecureRpcServer.cpp)

capnp_generate_cpp(CAPNP_SRCS CAPNP_HDRS schemas/example.capnp)

add_library(${LIBRARY_NAME} ${MODULE_HEADERS} ${MODULE_SOURCES} ${CAPNP_SRCS} ${CAPNP_HDRS})
add_library(lib::${LIBRARY_NAME} ALIAS ${LIBRARY_NAME})

target_include_directories(
        ${LIBRARY_NAME} PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>)
target_include_directories(
        ${LIBRARY_NAME} PRIVATE ${CMAKE_SOURCE_DIR}/src)

target_compile_features(${LIBRARY_NAME} PUBLIC cxx_std_20)

set_target_properties(${LIBRARY_NAME} PROPERTIES LINKER_LANGUAGE CXX)

target_link_libraries(${LIBRARY_NAME} CapnProto::kj-tls)
target_link_libraries(${LIBRARY_NAME} lib::util)
target_link_libraries(${LIBRARY_NAME} lib::logging)
target_link_libraries(${LIBRARY_NAME} CapnProto::capnp-rpc)
target_link_libraries(${LIBRARY_NAME} CapnProto::kj)
target_link_libraries(${LIBRARY_NAME} ssl)
target_include_directories(${LIBRARY_NAME} PUBLIC ${CMAKE_CURRENT_BINARY_DIR}/schemas)

[... compile options and stuff]
```

**Comment by Sarcasm** [comment]
I managed to get something working by patching janbar/openssl-cmake:

- https://github.com/Sarcasm/openssl-cmake/commit/a12caa43be2b3a3284dcab32497ce91ad78b1160

Repo with a first commit using upstream openssl-cmake that causes the issue, and a second commit that use the fork a fixes the issue:

- https://github.com/Sarcasm/cpm-kj-tls

I don't think the CMake targets export file make sense to upstream to janbar/openssl-cmake but the target_include_directories and ALIAS targets may. Feel free to propose these changes to janbar (I won't) or just use them in your personal fork.
The point is, I don't think patching CapnProto is the right approach.

**Comment by Sarcasm** [comment]
> Hm.. The FOUND variable is the concatenation the NAME argument from the CPMAddPackage call and `"_FOUND"`, So in your case I don't see why that wouldn't be `OpenSSL_FOUND`, but sure.

CPM will probably set `OpenSSL_FOUND`, however, FindOpenSSL API does not use this convention and instead use `OPENSSL_FOUND`, that's what CapnProto CMakeLists.txt rightly use.

**Comment by MixusMinimax** [comment]
Okay thanks for your help! I'll give this a try.
