### ISSUE TITLE
How to make compatible with the previous serialized file

### ISSUE THREAD

**Issue by chocoli** [capnproto/capnproto#1334]
please look at the following code.
```
// version 1                                 // version 2 
struct Person {                             struct Person {
  name @0 :Text;                              //name @0 :Text;
  email @1 :Text;                             email @0 :Text;
}                                           }
```
I serialized 'Person' of version 1 to local file 'data.bin'.  
then, I changed it to version 2 and recompiled it with capnp command.
but, in my read function, it always output the value of name, when I called `person.getEmail().cStr()`

I used to use CEREAL library. In this case, a temporary variable can help.
```
Text discard, email;
ifs >> discard >> email;
``` 
Can anybody tell me that is there any similar method or recommended way? 
I'm referring to function `printAddressBook(int fd)` in `c++/samples/addressbook.c++`

**Comment by kentonv** [comment]
Hi @chocoli,

The change you describe above is backwards-incompatible, and therefore is expected to lead to corruption. The full rules for compatibility are described in the documentation here:

https://capnproto.org/language.html#evolving-your-protocol

In particular, you cannot remove fields, and you cannot renumber fields. If there is a field you don't want anymore, you will need to rename it to `obsoleteName` or something like that, but keep the number and type the same.

Note that Cap'n Proto does not use field names on the wire. So in your example, there's no way for Cap'n Proto to know that the field `email` is the same field between the two versions.

**Comment by chocoli** [comment]
@kentonv You made that very clear, thank you!
