### ISSUE TITLE
What is the best way to include possibly non-existing imports in a file?

### ISSUE THREAD

**Issue by sarenameas** [capnproto/capnproto#1345]
Hello,

I want to share a file with people who only have the java capnp compiler while I have just the c++ capnp compiler.

I have this in the file currently (the java part commented out so that the schema will compile)
```
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("my::namespace");

using Java = import "/capnp/java.capnp";
$Java.package("com.my.package");
$Java.outerClassname("MyClassname");
```

I dont want to pull the Java capnp compiler in my primarily C++ build system and I don't want the Java folks to have to take a dependency on the C++ capnp compiler. How can I allow both of these using clauses in the same file?

Thank you!

**Comment by kentonv** [comment]
You'll need to make both `c++.capnp` and `java.capnp` available to both environments. This doesn't mean you need to install both compilers. You could, for example, copy these files into your own source tree.

Sorry, I know this is annoying but in 15 years (going back to Protobuf) no one has been able to come up with a better idea here.

**Comment by sarenameas** [comment]
Thank you

**Comment by sarenameas** [comment]
Maybe an annotation that acts like a \#ifndef and checks for environment variables?

**Comment by kentonv** [comment]
You can always write a little awk script or something that preprocesses the file, and make that part of your build. Adding a preprocessor to the language proper would be a big step that would require a lot of design work, since once we add it we can't really remove it.
