### ISSUE TITLE
Document generator?

### ISSUE THREAD

**Issue by AngryMane** [capnproto/capnproto#1369]
Are there any tools to generate documents from cap'n proto Schema?

I'm using cap'n proto to generate our IPC IF. Recently, it became necessary to create some documents for the specificatoin of these IPC IF. But there are so many IF, so I want to generate documents automatically.

**Comment by rlourette** [comment]
AngryMane, how did you make out generating docs?

**Comment by AngryMane** [comment]
@rlourette 
Finally, we created a custom plugin and generate markdown spec files.  
This plugin is developed at the worktime, so I can't share you, but I can share how to. 

# Add annotation
Cap'n Proto has a feature to add any information to node, called annotation. See https://capnproto.org/language.html. 

# Create custom plugin
You can create custom plugin and handle AST(including annotation info) of Cap'n proto schema with the plugin.  You can create this plugin with both c++ and rust. I uploaded base template plugin -> https://github.com/AngryMane/capnpc-template  

This template doesn't include how to extract infomation from each node. In this regard, `generate_code` function (See https://github.com/capnproto/capnproto-rust/blob/3bbb520205a661987e23b6d06d2b0c646b62f6c5/capnpc/src/codegen.rs#L1918)  is good reference for you.

**Comment by kentonv** [comment]
Hmm, that's too bad that your employer won't let you release this code. I can't imagine that having a capnp documentation generator is a significant competitive advantage...

**Comment by AngryMane** [comment]
I work for an outdated manufacturing company😄
