### ISSUE TITLE
calling Executor::executeAsync from non-looped thread?

### ISSUE THREAD

**Issue by risa2000** [capnproto/capnproto#1374]
I cannot figure out how to use `Executor::executeAsync` correctly (or if it is supposed to work at all) from the thread which does not run its own event loop.

The [`tour.md`](https://github.com/capnproto/capnproto/blob/master/kjdoc/tour.md) says:

 >To communicate between threads, you may use `kj::Executor`. Each thread (that has an event loop) may call `kj::getCurrentThreadExecutor()` to get a reference to its own `Executor`. That reference may then be shared with other threads. The other threads can use the methods of `Executor` to queue functions to execute on the owning thread's event loop.

>The threads which call an `Executor` do not have to have KJ event loops themselves. Thus, you can use an `Executor` to signal a KJ event loop thread from a non-KJ thread.

However, when looking at the implementation [`async.c++`](https://github.com/capnproto/capnproto/blob/a3bb240667686a007f3dd0649a093b7326e130cf/c%2B%2B/src/kj/async.c%2B%2B#L1230)
```c++
void Executor::send(_::XThreadEvent& event, bool sync) const {
  KJ_ASSERT(event.state == _::XThreadEvent::UNUSED);

  if (sync) {
    EventLoop* thisThread = threadLocalEventLoop;
    if (thisThread != nullptr &&
        thisThread->executor.map([this](auto& e) { return e == this; }).orDefault(false)) {
      // Invoking a sync request on our own thread. Just execute it directly; if we try to queue
      // it to the loop, we'll deadlock.
      auto promiseNode = event.execute();

      // If the function returns a promise, we have no way to pump the event loop to wait for it,
      // because the event loop may already be pumping somewhere up the stack.
      KJ_ASSERT(promiseNode == nullptr,
          "can't call executeSync() on own thread's executor with a promise-returning function");

      return;
    }
  } else {
    event.replyExecutor = getCurrentThreadExecutor();

    // Note that async requests will "just work" even if the target executor is our own thread's
    // executor. In theory we could detect this case to avoid some locking and signals but that
    // would be extra code complexity for probably little benefit.
  }
```
Seems to be assuming that a call for an async execution is called from the thread where `CurrentThreadExecutor` exists.

My app needs to schedule some async execution on the "looped" thread from a "non-looped" thread in order to not block the non-looped thread. Is this possible with current state of `kj`?

**Comment by kentonv** [comment]
`executeAsync()` requires that the calling thread has an event loop, since it returns a `kj::Promise`, which requires an event loop to wait on. Only `executeSync()` can be called from threads with no event loop.

Your options are:

* Use `executeSync()`.
* Use `kj::newPromiseAndCrossThreadFulfiller()`. The fulfiller can be fulfilled from any thread, including one without an event loop. You'll need to create the promise/fulfiller pair in advance, though, in the destination thread.
* Use OS-level I/O, like signals or pipes, to signal the destination thread.

**Comment by risa2000** [comment]
@kentonv What I am trying at the moment is:
1) defining `kj::TaskSet` on the thread that runs the event loop.
2) scheduling function using `Executor::executeSync()`, which adds the task (an RPC call) to the task set, something like this:
```c++
auto logRequest = logger.logRequest();
logRequest.setMessage(msg);
auto start = std::chrono::steady_clock().now();
taskSet.add(logRequest.send().ignoreResult());
auto stop = std::chrono::steady_clock().now();
```
My only observation is from timing the operation and this one seems to run faster than:
```c++
auto start = std::chrono::steady_clock().now();
logRequest.send().ignoreResult();
auto stop = std::chrono::steady_clock().now();
```
so I am assuming that adding to the `taskSet.add()` postpones the execution to the later, but I have really no clue.

The idea is that the log message has relatively high frequency and I do not care whether it was correctly received on the other end (broadcast topology).

Concerning the other option you suggested (using OS-level I/O like signals and pipes), since I should not block the event loop thread on my own, I am not sure, how should I do that. (I am no Windows).

**Comment by kentonv** [comment]
With this code:

```
auto start = std::chrono::steady_clock().now();
logRequest.send().ignoreResult();
auto stop = std::chrono::steady_clock().now();
```

You are not saving the promise returned by `logRequest.send().ignoreResult()`. When the promise is destroyed, the operation is canceled. So the request is immediately being canceled, which is probably not what you wanted. The timing is probably slower because some extra work has to be done to send a cancellation request.

See: https://github.com/capnproto/capnproto/blob/master/kjdoc/tour.md#cancellation

> Concerning the other option you suggested (using OS-level I/O like signals and pipes), since I should not block the event loop thread on my own, I am not sure, how should I do that. (I am on Windows).

You would probably need to use `Win32EventPort` directly, manually creating an OS-level pipe which you can wait on using that... unfortunately, this is not very easy, especially on Windows.

Probably the best approach is to use `kj::newPromiseAndCrossThreadFulfiller()` and `kj::MutexGuarded`. Your mutex guards a `kj::Own<PromiseFulfiller>` and a queue of messages. The receiving thread initializes this by creating a new promise/fulfiller pair. The sending thread, when it wants to send a message, locks the mutex, adds the message to the queue, and fulfills the fulfiller. The receiving thread, when it wakes up, locks the mutex, sets a new fulfiller for the next notification, and consumes the queue.

**Comment by risa2000** [comment]
> You are not saving the promise returned by `logRequest.send().ignoreResult()`. When the promise is destroyed, the operation is canceled. So the request is immediately being canceled, which is probably not what you wanted.

I have run some tests, using both handling:
```
logRequest.send().ignoreResult();
```
and
```
taskSet.add(logRequest.send().ignoreResult());
```
according to what you wrote the former should be cancelled immediately, and the latter should be run through by the taskSet? If yes then I am quite happy about using the taskSet approach.

Now, the interesting part is that I did some tests using the both approaches with different frequencies of the "log" messages. One running at approx 250 Hz - i.e. each 4ms and the other with ~ 1s period. In both cases the client receives all messages regardless the implementation and the frequency. My only interpretation is that the send operation executes before the cancel op, so the data are transmitted and this happens because the send operation takes so short time that the cancel does get scheduled only after.

**Comment by risa2000** [comment]
It turned out that
```
taskSet.add(logRequest.send().ignoreResult());
```
executed the task immediately which blocked the calling thread and eventually led into a deadlock when the connection was disrupted. So I ended up using `kj::newPromiseAndCrossThreadFulfiller()` as you suggested. There are possibly still some things I need to iron out as the disconnection handling seems to be a bit tricky, but in general it works as expected.

**Comment by kentonv** [comment]
> It turned out that
>
>     taskSet.add(logRequest.send().ignoreResult());
> executed the task immediately which blocked the calling thread and eventually led into a deadlock

Huh? No, `taskSet.add()` will return immediately, and the task runs on the event loop... nothing in KJ blocks the calling thread (except `promise.wait()`, but that's never called by any other KJ library function).

**Comment by risa2000** [comment]
You are right! I am sorry for the false conclusion. I misread the stack when debugging the deadlock. The problem was in the fact that "emitting thread" was calling `Executor::executeSync`, which got blocked in `Executor::send`, waiting for the "event loop thread" to finish the function (it never got to `taskSet.add(...)`, while at the same time, the event loop thread was trying to stop the emitting thread and waiting on it (because the logging was disabled or the receiving client simply disconnected).

I guess this is a consequence of using the `executeSync`, which one needs to use `executeSync` in order to execute `TaskSet::add` (and `executeAsync` is not possible, because the emitting thread does not run an event loop). So for true non-blocking (no collision) implementation between an even looped thread and non looped thread, using the cross thread fulfiller seems to be the only way to go.
