### ISSUE TITLE
How to serialize message to an array in packed form?

### ISSUE THREAD

**Issue by Krzmbrzl** [capnproto/capnproto#1375]
In the documentation I can only find examples of how to write a packed message to a file. However, I would like to get the packed message without having to write it to a file. Instead, I would like to serialize my packet into an array that I can then pass to other functions that send this thing over the wire.

I found `messageToFlatArray` but there doesn't seem to exist a version of this function that includes the packing step.

How would I go about this?

**Comment by kentonv** [comment]
Hi @Krzmbrzl,

You can do this using `kj::ArrayOutputStream` (which takes a fixed-length buffer and fails if the message goes over) or `kj::VectorOutputStream` (which will dynamically grow the buffer as needed), both found in [`kj/io.h`](https://github.com/capnproto/capnproto/blob/master/c++/src/kj/io.h). Then use `capnp::writePackedMessage()` to write a message to the stream.

Note that the size of a packed message isn't known in advance, hence the need for a dynamically-growing buffer to avoid any possibility of running out of space.

**Comment by Krzmbrzl** [comment]
Thanks!
