### ISSUE TITLE
`fd` in `generateRandomId()` may be not closed

### ISSUE THREAD

**Issue by FancyJan** [capnproto/capnproto#1382]
https://github.com/capnproto/capnproto/blob/6b5bcc2c6e954bc6e167ac581eb628e5a462a469/c%2B%2B/src/capnp/compiler/parser.c%2B%2B#L61

**Comment by kentonv** [comment]
Well that's embarrassing...

I guess this is only called by `capnp id` (which exits immediately) and when parsing a schema file that is missing a top-level ID (which is an error), so not a huge problem, but we should fix it.

**Comment by FancyJan** [comment]
您好，我已收到您的邮件！祝好！方子健
