### ISSUE TITLE
Accessing cap'n proto data without decoding it

### ISSUE THREAD

**Issue by katetsu** [capnproto/capnproto#1412]
I have an application that accepts multiple cap'n proto messages based on different schemas. 

Is there a way for accessing and reading the parts of a message without needing to decode it? so that i can forward it to the write processing functions where is will then get decoded.

**Comment by kentonv** [comment]
When you read a Cap'n Proto message, the implementation only "decodes" the specific fields for which you call the getter methods. Anything your code doesn't access won't be decoded at all. This is, in fact, Cap'n Proto's main design goal.

So, you can accomplish what you want by reading the message normally. :)

**Comment by katetsu** [comment]
Thanks a lot!
