### ISSUE TITLE
Need advise on best way to orgaize hierarchy

### ISSUE THREAD

**Issue by hs-apotell** [capnproto/capnproto#1423]
Looking for some advise on best way to model a class hierarchy, given that capnproto doesn't support inheritance.

- Our class hierarchy runs deep (~10 levels). There are members at each level that need to be serialized
- The entire class hierarchy is public API and I am trying to avoid introducing capnproto dependency in the headers
- Each class currently is modeled as a separate schema with all members (i.e. self + all super classes)
- I would like each class implementation to handle their own serialization rather than off-loading to other helper implementation. This is much like how constructor/destructor calls work - recursively walk to the base and on our way back initialize self.
- I can't forward declare the Reader/Builder because they are inner classes forcing inclusion of schema files in the header.
- Avoid reflection if at all possible
```
class A {
  int a;

  void load(schemas::A::Reader reader) {}
  void save(schemas::A::Builder builder) {}  
};

class B : public A {
  int b;

  void load(schemas::B::Reader reader) { 
    A::load(reader);
    .... // Read this member
  }
  void save(schemas::B::Builder builder) {
    A::save(builder);
    ... // Write this members
  }
};
class C : public A {
  int c;

  void load(schemas::C::Reader reader) { 
    A::load(reader);
    .... // Read this members
  }
  void save(schemas::C::Builder builder) {
    A::save(builder);
    ... // Write this members
  }
};
class D : public B {
  int d;

  void load(schemas::D::Reader reader) { 
    B::load(reader);
    .... // Read this members
  }
  void save(schemas::D::Builder builder) {
    B::save(builder);
    ... // Write this members
  }
};

Corresponding schema -

struct A {
  a @0 : UInt32;
};

struct B {
  a @0 : UInt32;
  b @1 : UInt32;
};

struct C {
  a @0 : UInt32;
  c @1 : UInt32;
};

struct D {
  a @0 : UInt32;
  b @1 : UInt32;
  d @2 : UInt32;
};
```
The above organization doesn't work because calls to base class load/save throws an error notifying that the parameters are wrong. There is no _implicit_ conversion from B::Reader to A::Reader.

Alternatively, if I templatize the code so the argument is left for compiler to figure out. I can get it to work, but that still introduces the need for including the schema header

```
class A {
  int a;

  template<typename U> void load(U reader) {
    .... // Read this members
  }
  template<typename U> void save(U builder) {
    .... // Write this members
  }  
};

class B : public A {
  int b;

  template<typename U> 
  void load(U reader) { 
    A::load(reader);
    .... // Read this members
  }
  template<typename U> 
  void save(U builder) {
    A::save(builder);
    ... // Write this members
  }
};
class C : public A {
  int c;

  template<typename U> 
  void load(U reader) { 
    A::load(reader);
    .... // Read this members
  }
  template<typename U> 
  void save(U builder) {
    A::save(builder);
    ... // Write this members
  }
};
class D : public B {
  int d;

  template<typename U> 
  void load(U reader) { 
    B::load(reader);
    .... // Read this members
  }
  template<typename U> 
  void save(U builder) {
    B::save(builder);
    ... // Write this members
  }
};
```

Is there a better way to organize this? We are generating nearly 200 schemas in the same header so including in this auto-generated header in all other files in the project isn't ideal - the static file size grows from 300 MB to over 3 GB in size.

Appreciate some advise!!

**Comment by kentonv** [comment]
Hi @hs-apotell,

It's hard to suggest a specific design without understanding your data model better. But, generically speaking, I would typically model such a hierarchy using a union, like:

```capnp
struct A {
  a @0 : UInt32;

  union {
    none @1 :Void;  # just A, not a derived type

    b :group {
      b @2 :UInt32;
      union {
        none @3 :Void;  # just a B, not a D
        d @4 :UInt32;
      }
    }

    c @5 :UInt32;
  }
}
```

To avoid forward declarations, you could declare a wrapper type like:

```
struct AReader {
  A::Reader reader;
}
```

Now you can forward-declare `AReader` and then use that in all your method signatures.

**Comment by hs-apotell** [comment]
@kentonv Appreciate the advice. Unfortunately, the suggested approach would get very messy and hard to maintain as the depth of the hierarchy increases. For context, I am looking at the protocol implementation for [chipsalliance/UHDM](https://github.com/chipsalliance/UHDM)

I came up with another approach which seem to work better. (Hopefully, someone someday would find it useful :))

```
struct A {
  a @0 : UInt32;
}

struct B {
  base @0: A;
  b @1: UInt32;
}
struct C {
  base @0: A;
  c @1: UInt32;
}
struct D {
  base @0: B;
  d @1: UInt32;
}
```
The `base` member always points to the _super_ class and as long as there is no multiple inheritance in the picture, this would work fine. As for the implementation, a sub-class can pass only the `base` member of its own input to recurse up. This with the suggested work-around for forward declarations would do the trick.
