### ISSUE TITLE
Support bazel build

### ISSUE THREAD

**Issue by min-tian-thomas** [capnproto/capnproto#1444]
There are more and more projects using Bazel to build everything from source code, which is a good way to get rid of dependency issues. 

Shall we add BUILD files to support Bazel build for Capnp? I will be more friendly to Bazel users to adopt this without their own build files. Meanwhile, we might also be able to add Bazel rules to generate Cpp source files from capnp protocol schema in Bazel?

If you don't mind I can move on with this.

**Comment by min-tian-thomas** [comment]
https://github.com/capnproto/capnproto/pull/1447

**Comment by JonasVautherin** [comment]
Bazel support is there, I think this can be closed :+1:.
