### ISSUE TITLE
Right way to run Cap'n Proto client on a background thread?

### ISSUE THREAD

**Issue by pgoodman** [capnproto/capnproto#1445]
I'm writing an API wrapper around a Cap'n Proto client interface. I can't guarantee that my API won't be used in a multi-threaded environment, and in fact my first use-case (in a Qt app) has it used in a QRunnable. Qt isn't my only use case, however. What I was thinking was that I would run an EzRpcClient on a background thread, get pointers to it, the interface client, and that thread's executor, then whenever I wanted to call an API, I'd used `executor->executeSync(...)`. The issue I face is that, at least in this setup, I don't know how to not have that background thread exit. I think I'd like to block on the wait scope or underlying event loop of the ezrpcclient, but I don't know how. Does this approach seem reasonable, or is there a better way of going about this?

**Comment by kentonv** [comment]
Sorry for the slow reply, I've been out for a few weeks.

To run the event loop forever, you can do: `kj::NEVER_DONE.wait(waitScope);`

**Comment by pgoodman** [comment]
I recall trying that and it throwing an exception. Anyway, I ended up landing on lazily constructing new per-thread connections, and crossing my fingers that it'll get used in a thread pool where I'll actually observe reuse.
