### ISSUE TITLE
Proposal Integrate fleece Data Structure (a superset of JSON)

### ISSUE THREAD

**Issue by frank-dspeed** [capnproto/capnproto#1479]
I have something for you as i just found your project is related to something that i use already i guess we can merge the stuff partial not the storage stuff but look yourself:

https://github.com/frank-dspeed/fleece

# Fleece

__Fleece__ is a binary encoding for semi-structured data. Its data model is a superset of JSON, adding support for binary values. It is designed to be:

* **Very fast to read:** No parsing is needed, and the data can be navigated and read without any heap allocation. Fleece objects are internal pointers into the raw data. Arrays and dictionaries can be random-accessed. Performance on real-world-scale data has been clocked at 20x that of JSON. (Want proof? See the [benchmark](Performance.md).)
* **Compact:** Simple values will be about the same size as JSON. Complex ones may be much smaller, since repeated values, especially strings, only need to be stored once.
* **Efficient to convert into native objects:** Numbers are binary, strings are raw UTF-8 without quoting, binary data is not base64-encoded. Storing repeated values once means they only need to be converted into native objects once.
* **Appendable:** Fleece is what's known as a [persistent data structure](https://en.wikipedia.org/wiki/Persistent_data_structure). A Fleece document can be mutated by appending data to it. The mutation is in effect a delta, so it's usually much smaller than the original document. And the original document is unchanged, which is great for concurrency as well as (simple) version control.

## What You Get

* Documentation, including
    * **High-level API guide "[Using Fleece](https://github.com/couchbaselabs/fleece/wiki/Using-Fleece)"**
    * The [design document](Fleece.md), with details on the data format
    * An [example](Example.md) showing the details of the encoding of a specific data structure, and a walkthrough of what happens when a program works with the resulting Fleece objects
    * Some older [performance](Performance.md) figures based on the included test suite, including comparisons to JSON parsing using Apple's Foundation framework
* A C++ reference implementation, including:
    * Encoder and decoder/accessors
    * Extensions for converting JSON directly to Fleece or vice versa
    * Extensions for encoding from and decoding to Objective-C (Foundation) object trees
    * Extensions for mutable values, making it easy to modify Fleece documents and then save them again
    * Extensions for delta compression
    * Unit tests
    * Some simple performance benchmarks
* C++ and C APIs
* A command-line tool, `fleece`, that can convert JSON to Fleece or vice versa, or dump Fleece data in a human-readable form that shows the internal structure
* Some experimental stuff:
    * A [Hash-Array-Mapped Trie](https://en.wikipedia.org/wiki/Hash_array_mapped_trie) implementation for building highly scaleable persistent hash tables in Fleece
    * At the other extreme, an extremely compact binary tree of strings that might find a use someday

## FAQ

**Q: Why does the world need yet another binary JSON encoding?**  
A: Excellent question, sock puppet! Fleece is different from [BSON](http://bsonspec.org), [PSON](https://github.com/dcodeIO/PSON), etc. in that it's been carefully designed to not need parsing. In performance tests with other binary formats I found that, while they were faster to parse than JSON, the total time was still dominated by allocating and freeing the resulting objects, as well as the conversion from UTF-8 data to platform strings. (I was using Objective-C, but similar issues would arise if using STL or GLib or other collection frameworks.) The way around this is to structure the encoded data more like a memory dump, with "pointers" (relative byte offsets) and fixed-width random-accessible arrays. That's what Fleece does. As a result, it's many times faster to work with than JSON; [literally _20x faster_](Performance.md) in the included benchmark run on a Macbook Pro.

**Comment by kentonv** [comment]
Sorry but I don't understand what you're proposing. You've copy/pasted the readme of some other serialization project that uses a very different design. What do you want us to do with this?

**Comment by frank-dspeed** [comment]
@kentonv use it as transport structure to serialize json and binary data eg allow me to do JSON or Binary input and transport that as fleece data structure.

**Comment by frank-dspeed** [comment]
but your right i will integrate that my self as you support binary transport already it is maybe out of scope for you but i found that you got multiple issues that look related out of my high level view i did not reviewed your code i just found it and jumped directly into the issues thats always the first thing i do when i find something.

**Comment by kentonv** [comment]
Sorry Frank but you're not making any sense. Cap'n Proto _is_ a binary serialization, we don't need another binary serialization.

The issues you linked don't seem to be related to anything.

**Comment by frank-dspeed** [comment]
@kentonv as sayed before your maybe correct i will now investigate into reading your code and when i understand your comment correct there will be no blocker to use capnproto as transport for the data. without reserialisation 

it came only into my mind because i saw so much talking about serialisation in this project that i was wondering about that as long as your implementation is able to transport that data untouched 

it will be a good thing.
