### ISSUE TITLE
CAPNP_LITE still includes schema defs in binary

### ISSUE THREAD

**Issue by Vadmeme** [capnproto/capnproto#1498]
On release builds in gcc and msvc the compiler does not optimize away the binary data describing the protocol if you have `CAPNP_LITE` defined.

The issue seems to be caused by the `capnp::_::AlignedData` structure not being within the bounds of the `CAPNP_LITE` check

```cpp
static const ::capnp::_::AlignedData<37> b_deadbeefcafebabe = {
  {   /* omitted */ }
};
::capnp::word const* const bp_deadbeefcafebabe = b_deadbeefcafebabe.words;
#if !CAPNP_LITE
static const uint16_t m_deadbeefcafebabe[] = {0};
static const uint16_t i_deadbeefcafebabe[] = {0};
const ::capnp::_::RawSchema s_deadbeefcafebabe = {
  0xdeadbeefcafebabe, b_deadbeefcafebabe.words, 37, nullptr, m_deadbeefcafebabe,
  0, 1, i_deadbeefcafebabe, nullptr, nullptr, { &s_deadbeefcafebabe, nullptr, nullptr, 0, 0, nullptr }
};
```

It should be solvable quite easily by moving up the `#if !CAPNP_LITE` to also include the schema data in [c++/src/capnp/compiler/capnpc-c++.c++](https://github.com/capnproto/capnproto/blob/045d5ff0e50cd044c1f05925789d5c3e46d96d21/c%2B%2B/src/capnp/compiler/capnpc-c%2B%2B.c%2B%2B#L2779)

**Comment by kentonv** [comment]
This is intended. `CAPNP_LITE` was specifically designed to trim away features that, at the time, we couldn't get to compile correctly in MSVC. Since then, MSVC has improved and lite mode is essentially obsolete.

Lite mode was not designed as a way to reduce binary size. If this is your goal, my recommendation is to use a linker that does tree shaking / dead code elimination to remove symbols that aren't referenced anywhere. This should remove all the embedded schemas, assuming you in fact don't use them.

**Comment by Vadmeme** [comment]
Thank you for your clarification

Lite mode is quite helpful for sensitive protocols where having information leak (such as field names) would cause problems. 

I ask you to consider implementing such a change as it shouldnt affect any existing users while adding extra use cases.

For now I will look into linker options to strip such data like you suggested.

**Comment by kentonv** [comment]
It sounds like what you really want is a file annotation like `$Cxx.omitSchemas` which directs the C++ code generator not to embed the schemas at all. I'm willing to accept a PR that implements this, but I don't have any use for it myself so I don't think I'll be implementing it.

Of course, if you can convince your linker to remove dead symbols that is probably a better strategy.

**Comment by Vadmeme** [comment]
I have implemented this feature in PR https://github.com/capnproto/capnproto/pull/1502
