### ISSUE TITLE
Question on kj::Array thread safety (c++)

### ISSUE THREAD

**Issue by odygrd** [capnproto/capnproto#1516]
Hello, thank you for this great library! I've been using it recently and I am wondering if it is safe to do the following:

If have two threads, one producer thread T1 and one consumer thread T2

I would like T1 to serialise the capnp message into a `kj::Array<capnp::word const>` and pass/move this array to T2. 

My current understanding is that `kj::Array` owns some memory into the internal capnp memory pool and that memory gets deallocated when the Array's lifetime ends.

I'm serialising the messages on T1 and then pushing the serialised messages into a queue as `kj::Array` in order for them to be read by the consumer T2.

On the producer T1 it looks like :

```
auto msg = std::make_shared<kj::Array<const capnp::word>>(messageToFlatArray(message));

queue_1.emplace(msg);
queue_2.emplace(msg);
queue_3.emplace(msg);
```

The consumer thread T2 consumes the queues and when the last queue is consumed, **T2 will call the destructor of kj::Array that was previously allocated by T1**

Is it safe to do something like this, or are there some internals in the capnp memory pool that are not thread safe and prevent doing this ?

**Comment by kentonv** [comment]
Hi @odygrd,

`kj::Array` just uses `malloc()` to allocate memory. As long as your `malloc()` and `free()` implementations allow freeing on a different thread (most do) then you should be fine.
