### ISSUE TITLE
what's the recommended way to handle error?

### ISSUE THREAD

**Issue by ricksapphire** [capnproto/capnproto#1524]
```c++
FILE *fd = fopen("xxx", "rb");
capnp::StreamFdMessageReader message_reader(fileno(fd));
MyMessage::Reader reader = message_reader.getRoot<MyMessage>();
```
   I read data from file with the code above. How can I check if the data is consistent with schema before read it? throw exception is not perfered

**Comment by kentonv** [comment]
If you don't want to use exceptions, you can implement `kj::ExceptionCallback` as an alternative way to receive notification of type errors. This will work even if you compile with exceptions disabled.

Note that the data is not scanned for errors upfront; errors will be detected on-demand when you try to access parts of the message. After calling the error callback, if the callback doesn't throw, the getter method will return a default value.

Moreover, note that there is no guarantee that you'll see any errors if you interpret data with the wrong schema. It's completely possible, and in fact quite normal, for a message encoded using one schema to appear to be completely valid under a different schema -- though the content you read from it is likely to be garbage. If you want to detect schema mismatches, you will need to add additional metadata to your messages which specify what schema they were encoded under.
