### ISSUE TITLE
capnp convert - syntax and --help is unclear

### ISSUE THREAD

**Issue by koitRK** [capnproto/capnproto#1533]
I can not get the convert to work no matter how I order the arguments.
My files are `log.bin` and `log.cpnp`.
The `--help` suggests following syntax `Usage: capnp convert [<option>...] <from>:<to> [<schema-file>] [<type>]`

None of these worked:
```
capnp convert log.bin packed:text log.capnp Outer
capnp convert packed:text log.bin log.capnp Outer
capnp convert packed:text log.capnp log.bin Outer
capnp convert packed:text log.capnp Outer log.bin
capnp convert packed:text log.capnp Outer
log.bin
```

--- Edit ---
Figured it out:
`capnp convert packed:text log.capnp Outer < log.bin > output.txt`

**Comment by kentonv** [comment]
Sounds like you figured it out.
