### ISSUE TITLE
Can a capnp call throw an exception?

### ISSUE THREAD

**Issue by JonasVautherin** [capnproto/capnproto#1534]
Take the simple definition below, made for pipelining (`bar(foo)`).

```capnp
interface MyInterface {
  foo @0 () -> (result :Value);
  bar @1 (someVal :Value) -> ();

  interface Value {
    read @0 () -> (value: UInt32)
  }
}
```

It works well like this, but what if `foo()` could fail? Without trying to pipeline them, it could be something like this, where `foo()` can either return a `Value` or a `Text` (or some kind of error, whatever):

```capnp
interface MyInterface {
  foo @0 () -> (result :Result);
  bar @1 (someVal :Value) -> ();

  interface Value {
    read @0 () -> (value: UInt32)
  }

  struct Result {
    union {
      value @0 :Value;
      errorMsg @1 :Text;
    }
  }
}
```

But that doesn't work with pipelining, because `bar()` takes a `Value`, and `foo()` returns a `Result`. Is there a way to achieve this with pipelining? For instance, could `foo @0 () -> (result :Value)` throw an exception instead of returning an error in the form of a `union`?

**Comment by kentonv** [comment]
Hi Jonas,

Yes, Cap'n Proto supports exceptions. If you make a pipelined call, but the first call in the pipeline throws an exception, then the exception propagates to all later calls.

I guess exceptions should be discussed more in the Cap'n Proto docs. They are covered in the KJ docs, FWIW, and Cap'n Proto extends the same model to RPC:

https://github.com/capnproto/capnproto/blob/master/style-guide.md#exceptions

https://github.com/capnproto/capnproto/blob/master/kjdoc/tour.md#debugging-and-observability

**Comment by JonasVautherin** [comment]
Oh right. Then I'm missing something somewhere (I had read the docs, I'm apparently just failing to implement it correctly) :thinking:. I'm returning an exception from the server implementation, but I seem to "lose" information on the way to the client:

The server side looks like this:

```cpp
kj::Promise<void> foo(FooContext context) override {
    auto description = kj::heapString("foo failed for some reason");
    kj::Exception exception = kj::Exception(kj::Exception::Type::FAILED, kj::mv(description), 42);
    return exception;
}
```

And the client:

```cpp
auto fooRequest = myInterface.fooRequest();
auto fooPromise = fooRequest.send();
fooPromise.then([](capnp::Response<MyInterface::FooResults> results) {
  KJ_DBG("Got some results");
}).eagerlyEvaluate([](kj::Exception&& exception) {
  KJ_DBG(exception);
}).wait(waitScope);
```

When executing, on the server side I get an info log saying:

```
capnp/rpc.c++:160: info: returning failure over rpc; exception = foo failed for some reason:42: failed
```

But on the client side I get:

```
error: remote exception: :0
```

But you're saying that the exception should pass through to the client, right? I guess I'm missing something stupid :confused:.

**Comment by kentonv** [comment]
That's odd, the exception description should have propagated through.

**Comment by JonasVautherin** [comment]
Hmm... so if I use `KJ_EXCEPTION` instead, it works:

```cpp
kj::Promise<void> foo(FooContext context) override {
    auto description = kj::heapString("foo failed for some reason");
    return KJ_EXCEPTION(FAILED, description);
}
```

This gives me:

```
debug: e = (remote):0: failed: remote exception: description = foo failed for some reason
```

But when I try to instantiate the exception myself (which I guess I shouldn't do anyway):

```cpp
kj::Promise<void> foo(FooContext context) override {
    auto description = kj::heapString("foo failed for some reason");
    return kj::Exception(kj::Exception::Type::FAILED, kj::mv(description), 42);
}
```

Then it does not propagate the description:

```
debug: e = (remote):0: failed: remote exception:
```

I will be fine with `KJ_EXCEPTION`, but I would be interested in understanding why my other version doesn't work :innocent:.
