### ISSUE TITLE
interface to std::vector

### ISSUE THREAD

**Issue by FTSSYY** [capnproto/capnproto#1549]
hello 
    I have a question to consult.
    do we have some way quickly from **::capnp::List** to **std::vector**
    or
    have a interface just like **std::vector::data()**
    
    I have a project to reform to capnproto. It will be a big problem, if we have not a way to transform **::capnp::List** to **std::vector**.

**Comment by kentonv** [comment]
Hi,

I think you should be able to copy the contents of a capnp List into a
Vector like:

    std::vector<int> vec;
    vec.insert(vec.end(), list.begin(), list.end());

I believe there's no way to construct std::vector that is directly backed
by the List's memory, for two reasons:
1. std::vector is designed to own its memory. It is not designed to point
into some external buffer.
2. A capnp::List is not necessarily encoded the same as a native array, so
you have to use the List API to access it.

-Kenton
