### ISSUE TITLE
How to serve multiple interfaces?

### ISSUE THREAD

**Issue by shivshankardayal** [capnproto/capnproto#1556]
The calculator example serves one interface. If I have multiple interfaces how do I make them work? A small example would be very nice.

**Comment by kentonv** [comment]
Hi @shivshankardayal,

An interface can return other interfaces. So, I would suggest defining a top-level interface define methods to get other interfaces:

```capnp
interface Main {
  getFoo @0 () -> (foo :Foo);
  getBar @1 () -> (bar :Bar);
}

interface Foo {
  # ...
}

interface Bar {
  # ...
}
```

(Interfaces also support inheritance, which is more appropriate when the interfaces represent the same logical object.)
