### ISSUE TITLE
LocalReponse destructor invalidates read values

### ISSUE THREAD

**Issue by yakiro-nvg** [capnproto/capnproto#1575]
Usually, we want the Response and the result on the same line.

```C++
auto result = req.send().wait(ws).getResult();
```

It worked well until I upgrade the environment to Ventura 13.0.1, Xcode 14.1.

```C++
auto rep = req.send().wait(ws);
auto result = rep.getResult();
rep.~Response();
// result becomes invalid
```

The Response destructor invalidates our read result, is this expected behavior?

It's UT code so the Response is LocalResponse, with no network involved.

Environment:
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix

**Comment by kentonv** [comment]
Yes, this is expected (assuming `result` is not a primitive integer type). The `Response` object owns the backing buffer for the message. `getResult()` returns some sort of `T::Reader`, which behaves like a pointer, pointing into that backing buffer. The `Response` must outlive it. This has always been the case.
