### ISSUE TITLE
[Question] how to install capnproto library with -O3 option

### ISSUE THREAD

**Issue by hsvacuum** [capnproto/capnproto#1589]
Following https://capnproto.org/install.html build capnproto library with -O2 compiler option. Is there any recommended way of installing capnpproto library by building it with -O3 option instead of -O2? Also, is there any reason for using -O2 istead of -O3 option in the installer?

**Comment by kentonv** [comment]
`-O2` is the default used by the build system, GNU autotools. You'd have to ask them why it is the default. However, it's easy to change with a flag to `configure`, like so:

```
./configure CXXFLAGS=-O3
```

**Comment by jclee** [comment]
FWIW, I noticed that capnproto's autotools configuration is set up such that if no `CFLAGS`/`CXXFLAGS` values are provided, it will use a default of `-O2 -DNDEBUG` (as opposed to the usual autotools defaults of `-g -O2`:

https://github.com/capnproto/capnproto/blob/master/c%2B%2B/configure.ac#L10-L15

So you might need to do something similar, to get a build that only differs by the optimization flag, like maybe?:
```
./configure CXXFLAGS="-O3 -DNDEBUG"
```

(I assume the `CFLAGS` value is effectively irrelevant in a C++ project, but could be set similarly, if desired.)

**Comment by kentonv** [comment]
@jclee good point, I updated my answer
