### ISSUE TITLE
I am unable to use absolute path imports

### ISSUE THREAD

**Issue by hmuendel** [capnproto/capnproto#1595]
Hello and thank you for this nice tool.
In the way I understood the docs and cli help, I should be able to import files from outside the current schema folder by passing the `-I` flag to the compile command. This fails with `error: Import failed: <path to file>`
Copying the exact same file right next to my schema file and changing the import path to non absolute compiles fine.

I now tried for some time to figure it out, but I am unable to.

Here is a minimal example:

```bash
> uname -srmo
Linux 6.1.1-arch1-1 x86_64 GNU/Linux

> capnp --version
Cap n Proto version 0.10.2

> pwd
/tmp/capnp

> tree
.
├── A
│   ├── a.capnp
│   ├── b.capnp
│   └── c.capnp
└── B
    └── b.capnp

3 directories, 4 files

> cat A/a.capnp
@0x8e4986f5ac37ebbe;

using Bar = import "/tmp/capnp/B/b.capnp";

struct A {
	bs @0 :List(Bar.B);
}

> capnp compile -oc++ --verbose --import-path=/tmp/capnp/B A/a.capnp
A/a.capnp:3:20-42: error: Import failed: /tmp/capnp/B/b.capnp
A/a.capnp:6:14-17: error: Not defined: Bar
A/a.capnp:6:9-13: error: 'List' requires exactly one parameter.

> cat /tmp/capnp/B/b.capnp
@0xb7169ccabccfe69e;

struct B {
    name @0 :Text;
}

> ls -l
total 0
drwxr-xr-x 2 user user 100 Dec 27 23:55 A
drwxr-xr-x 2 user user  60 Dec 27 23:27 B

> ls -l A
total 12
-rw-r--r-- 1 user user 101 Dec 28 00:04 a.capnp
-rw-r--r-- 1 user user  54 Dec 27 23:29 b.capnp
-rw-r--r-- 1 user user  80 Dec 28 00:04 c.capnp

> ls -l B
total 4
-rw-r--r-- 1 user user 54 Dec 27 23:23 b.capnp

> cat A/c.capnp
@0x8e4986f5ac37ebbe;

using import "b.capnp".B;

struct A {
	bs @0 :List(B);
}

> capnp compile -oc++ --verbose --import-path=/tmp/capnp/B A/c.capnp

> diff A/b.capnp B/b.capnp
```

**Comment by jclee** [comment]
I'm not sure exactly which documentation you're referring to -- perhaps this?: https://github.com/capnproto/capnproto/blob/3927c10d/doc/language.md?plain=1#L582-L584

> The above imports specify relative paths.  If the path begins with a `/`, it is absolute -- in this case, the `capnp` tool searches for the file in each of the search path directories specified with `-I`.

You seem to be interpreting this to mean that if you import an absolute path in a `.capnp` file, then running `capnp -I` with some absolute prefix of that path grants `capnp` permission to read the specified absolute path in the filesystem, but that's not actually how `capnp` interprets the option.  Instead, it interprets an "absolute" path to mean "some path relative to one of the import directories".  So it actually searches for the file by converting the absolute path into a path relative to the root, then concatenating it with each of the import directories.

So, for example, in your first case it converts `"/tmp/capnp/B/b.capnp"` to `"tmp/capnp/B/b.capnp"`, then concatenates it with the `-I` directory to yield `"/tmp/capnp/B/tmp/capnp/B/b.capnp"`, which indeed does not exist.

To make your example work, I think you'd need to instead do:
```
# in A/a.capnp
using Bar = import "/b.capnp";

> capnp compile -oc++ --verbose --import-path=/tmp/capnp/B A/a.capnp
```

(Another possibility might be to specify `-I /`, but that would allow capnp to read any file in the filesystem, which might allow security abuses.)

Perhaps the import documentation could be clarified to eliminate this particular point of confusion?

**Comment by hmuendel** [comment]
Thank you very much, for the quick help.
I was indeed referring to this piece of documentation and also the the cli help:
```
Options:
    -I<dir>, --import-path=<dir>
        Add <dir> to the list of directories searched for non-relative imports
        (ones that start with a '/').
```
This and the error message did not bring me to the right track. Rereading the documentation with knowledge of your comment, makes it now clear to me and it is indeed not an unusual behavior for import paths. I guess the notion of absolute paths confused me,  because it is overloading the usual OS logic. 
Also why do we distinguish between absolute and relative imports? The behavior could also be:
- import local folder
- if that failed import from import paths in order
This would feel more intuitive to me.

I will make a PR against the documentation and propose a wording, that would had helped me to avoid the confusion.
