### ISSUE TITLE
Waiting for executeSync to complete in Windows may hang forever

### ISSUE THREAD

**Issue by fabiorossetto** [capnproto/capnproto#1623]
We have observed that under certain conditions `executeSync` may hang forever in Windows. Unfortunately I could not create a simple standalone example to reproduce the issue. However, I think I know what the issue is.

When the executor is sleeping, it can be resumed by calling `wake()`. On Windows, this causes `PostQueuedCompletionStatus` to be called. This in turn causes `waitIocp` to resume from sleep. 

So the standard flow of `executeSync`, as far as I understand it is:
- Post an event to the executor event loop
- Call `EventPort::wake()` to resume the event loop
- Wait until the event has executed and the result is available

Howeve I think there's a catch. `waitIocp` is called also by `~IoPromiseAdapter()`. So if `wake()` is called while waitIocp is executing within `IoPromiseAdapter` destructor, by the time `wait()` is called the event sent by `wake` has already been consumed. Thus `wait` waits to be resumed forever and `executeSync` hangs.

Can someone have a look at the code and confirm this can happen?

**Comment by kentonv** [comment]
Hi @fabiorossetto,

Yes, your analysis looks correct to me. It looks like `wait()` needs to call `receivedWake()` at the start of the function and, if it returns true, perform a poll instead and return true.

Would you care to submit a PR? You might have an easier time testing this than me as I don't actually have a Windows machine.

**Comment by fabiorossetto** [comment]
I'll try to make one. I should have some time in two weeks

**Comment by fabiorossetto** [comment]
I've created an MR, can you check if this is what you had in mind? https://github.com/capnproto/capnproto/pull/1631
