### ISSUE TITLE
Some test failed on CircleCI Ubuntu 22.04 environment

### ISSUE THREAD

**Issue by chengguizi** [capnproto/capnproto#1657]
Here is the full log, 0.10.3 version checked out. It runs fine with 20.04 on CircleCI. Also runs ok on lxc ubuntu22.04.

[circleci-ubuntu2204-capnproto.zip](https://github.com/capnproto/capnproto/files/11187359/circleci-ubuntu2204-capnproto.zip)

May I know what could be the cause of this? Thanks!

**Comment by kentonv** [comment]
This is a duplicate of #1652.
