### ISSUE TITLE
Why is `miniposix.h` not installed?

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [capnproto/capnproto#1658]
For https://github.com/capnproto/pycapnp/pull/310, I'm updating a lot of the code copied from `async-io-unix.c++` to the latest version in this repo. This code now relies on `miniposix.h`, which is not [installed](https://github.com/capnproto/capnproto/blob/851a9e23ea4fb2f1dd0a2d34924407ee612d1da2/c%2B%2B/Makefile.am#L140). Is there any particular reason for this?

**Comment by kentonv** [comment]
This is a private internal header, it is not intended for consumption by dependents of Cap'n Proto. If you find you need this functionality, I would recommend copying it into your own project -- that way you are not broken if it changes in the future.
