### ISSUE TITLE
[ FAIL ] capnp/encoding-test.c++:1877: legacy test: Encoding/Generics (211 μs) on ppc64le

### ISSUE THREAD

**Issue by vt-alt** [capnproto/capnproto#1660]
One test failed on ppc64le for 0.10.4.
```
[00:01:54] + make -j43 check
...
[00:04:02] [ TEST ] capnp/encoding-test.c++:1877: legacy test: Encoding/Generics
[00:04:02] capnp/layout.c++:2182: failed: expected boundsCheck(segment, ptr, ref->structRef.wordSize()); Message contained out-of-bounds struct pointer.
[00:04:02] stack: 7fff99b8a8a7 130aca503 7fff9989482f
[00:04:02] [ FAIL ] capnp/encoding-test.c++:1877: legacy test: Encoding/Generics (211 μs)
...
[00:04:02] 960 test(s) passed
[00:04:02] 1 test(s) failed
[00:04:02] FAIL: capnp-test
[00:04:02] Randomly testing backwards-compatibility scenarios with seed: 1681667244
[00:04:02] PASS: capnp-evolution-test
[00:04:02] PASS: src/capnp/compiler/capnp-test.sh
[00:04:02] ===========================================
[00:04:02] 1 of 3 tests failed
```

There is temporary full build log https://git.altlinux.org/tasks/318593/build/100/ppc64le/log

ps. (On aarch64, i586, x86_64 there are no problems.)

**Comment by kentonv** [comment]
This is very strange that this one test would be affected while everything else works.

Can you try running with `./configure CXXFLAGS='-g -no-pie' --disable-shared`, which should allow the stack trace to be symbolized?

**Comment by vt-alt** [comment]
We build with LTO (`-flto=auto`), and I know it can cause mysterious behavior due to compiler bugs (we have gcc version 12.2.1). So, I disabled the LTO build, and the test failure disappeared. (Perhaps no need to debug further, if you not insist, so I close the issue.)

**Comment by kentonv** [comment]
Hmm that's mildly disturbing. We did have a case once in the past where [a compiler optimization introduced a vulnerability](https://github.com/capnproto/capnproto/blob/master/security-advisories/2017-04-17-0-apple-clang-elides-bounds-check.md). This wasn't a bug in the compiler -- we were technically depending on undefined behavior. There could be something similar going on here.

But it's entirely up to you if you want to spend time looking into it or just move on.

**Comment by vt-alt** [comment]
I compiled it as you instructed. What should I look for next?

I tried to set a breakpoint at the location of the test, but it doesn't seem to have worked:
```
builder@powerpc64le:~/RPM/BUILD/capnproto-0.10.4/c++$ gdb -q --args ./capnp-test -f capnp/encoding-test.c++:1877
Reading symbols from ./capnp-test...
(gdb) list capnp/layout.c++:2182
2177        KJ_REQUIRE(ref->kind() == WirePointer::STRUCT,
2178                   "Message contains non-struct pointer where struct pointer was expected.") {
2179          goto useDefault;
2180        }
2181
2182        KJ_REQUIRE(boundsCheck(segment, ptr, ref->structRef.wordSize()),
2183                   "Message contained out-of-bounds struct pointer.") {
2184          goto useDefault;
2185        }
2186
(gdb) hb capnp/layout.c++:2182
No hardware breakpoint support in the target.
(gdb) b capnp/layout.c++:2182
Breakpoint 1 at 0x105df694: capnp/layout.c++:2182. (3 locations)
(gdb) b main
Breakpoint 2 at 0x100388a8: file src/kj/test.c++, line 363.
(gdb) r
Starting program: /usr/src/RPM/BUILD/capnproto-0.10.4/c++/capnp-test -f capnp/encoding-test.c++:1877
Warning:
Cannot insert breakpoint 2.
Cannot access memory at address 0x100388a8
Cannot insert breakpoint 1.
Cannot access memory at address 0x105df694
Cannot insert breakpoint 1.
Cannot access memory at address 0x1073bafc
Cannot insert breakpoint 1.
Cannot access memory at address 0x1073bb44

(gdb)
```

**Comment by vt-alt** [comment]
> I tried to set a breakpoint at the location of the test, but it doesn't seem to have worked:

It seems that this (well known gdb) failure is due to the read-only `/proc` mount. I may be able to fix it later.
