### ISSUE TITLE
putting a field into a new union is not forward compatible

### ISSUE THREAD

**Issue by pompon0** [capnproto/capnproto#1694]
As per https://github.com/capnproto/capnproto/issues/1424 I understand that https://capnproto.org/language.html#evolving-your-protocol states schema changes which are intended to be both backward and forward compatible.

I've found a problem with the following point:
* "A field can be moved into a group or a union, as long as the group/union and all other fields within it are new."

For example, if you evolve schema from
```
struct B1 {
  x @0: UInt64;
}
```
to
```
struct B2 {
  union {
    x @0: UInt64;
    y @1: UInt32;
  }
}
```
And you encode a `B2` message with `y` set, it will silently decode to `B1` with garbage `x` value.

**Comment by pompon0** [comment]
yes, it would be nice to annotate which schema changes are backward + forward compatible and which ones are only backward compatible. Also, as you mentioned in https://github.com/capnproto/capnproto/issues/1424 backward-only compatibiliy is not very useful in the first place, so perhaps it would be better to just remove unionization from the list of "compatible changes" altogether?

**Comment by kentonv** [comment]
In practice I have used retroactive unionization many times and it is quite useful. There are often ways that you can guarantee that you won't set the new value in messages sent to old readers, or you may be able to update all readers before starting to use the new union member.
