### ISSUE TITLE
[1.0.0] Windows Release x64 build compile errors

### ISSUE THREAD

**Issue by aabosen** [capnproto/capnproto#1740]
I excitedly downloaded the new rev 1.0.0 and went to build it on Windows with Visual Studio 2019.  When I build with the "Debug" configuration, everything goes great, no problems.  When I switch from Debug configuration to Release, the "ALL_BUILD" fails with lots of compile errors:
2>    C:\Downloads\capnproto-c++-win32-1.0.0\capnproto-c++-1.0.0\src\kj\exception.c++(574,3): error C2059: syntax error: ')'
2>    C:\Downloads\capnproto-c++-win32-1.0.0\capnproto-c++-1.0.0\src\kj\exception.c++(574,3): error C2065: 'f': undeclared identifier

Visual Studio says there 2311 errors.  Looks like these are related to using the KJ_ preprocessor macro calls, like KJ_WIN32, KJ_EXPECT, EXPECT_FALSE, EXPECT_TRUE.  Running the Debug configuration build has no errors at all, so looks like something is very confused about the Release build configuration.

Going back to version 0.10.4 it compiles fine for both Debug and Release configurations - same Visual Studio 2019 setup.  Can someone else try the Windows Release build configuration on version 1.0.0 and see if they have the same problems?

**Comment by heetaekim** [comment]
@aabosen 
I am seeing same issue too... i just removed NDEBUG preprocessor definitions (for now) which builds fine with Relesae

**Comment by throwable-one** [comment]
I also see that https://github.com/capnproto/capnproto/issues/1765

**Comment by kentonv** [comment]
I've released 1.0.1 with the fix for this. Sorry for the trouble.
