### ISSUE TITLE
Are generated C++ sources the same on all platforms?

### ISSUE THREAD

**Issue by teo-tsirpanis** [capnproto/capnproto#1812]
In our C++ codebase that uses capnproto, we add in source control the files generated by the `capnp` tool. Because in the past the tool generated different files for Windows and Linux, we store both versions of them. Recently however, we 've been noticing that the Windows and Linux files are identical and would like to merge them.

Is this always the case? Does `capnp` generate identical output on all platforms (barring differences such as line endings)? We are on version 0.8.0.

**Comment by kentonv** [comment]
Yes, the generated code is (and always has been) identical on all platforms. We use `#ifdef` inside the generated code to guard any platform-specific bits.
