### ISSUE TITLE
Cross-compilation issues

### ISSUE THREAD

**Issue by robert-llf** [capnproto/capnproto#1815]
Hello, I am compiling "capnproto-release-1.0.0" with a cross-compiler(aarch64-linux-gnu), and when I use the make command, I get an error like this:
> ./capnp compile --src-prefix=./src -o./capnpc-c++:src -I./src $(for FILE in src/capnp/test.capnp src/capnp/test-import.capnp src/capnp/test-import2.capnp src/capnp/compat/json-test.capnp; do echo ./$FILE; done)
./capnp: line117: /home/ubuntu/WorkSpace/libcode/capnproto-release-1.0.0/c++/.libs/lt-capnp: Unable to execute binary: The executable file is malformed
./capnp: line117: /home/ubuntu/WorkSpace/libcode/capnproto-release-1.0.0/c++/.libs/lt-capnp: succeed
Makefile:3981: recipe for target 'test_capnpc_middleman' failed
make: *** [test_capnpc_middleman] Error 126

My compilation process is as follows
> cd ./capnproto-release-1.0.0/c++/
autoreconf  -i
./configure --host=aarch64-linux CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ --prefix=/home/ubuntu/WorkSpace/LIB/capnproto
make -j4 check

But when I don't use the cross-compiler, it compiles successfully
> cd ./capnproto-release-1.0.0/c++/
autoreconf  -i
./configure --prefix=/home/ubuntu/WorkSpace/LIB/capnproto
make -j4 check

How to solve this problem? Can I not compile the 'test_capnpc_middleman' part? If can, how do I set it up?

**Comment by kentonv** [comment]
When cross-compiling, you must first install the same version of capnp locally on your machine, then when you invoke `./configure` for cross-compilation, pass the `--with-external-capnp` flag. This tells the makefiles to use your installed copy of capnp instead of the copy that was created as part of the build (which is for a different architecture).

**Comment by garymm** [comment]
Is there any way to disable the test_capnpc_middleman so that executing capnp is not required? If not, could you provide one?
I'm having a hell of a time getting the cross compilation working for conda-forge in https://github.com/conda-forge/capnproto-feedstock/pull/42

**Comment by kentonv** [comment]
@garymm `test_capnpc_middleman` is only needed to compile the tests. But for some reason, autotools sets things up so just running `make` builds this target, even though it should only be needed for `make check`. I don't understand why this is but I'd welcome a PR that fixes it. However, it looks like as a work-around you can specify all the individual targets:

```
make libkj.la libkj-test.la libkj-async.la libkj-http.la libcapnp.la libcapnpc.la libcapnp-rpc.la libcapnp-json.la libcapnp-websocket.la capnp capnpc-c++ capnpc-capnp
```

It looks like this command does not build `test_capnp_middleman`.
