### ISSUE TITLE
Remote Object Lifetime

### ISSUE THREAD

**Issue by lewisxy** [capnproto/capnproto#1831]
I just started playing around with this library, and so far it looks great. However, from the calculator example, the server side object is created with [`kj::heap`][kj-heap] before they are sent to the client. This seems to suggest that there is no way for server to manage these object directly. For example, what if the server want to return the same object reference to different client or across calls from the same client? Or destroy that object (such that all subsequent call from any client with that object throws exception)? 

Obviously, I can wrap some shared data structure in the implementation of the corresponding `MyInterface::Server` class. But this doesn't feel very elegant.

[kj-heap]: https://github.com/capnproto/capnproto/blob/ac91386f32313704503a0b43301cd9084dd01e11/c%2B%2B/samples/calculator-server.c%2B%2B#L172

**Comment by kentonv** [comment]
> For example, what if the server want to return the same object reference to different client or across calls from the same client?

You can do this by converting the object to a `Client` once, and then returning that same `Client` from multiple RPC calls:

```
MyInterface::Client client = kj::heap<MyInterfaceImpl>();
```

`Client`s are references to the server which can be passed over the network. They use reference counting -- you can copy a `Client`, and only once all `Client`s are destroyed (including remote ones), the server object will be destroyed.

> Or destroy that object (such that all subsequent call from any client with that object throws exception)?

You can use `capnp::RevocableServer` to create a `Client` that does not "own" the thing it points at, and starts throwing exceptions if the target object goes away.

https://github.com/capnproto/capnproto/blob/ac91386f32313704503a0b43301cd9084dd01e11/c++/src/capnp/capability.h#L564
