### ISSUE TITLE
get Server from Client during server implementation

### ISSUE THREAD

**Issue by lewisxy** [capnproto/capnproto#1839]
Interface is a great way to represent "opaque remote object", however, I am struggling to use it.

Consider the following API interface
```
interface Api {
  interface OpaqueHandle {}
  create @0 (someParameters :Text) -> (handle :OpaqueHandle);
  doSomething @1 (handle :OpaqueHandle, otherParameters :Text) -> (returnValueIsNotImportant :Text);
}
```
`OpaqueHandle` represents some object on the server, client creates such object using `create`, and operate on this object using `doSomething`. `OpaqueHandle` interface has no exported methods because we don't want user to operate on it directly. On the server, however, `OpaqueHandle` is implemented by `OpaqueHandleImpl` and has methods that can do things.
```c++
class OpaqueHandleImpl final : public Api::OpaqueHandle::Server {
public:
  SomeNonSerializedType getInformationNeededToDoSomething();
private:
  MyObject someImportantField_
}
```

On the client side, the value returned from `create` has type `Api::OpaqueHandle::Client`, which is fine. However, in the server implementation for `doSomething`, we also get the `Api::OpaqueHandle::Client`, and apparently there is no way to get the `OpaqueHandleImpl` object that it refers to.
```c++
kj::Promise<void> ApiImpl::doSomething(DoSomethingContext context) {
  // this has type Api::OpaqueHandle::Client, how do we get the `OpaqueHandleImpl` object?
  context.getParams().getHandle();
  // ...
}
```
How do we get `OpaqueHandleImp` on the server?

While I could restructure the `Api` by putting `doSomething` method in `OpaqueHandle`, but is it the only way? This is very much a simplified example, in reality, there are many types of remote objects similar to `OpaqueHandle` and many methods similar to `doSomething`, and some of those methods takes more than one type of remote objects similar to `OpaqueHandle`.

**Comment by vaci** [comment]
You can use a CapabilityServerSet to recover a previously registered implementation of a client:

https://github.com/capnproto/capnproto/blob/v2/c%2B%2B/src/capnp/capability.h#L693

**Comment by kentonv** [comment]
Yes, `CapabilityServerSet` is the answer here -- it lets you unwrap your own objects when they return to you.

**Comment by lewisxy** [comment]
Thanks for providing this. After reading the documentation and test cases, I am still a bit confused about how should I recover the server implementation. For example, suppose I defined the following interface.
```
interface OpaqueHandle {} 
```

And I have 2 (or more) implementations of it.

```c++
class OpaqueHandleImpl1 final : public Api::OpaqueHandle::Server {
public:
  ReturnType SomeFunction(ParamType params);
private:
  MyObject someImportantField_;
}

class OpaqueHandleImpl2 final : public Api::OpaqueHandle::Server {
public:
  ReturnType2 SomeFunction2(ParamType2 params);
private:
  MyObject2 someImportantField2_;
}
```
I could add both of them to the same `CapabilityServerSet<OpaqueHandle>` since both implementations inherits `Api::OpaqueHandle::Server`. 
However, when I am trying to use it, the `Api::OpaqueHandle::Client` is supplied by the client, so we don't know the type, and `getLocalServer()` will return an object of type `kj::Promise<kj::Maybe<typename Api::OpaqueHandle::Server&>>`. How should I determine which implementation is it? I can probably come up with some hacks with `dynamic_cast`, but it feels weird. Even if there is only 1 implementation, I still need to somehow cast it back to the implementation type. What's the correct way to use it?

**Comment by lewisxy** [comment]
Right now, as a workaround, I created a `HandleTable` which maps handles (integers) to server side objects, and does the corresponding translation when client supplies handles. However, there are several major downside with this approach.
1. I need to validate if the handle (supplied by the client) is still valid and is the correct type.
2. I need to implement a `invalidate(handle)` method to allow client invalidate a handle (and the server will remove it from `HandleTable`, which is clunky and less elegant than a `Capability::Client`.
3. Because they are integers (or string/struct if you make it that way), the client cannot use pipelined call, which makes the API cumbersome.

For these reasons, I really hope I can get `CapabilityServerSet` to work.

**Comment by kentonv** [comment]
I would recommend making `OpaqueHandleImpl1` and `OpaqueHandleImpl2` both inherit some intermediate type `OpaqueHandleImplBase` which in turn inherits `OpaqueHandle::Server`.

```
class OpaqueHandleImplBase final : public Api::OpaqueHandle::Server {
public:
  virtual void someCommonOperation() = 0;
};

class OpaqueHandleImpl1 final : public OpaqueHandleImplBase {
  ...
}

class OpaqueHandleImpl2 final : public OpaqueHandleImplBase {
  ...
}
```

Since you then know that all objects in your `CapabilityServerSet` implement `OpaqueHandleImplBase`, you can safely downcast to that type (with `static_cast`, not `dynamic_cast`).

This base type should ideally provide virtual methods to do whatever operations you might need to do on an object after unwrapping it via `CapabilityServerSet`. Or, it could simply provide a `getType()` method which tells the caller which type it is, so the caller can downcast it (but that's only slightly better than just using `dynamic_cast` in the first place).

**Comment by lewisxy** [comment]
Thanks, this is pretty close to what I figured out as well. The only remaining question is about the lifetime of server and client when interacting with `CapabilityServerSet`.

Specifically, the [comments under `getLocalServer`][getlocalserverdoc] says
> ...Keep in mind that the server will be deleted when all clients are gone, so the caller should make sure to keep the client alive (hence why this method only accepts an lvalue input)

Does it mean that we must keep at least one `Client` object when calling `getLocalServer()` and before the promise it returns resolved (or cancelled)?

Consider the following example,
```
interface MyAPI {
  interface MyHandle {}
  getHandle @0 (id :UInt64) -> (result :MyHandle);
  useHandle @1 (handle :MyHandle) -> (result :UInt64);
}
```
```c++
class MyHandleImpl1 final : public MyAPI::MyHandle::Server {
public:
    MyHandleImpl1(uint64_t id) : id_(id) {}
    uint64_t getId() { return id_; }
private:
    uint64_t id_;
};

class MyAPIImpl final : public MyAPI::Server {
public:
    kj::Promise<void> getHandle(GetHandleContext context) {
        uint64_t id = context.getParams().getId();
        context.getResults().setResult(set_.add(kj::heap<MyHandleImpl1>(id)));
        return kj::READY_NOW;
    }

    kj::Promise<void> useHandle(UseHandleContext context) {
        MyAPI::MyHandle::Client client = context.getParams().getHandle();
        return set_.getLocalServer(client).then([] (auto&& maybeServer) {
            // maybeServer have type kj::Maybe<MyHandle::Server&>, which is really a wrapper of MyHandle::Server*, that we can downcast to the implementation type
            KJ_IF_MAYBE(server_ptr, maybeServer) {
                return static_cast<MyHandleImpl1*>(server_ptr);
            } else {
                KJ_FAIL_ASSERT("Handle not found on server");
            }
        }).then([context] (auto serverImpl) mutable {
            uint64_t res = serverImpl->getId();
            context.getResults().setResult(res);
        });
    }
private:
    capnp::CapabilityServerSet<MyAPI::MyHandle> set_;
};
```
`usehandle()` will take take an `MyHandle` capability and do something with it if it's a server-side object. The example is quite simple, however, the last promise continuation (the one that takes `auto serverImpl`) can be something more complex (i.e., a function that takes `serverImpl` and return another `Promise<void>`, this works because `Promise<Promise<...>>` will be collapsed into `Promise<...>`). In this case, by the time `useHandle()` returns, it's local variable `client` will be gone, and the promise (i.e., code in the `then()` block) has not been executed yet. Is it possible under any circumstance that `serverImpl` will points to an address that has been freed (i.e., due to all clients are freed) when that block executes?

[getlocalserverdoc]: https://github.com/capnproto/capnproto/blob/5e9586b9d7a492fb4b5f87233b1b98542274d8be/c%2B%2B/src/capnp/capability.h#L714

**Comment by kentonv** [comment]
> Does it mean that we must keep at least one Client object when calling getLocalServer() and before the promise it returns resolved (or cancelled)?

Yes.

I think your example code here happens to work because the `Client` object is still held by the RPC's params, and those stay alive until the RPC completes or you explicitly call `context.releaseParams()`. In your example, if the RPC is canceled, then the `getLocalServer()` call is canceled, so again you are safe. However, I think it would be better to explicitly capture the `Client` into your `.then()` continuation lambda, to prove more directly that it's still valid. This would be necessary if you wanted to keep the unwrapped server reference beyond the completion of the RPC, or if you wanted to use `context.releaseParams()` to free memory earlier.
