### ISSUE TITLE
Logging to stderr causes issues in code that monitors stderr for at least one warning log message

### ISSUE THREAD

**Issue by kentdlee** [capnproto/capnproto#1976]
Typically this is not a problem, but specifically for a log message in the kj library there is a log message that was generated when running inside a docker container or in some CICD pipelines. In the source file filesystem-disk-unix.c++ the log message 

KJ_LOG(WARNING, "PWD environment variable doesn't match current directory", pwd);

is the culprit. It was suggested that changing the level of that log message to INFO would be acceptable and would alleviate the problem since INFO level messages are not logged by default.

**Comment by kentdlee** [comment]
I will make the change for this issue and put up a PR.

**Comment by fhanau** [comment]
#1977 has been merged to master and also to v2 by now – closing this.
