### ISSUE TITLE
Simple manual on how to send image

### ISSUE THREAD

**Issue by ericjansen** [capnproto/capnproto#1988]
Hi @kentonv

I am new to capnproto and trying to find a good resources to learn deeper in Capnproto.
I find it struggling to understand the basic concepts. Could you tell me the logic to send image using Capnproto RPC in C++.
Thanks,
Eric

**Comment by kentonv** [comment]
You would probably send the image packed into a `Data` field, encoded in some other image encoding format (jpeg, png, etc.). Cap'n Proto doesn't actually have a lot to offer here.

Sorry, but I don't have bandwidth to write an example. There are a bunch of examples in the docs already, if there's something that doesn't make sense there feel free to ask a specific question about it.
