### ISSUE TITLE
Wait for multiple promises

### ISSUE THREAD

**Issue by lewisxy** [capnproto/capnproto#2019]
I would like to build a data structure that allows users to add promise into it, and obtain a promise that resolves whenever any promise added resolves (or throw exception), it also need to provide a method to tell the number of promises inside.

This is kinda similar to `TaskSet`, except that method produces a promise that wait until any promise added finishes.

It seems impossible to implement without breaking the abstraction that `kj` provides (I.e., uses internal stuff such as `PromiseNode`), which I prefer not to touch if possible.

Any help is appreciated.

**Comment by kentonv** [comment]
There are several ways you could implement this. A couple possibilities:

* `promise1.exclusiveJoin(promise2)` returns a promise that resolves when either of the input promises resolves. However, the other promise is then canceled -- this may or may not be what you want.
* Use `kj::newPromiseAndFulfiller<void>()` to create a new promise-fulfiller pair. For each promise the user adds, do:

      tasks.add(promise.then(
            [this]() {fulfiller->fulfill();},
            [this](kj::Exception&& e) {fulfiller->reject(kj::cp(e)); kj::throwFatalException(kj::mv(e));}));

    Then wait on the promise side of the pair -- it will resolve when the first promise in the set resolves. In this case, the other promises are not canceled since they're still in the TaskSet.

**Comment by lewisxy** [comment]
I thought about `exclusiveJoin`, but I don't want other promises added to be cancelled.

For the second approach you mentioned, while it does return a promise that resolves when any promise resolves. I want to be able to keep requesting such promise. In other words, once the caller handles the promise that completed, it will be able to grab another promise that resolves when any of the remaining promises (and the caller can add new promises inside as well) inside resolves.

**Comment by kentonv** [comment]
When the caller asks for a new promise, create a new promise-fulfiller pair, and replace the existing fulfiller with the new one. Now, the next time a promise resolves, it will call `fulfill()` on the new fulfiller.

**Comment by lewisxy** [comment]
Oh, I see your point. I think I get it. I will experiment with this approach and see if it solves my problem. Thank you
