### ISSUE TITLE
Is packing a canonical message considered okay

### ISSUE THREAD

**Issue by 5225225** [capnproto/capnproto#2052]
I'm considering using capnp for a VCS, and for that I need determinism (such that if 2 different people both make an object with the same content, they get deduplicated since their bytes are the same), so it looks like I'd use the canonical encoding, but I'm not sure about the line that says canonical messages are not packed.

Does this mean "we don't consider a packed encoding to be the canonical form of the message (but the packing form won't *change*)?", or "the packing method can change in the future, so anything relying on a packed message being consistent across versions of capnp may break". For my use case, I can't do the suggested solution of unpacking before hashing, since I'm also encrypting the messages, and want the hash to be based on the encrypted data.

I don't *require* packing, I just want something that can help compress the message, so alternatively I could just treat the packing step as a general purpose compression format (or just run a compression format without packing).

(I'm going to be using the rust capnp implementation, but I assumed this repo is the correct place for more general format questions)

**Comment by kentonv** [comment]
I think that in practice it'll work, but this isn't a property that the packing algorithm is intended to provide. It's possible to imagine tweaks to the packing algorithm that could result in slightly different bytes being produced, but which might improve compression ratio or performance. Do I think anyone will ever actually implement such optimizations? Not really. But I'm not sure I'd want to rule it out.

Could you maybe store both a hash of the original message, and the packed/encrypted content, using only the hash as the key?

**Comment by 5225225** [comment]
> Could you maybe store both a hash of the original message, and the packed/encrypted content, using only the hash as the key?

I *could*, other things do that, and it's definitely the more flexible option when it comes to changing the parameters without reuploading all the data, but my concern is that it's more prone to accidental/intentional corruption.

If you have the message hash be based on the original message, then a client can upload a message whose transformed content *doesn't* correspond to the original message, and the server has no way of *checking* that (without access to the key, which you probably don't want it to have).

But the failure case if you have the hash be based on the final output is "the user uploads a commit with junk data, but the hash is different from what it should be (so if the user uploaded the same original content again with a correct impl, they'll upload a correct commit, and all is well)" (at the cost of needing to reupload basically a whole new commit if you want to change the compression algorithm, which is a bit of a shame)

(there's also a concern about reading what content the user has uploaded by having hashes of known content, but that's fixable by using a keyed hash)

---

Anyways, that's all unrelated to the actual question, which was answered. I'll consider either copy pasting a packing implementation and treating it like a compression format, or just going without packing and seeing if a pre-existing compression algorithm works well enough at unpacked data.
