### ISSUE TITLE
DynamicStructBuilder::set hits KJ_UNREACHABLE when assigning a group

### ISSUE THREAD

**Issue by alexrobomind** [capnproto/capnproto#2067]
https://github.com/capnproto/capnproto/blob/5faf3144b5e1b0fbbe80992f7e3a890a472c82a3/c%2B%2B/src/capnp/dynamic.c%2B%2B#L663

I guess this case block should be terminated by a return after this line?

**Comment by kentonv** [comment]
Indeed, and I guess this means we don't have any unit test coverage for this, so it may be broken in other ways too... :/

**Comment by fhanau** [comment]
Closing this – https://github.com/capnproto/capnproto/pull/2094 has been merged to the master and v2 branches.
