### ISSUE TITLE
failed: expected boundsCheck(segment, ptr, wordCount)

### ISSUE THREAD

**Issue by Chenmo128** [capnproto/capnproto#2074]
I'm getting a runtime error:
`terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  capnp/layout.c++:2390: failed: expected boundsCheck(segment, ptr, wordCount); Message contains out-of-bounds list pointer. This usually indicates that the input data was corrupted, used a different encoding than specified (e.g. packed vs. non-packed), or was not a Cap'n Proto message to begin with. Note that this error is NOT due to a schema mismatch; the input is invalid regardless of schema.
stack: ffffb00a6e3b aaaac0b335cb aaaac0b33b07 aaaac0b82bb3 aaaac0b6948b aaaac0b69aaf aaaac0b6a493 aaaac0b47f57 aaaac0b48e2b aaaac0b49107 aaaac0b31927 ffffafc3411f aaaac0b327d3`

I printed the size of the List and accessed it without exceeding the size. i don't understand why i get this error.
Additionally, I can correctly access the submeesage Sub1

My code is as follows：

```
void Update_midsize(MyMessage::Builder& message) {
    auto sub1 = message.initSub1();
    sub1.setSubString("test_sub");
    sub1.setSubInt(100);
    sub1.setSubFloat(100.0f);

    auto repeatedStringField = message.initRepeatedStringField(60);
    auto repeatedIntField = message.initRepeatedIntField(60);
    auto repeatedFloatField = message.initRepeatedFloatField(60);
    for(int i = 0; i < 60; i++){
        repeatedStringField.set(i, "test");
        repeatedIntField.set(i, 1);
        repeatedFloatField.set(i, 1.5f);
    }
}

// Serialization function
kj::Array<capnp::word> capnp_serialize(capnp::MallocMessageBuilder& message) {
     kj::Array<capnp::word> serializedData = capnp::messageToFlatArray(message);
     return serializedData;
}

// Deserialization function
MyMessage::Reader capnp_deserialize(kj::Array<capnp::word>& serialized_data) {
    capnp::FlatArrayMessageReader reader(serialized_data);
    return reader.getRoot<MyMessage>();
}

void capnp_access(MyMessage::Reader& msg) {
    auto field1 = msg.getIntField1();
    auto field2 = msg.getFloatField1();
    auto field3 = msg.getSub1().getSubString();

    std::cout << "string.size: " << msg.getRepeatedStringField().size() << std::endl;
    std::cout << "int.size: " << msg.getRepeatedIntField().size() << std::endl;

      for (int i = 0; i < msg.getRepeatedStringField().size(); ++i) {
        auto field4 = msg.getRepeatedStringField()[i];
        benchmark::DoNotOptimize(field4);
        std::cout << "field4: " << field4.cStr() << std::endl;
    }
}

static void funcname(benchmark::State& state) {
    capnp::MallocMessageBuilder message; 
    MyMessage::Builder MyMsg = message.initRoot<MyMessage>(); 
    Update_midsize(MyMsg);
    auto serialized_data = capnp_serialize(message);
    auto deserialized_msg = capnp_deserialize(serialized_data);
    for (auto _ : state) {
        capnp_access(deserialized_msg);
    }
}
```

**Comment by kentonv** [comment]
Your bug is here:

```
MyMessage::Reader capnp_deserialize(kj::Array<capnp::word>& serialized_data) {
    capnp::FlatArrayMessageReader reader(serialized_data);
    return reader.getRoot<MyMessage>();
}
```

`reader.getRoot<T>()` returns a `MyMessage::Reader` which is like a pointer. It points into the message owned by `FlatArrayMessageReader`. But when you return from this function, the `FlatArrayMessageReader` is destroyed. Therefore you are returning a dangling pointer. When you try to access the dangling pointer, you are accessing memory that has been freed and probably overwritten by other things, so you get errors as if the message is corrupt.
