### ISSUE TITLE
Build a portable capnp binary that links against static libraries

### ISSUE THREAD

**Issue by JanosGit** [capnproto/capnproto#2120]
I'm testing out capnproto for the first time since it seems like a nice fit for a project.

One requirement that our build system has regarding integration of third party dependencies it that we create pre built libraries and binaries and deploy them via conan. I'm currently looking for ways to build the capnp binary in a way that it links against static libraries and not dynamic libraries.

I did a first attempt on macOS where I built it according to the documentation with one difference that was installing it like
```
make DESTDIR=/some/custom/directory install
```

Attempting to run the generated binary results in
```   
dyld[73769]: Library not loaded: /usr/local/lib/libcapnpc-2.0-dev.dylib
  Referenced from: <D90E78BE-E37A-32BC-8F7C-BE11D720B777> /some/custom/directory/usr/local/bin/capnp
  Reason: tried: '/usr/local/lib/libcapnpc-2.0-dev.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libcapnpc-2.0-dev.dylib' (no such file), '/usr/local/lib/libcapnpc-2.0-dev.dylib' (no such file)
zsh: abort      ./capnp id
```

I don't want to install the dynamic libraries on each build machine first, I'd prefer a fully portable capnp build. Can this be accomplished somehow? Furthermore, I also don't want to integrate the dynamic libraries in the product at all, so I'd be fine with a static library only build.

As a sidenote, I'm not really familiar with autotools and make since I use CMake for all C++ builds, so there might be some simple obvious build option that I'm overlooking here.

**Comment by JanosGit** [comment]
Thank you for your quick reply.

Generally, macOS looks for dynamic libraries in some known locations but there are ways to modify a binary so that it looks for dynamic libraries in other places. However this is not the main point here. When building the binary with usual configurations, I can inspect the dynamic library dependencies of it like that

```
otool -L /usr/local/bin/capnp
/usr/local/bin/capnp:
	/usr/local/lib/libcapnpc-1.0.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libcapnp-json-1.0.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libcapnp-1.0.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libkj-1.0.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1600.157.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)

```

This shows that the `capnp` binary dynamically links against the two system libraries `libc++` and `libSystem` along with the project specific libraries `libcapnpc-1.0.2.dylib`, `libcapnp-json-1.0.2.dylib`, `libcapnp-1.0.2.dylib` and `libkj-1.0.2.dylib`. This also means that if I copied the binary to another mac without copying the dynamic libraries, it would obviously fail to run because of the missing project specific libraries.

However, the static library variants of `libcapnpc`, `libcapnp-json`, `libcapnp` and `libkj` are built along with the dynamic libraries, I can find them in `/usr/local/lib`. What I'm looking for is some build flag that makes the linker use the static libraries instead of the dynamic ones, which should end up in a portable binary that has only dependencies to system libraries.

Do you know of any such build flag? This should probably not be something macOS specific, in fact I'd need the same for Windows builds as well. Given that the project contains CMakeLists, is building it with CMake also officially supported? I'd probably find my way around things a bit faster with CMake ;)

And theanks for the heads-up regarding the 1.x release, I'm currently using the 1.0.2 release tarball.

**Comment by kentonv** [comment]
If you use `./configure --disable-shared`, it won't build dynamic libs at all, and the capnp tool will statically link against the capnp libs. I am not sure if there's a way to make the dynamic libs still be built, while linking the binaries statically, other than to do two separate builds in the two configurations.

The cmake build should generally work but it is not the "official" build. I personally don't know cmake so I can't say for sure if the camke build that has been contributed is the same as the autotools build.

**Comment by JanosGit** [comment]
Great, that works!

As an addition, in order to build arm/x86_64 universal binary versions of the binaries and library with a proper macOS deployment target – which is most of the time what you want nowadays – I added the following flags as CFLAGS and CXXFLAGS"
`-arch arm64 -arch x86_64 -mmacosx-version-min=10.12`
Might be helpful for people that come here and find this issue. Maybe also wort noting that in the installation instructions?

**Comment by kentonv** [comment]
If there is a good site out there that aggregates best practices for autotools builds on every platform, I'd be happy to link to it. But I don't think Cap'n Proto's own docs are the best place to start giving OS-specific tips that could just as easily apply to every autotools-based project. That kind of thing could blow up quickly, especially when talking about Windows...
