### ISSUE TITLE
Exception thrown in MallocMessageBuilder::allocateSegment

### ISSUE THREAD

**Issue by JanosGit** [capnproto/capnproto#2170]
We use capnproto messages to store analysis results of user input files. Depending on the input file size, the size of the generated message varies. We use a `MallocMessageBuilder` and supply a custom memory block as `firstSegment` to its constructor. We estimate the required size of that memory block according to a quick analysis of the input file and in case of bigger input files, this will actually be a memory mapped file temp with write access to avoid eating up too much RAM.

Now if the input file is extremely large, thus the size of the `firstSegment` is also quite large, we run into a capnp assertion when calling `MessageBuilder::initRoot` which originates from `MallocMessageBuilder::allocateSegment` https://github.com/capnproto/capnproto/blob/377d991aae4523a00240613fea86fb42015e9187/c%2B%2B/src/capnp/message.c%2B%2B#L248 

Looking at the code it is caused by the condition `bounded(nextSize) * WORDS <= MAX_SEGMENT_WORDS` – however I wasn't able to find any documentation on this constant. Could you elaborate a bit on this limit and what would be suitable workarounds here?

**Comment by kentonv** [comment]
A single capnp segment is limited to 2^29 - 1 words (or 2^32 bytes, minus one word). This is an inherent limitation in how pointers are encoded -- intra-segment offsets are encoded as a 30-bit signed integer. A message can have 2^32 segments, thus can reach up to ~2^64 bytes in size, but not in a single segment.

You'll have to cap your first segment allocation at 2^29-1.

**Comment by JanosGit** [comment]
Thanks for explaining the background of that limitation, now that makes a bit more sense to me.

> You'll have to cap your first segment allocation at 2^29-1.

This was our intermediate solution as well, however that means that everything beyond the first segment will be allocated using plain `malloc` calls for the further segments. If we preferred to use our own segment allocation strategy, we probably have to use our own message builder implementation based on the `capnp::MessageBuilder` base class, right?

**Comment by kentonv** [comment]
Yes, you can fully control allocation of all segments by subclassing `capnp::MessageBuilder`.
