### ISSUE TITLE
Canonical/Deterministic serialization

### ISSUE THREAD

**Issue by Pique7** [capnproto/capnproto#2171]
Hello! I know this issue is already discussed on the Cap'n'Proto webpage but I ask anyway:

Is it possible to perform deterministic/canocial serialization with Cap'n'Proto, by any means? 
In other words: _Same input always leads to same output (byte sequence)._

Actually I wanted to use Google Protocol Buffers, but as far as I can ascertain, unfortunately Protobufs are not suitable for this.

**Comment by kentonv** [comment]
Yes, this is covered here: https://capnproto.org/encoding.html#canonicalization
