### ISSUE TITLE
capnp.exe throws an exception on VeraCrypt partitions

### ISSUE THREAD

**Issue by Rasmus-123** [capnproto/capnproto#2176]
This error occurs on VeraCrypt encrypted partitions.  
There are no issues on unencrypted partitions or partitions using Bitlocker and afaik also not on partitions using TrueCrypt.

This Issue was already reported in the VeraCrypt repository in 2021: https://github.com/veracrypt/VeraCrypt/issues/764  
But has regrettably received no responses.

```powershell
G:\ > capnp compile -oc++ .\schema.capnp
*** Received structured exception #0xe06d7363: (unknown exception code); stack: 7ffc655eb698 7ffc51d35266 7ff7284a3251 7ff72848eb3a 7ff7284b110e 7ff7284a9ce6 7ff7284ad585 7ff7283d8237 7ff7284bedcb 7ffc66337373 7ffc678dcc90
```

or on another system

```powershell
PS E:\path\proto> capnp.exe compile -oc++ .\schema.capnp
*** Uncaught exception ***
kj\filesystem-disk-win32.c++:384: failed: GetFileInformationByHandleEx(FileCompressionInfo): #87 The parameter is incorrect.
stack: 7ff7e809eb3a 7ff7e80beeef 7ff7e80bed91 7ff7e7fd37fa 7ff7e7fd3a11 7ff7e7fdb467 7ff7e7fd95e1
```

The exception is thrown by the error handling to a call of `GetFileInformationByHandleEx` in the function `FsNode::Metadata stat()` in `filesystem-disk-win32.c:378` ([Link to line](https://github.com/capnproto/capnproto/blob/377d991aae4523a00240613fea86fb42015e9187/c%2B%2B/src/kj/filesystem-disk-win32.c%2B%2B#L378)).

Excerpt:
```c++
FsNode::Metadata stat() const {
    BY_HANDLE_FILE_INFORMATION stats;
    KJ_WIN32(GetFileInformationByHandle(handle, &stats));
    auto metadata = statToMetadata(stats);

    // Get space usage, e.g. for sparse files. Apparently the correct way to do this is to query
    // "compression".
    FILE_COMPRESSION_INFO compInfo;
    KJ_WIN32_HANDLE_ERRORS(GetFileInformationByHandleEx(
        handle, FileCompressionInfo, &compInfo, sizeof(compInfo))) {
      case ERROR_CALL_NOT_IMPLEMENTED:
        // Probably WINE.
        break;
      default:
        KJ_FAIL_WIN32("GetFileInformationByHandleEx(FileCompressionInfo)", error) { break; }
        break;
    } else {
      metadata.spaceUsed = compInfo.CompressedFileSize.QuadPart;
    }

    return metadata;
  }
```

Could there be an easy workaround fix similar to WINE?
Or a fallback way to determine size?

VeraCrypt version: 1.26.15 (64-bit) - latest
Capn' Proto Version: 1.0.2 - latest, installed using vcpkg

**Comment by kentonv** [comment]
Yes, we could add a `case` for the error code you're seeing, and skip populating `spaceUsed`, like we do under WINE. I'm happy to accept a PR that does this, but it'd be best if someone who uses VeraCrypt could create the PR and test it.

**Comment by Rasmus-123** [comment]
I've just created two pull requests for master-v1 and v2.  

I've tested capnp.exe with `capnp compile -oc++ <schema>` on both systems where it previously failed and with this change it now works fine with both v1 and v2.
