### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by carlocorradini** [capnproto/capnproto#2185]
First and foremost, thank you for this amazing product 🙌
I was wondering if `Cap'n Proto` has an official __logo__?
Thanks 🥳

**Comment by kentonv** [comment]
Yes, the logo is the thing at the top of the web page, and is also the org's avatar on github, that is:

![](https://avatars.githubusercontent.com/u/29186932)

**Comment by carlocorradini** [comment]
@kentonv Thank you for responding so quickly.
Sorry for bothering, but is there also an `SVG` version?
I want to have the logo for all `.capnp` files in `VSCode` via [vscode-icons](https://github.com/vscode-icons/vscode-icons) (I'll submit a PR), so an `SVG` version would be awesome.
Thank you again for your work and support 🥳

**Comment by kentonv** [comment]
Hmm, I don't think I have an SVG. @sailorhg made the logo way back in PR #1 and then send me an updated version which I committed in afe41c0... both were PNGs. I think that's all I have.

**Comment by MatthewS8** [comment]
Hello guys, I attempted to generate the SVG logo from the original PNG.
It contains some small artifacts/defects, but it is more than acceptable.

I've also created a PR in `vscode-icons`: https://github.com/vscode-icons/vscode-icons/pull/3625

![capnp](https://github.com/user-attachments/assets/38183dc9-4256-4b82-bd8c-502afb965c21)

**Comment by carlocorradini** [comment]
@sailorhg Can you help us? Thanks 🙏
