### ISSUE TITLE
"Capnproto" package install issue

### ISSUE THREAD

**Issue by raptee-suraj** [capnproto/capnproto#2204]
I have used the same source and same source revision id in my recipe. But the library files are not getting packaged and the package is not getting installed (libcpnp.so). In the meta-oe layer, capnproto compiler is mentioned in the capnproto recipe but I need to install only the shared object file of capnproto, I have shared my recipe.

`SUMMARY = "Cap'n Proto serialization/RPC system"
DESCRIPTION = "Cap’n Proto is an insanely fast data interchange format and capability-based RPC system. "
HOMEPAGE = "https://github.com/sandstorm-io/capnproto"
SECTION = "console/tools"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://../LICENSE;md5=a05663ae6cca874123bf667a60dca8c9"

SRC_URI = "git://github.com/sandstorm-io/capnproto.git;branch=release-${PV};protocol=https"
SRCREV = "1a0e12c0a3ba1f0dbbad45ddfef555166e0a14fc"

PV = "1.0.2"
S = "${WORKDIR}/git/c++"

inherit cmake

DEPENDS = "cmake-native ninja-native"

CVE_PRODUCT = "capnproto capnp"

EXTRA_OECMAKE += "\
    -DBUILD_TESTING=OFF \
"

FILES:${PN}-compiler = "${bindir}"

PACKAGE_BEFORE_PN = "${PN}-compiler"
RDEPENDS:${PN}-dev += "${PN}-compiler"

BBCLASSEXTEND = "native nativesdk"`

Where need to make changes, Please help me out to install package into AGL Linux-OS.

**Comment by kentonv** [comment]
Sorry but I have no idea what this means. I don't even know which package manager you're talking about. But the Cap'n Proto project itself doesn't maintain any packages for any package manager in any case. You will have to find whoever maintains this package and talk to them.
