### ISSUE TITLE
void TaskSet::wait(WaitScope& waitScope)

### ISSUE THREAD

**Issue by szenker** [capnproto/capnproto#286]
Wouldn't it be useful to have TaskSet::wait(WaitScope& waitScope) available which blocks until all queued promises are fulfilled (or rejected)?

**Comment by dwrensha** [comment]
Is `kj::joinPromises()` sufficient for what you're trying to accomplish?

**Comment by szenker** [comment]
kj::joinPromises() doesnt work for my use case, because I cannot create all the promises in a row. Instead the promises get created by some kind of user interaction which occurs more or less randomly - e.g. a button click. What I want to ensure is, that the application processes all promises before it terminates. So my idea was to add them all to a TaskSet and call TaskSet::wait() at program exit.

Do you think it is straight forward to implement TaskSet::wait()?

**Comment by kentonv** [comment]
@szenker Another solution would be: in place of your TaskSet, keep a single kj::Promise<void>. Each time you would normally add a task to the TaskSet, instead join it with the existing promise. So, like:

    kj::Promise<void> tasks = kj::READY_NOW;

    // ... later ...

    kj::Promise<void> newTask = doSomething();
    tasks = kj::joinPromises({kj::mv(tasks), kj::mv(newTask)});

I suppose it would also be possible to modify `TaskSet` (specifically I'd add an `allDone()` call which returns a `kj::Promise<void>`; you could then call `wait()` on that if you actually want to block). But the above works with no changes to the library.

**Comment by szenker** [comment]
When using your suggested approach (without the need to change the library):

kj::Promise<void> newTask = doSomething();
tasks = kj::joinPromises({kj::mv(tasks), kj::mv(newTask)});

Would that cause a "memleak". I mean, I will call tasks.wait() at program exit and therefore, the list of all tasks will grow and grow during runtime without cleanup?

**Comment by kentonv** [comment]
Oh I see, I was thinking your program flow was:

1. Add things to TaskSet.
2. TaskSet::wait().

But now I see you have a long-running app, and what you're saying is that when the user chooses to exit, you want to wait on whatever is left over.

My approach could be leaky. It will only leak in the case that some old, long task is still waiting and lots of new tasks have come and gone in the meantime -- in this case a chain to the old task will stick around. Once the old task finishes then the chain is cleaned up.

I agree this is not ideal. I guess TaskSet::allDone() makes sense.

**Comment by dwrensha** [comment]
Another possibility: instead of `taskSet.add(p)`, do `taskSet.add(p.attach(handle))`, where `handle` is some object that decrements a refcount when destructed, and when the refcount hits zero fulfills the promise that your toplevel will wait on.

**Comment by kentonv** [comment]
BTW, please note that I'm unlikely to have time to work on this soon, but I'm happy to accept pull requests.
