### ISSUE TITLE
capnp generates files outside the output directory

### ISSUE THREAD

**Issue by mikezackles** [capnproto/capnproto#288]
Something like `capnp --output=c++:gen/src ../../../src/baz.capnp` will put the generated files in `../src`.

This can be worked around using `--src-prefix` as in #193, but it's very confusing. It might also be nice if `capnp help compile` were a bit clearer about this behavior.

**Comment by kentonv** [comment]
Copying my comment from the other thread:

> I agree that capnp should not allow output files to land outside of the specified output directory. We should canonicalize the output path and error out if it starts with "..".
