### ISSUE TITLE
Reading an unaligned message triggers a KJ_DASSERT() failure, but only sometimes.

### ISSUE THREAD

**Issue by dwrensha** [capnproto/capnproto#313]
Currently, if you try to read an unaligned message (on an architecture that allows such reads), you can hit [this error](https://github.com/sandstorm-io/capnproto/blob/f6a31613efce413795a200ccc194c2c05d463da2/c%2B%2B/src/capnp/layout.c%2B%2B#L2731-L2733) if your code was compiled in debug mode. The error is not triggered on all messages, so tracing down its cause can be confusing. See for example the mailing list discussion [here](https://groups.google.com/forum/#!topic/capnproto/RPqMlhkSdeo).

It would be better if capnproto had a more uniform policy on alignment errors. We should either:
1. Always throw a `KJ_DASSERT()` failure on unaligned reads, with a more helpful error message explaining the need for alignment. 
2. Never throw an exception due to an unaligned read. Justification: the programmer, by explicitly casting the data to `capnp::word*`, has taken responsibility for any dangers that lurk.

**Comment by kentonv** [comment]
Problem with (2) is that we've had a few conversations with people where they seemed unaware that there was any problem with such a cast.

Maybe what we want is a very upfront check (e.g. in FlatArrayMessageReader's constructor), but with the ability to call a special version of the method that acknowledges that the caller doesn't care about alignment (for people who are on x86 and would rather have unaligned reads than do a copy).

**Comment by DemiMarie** [comment]
@kentonv Unfortunately at least LLVM considers unaligned reads to be undefined behavior.  Though I wonder if there is any realistic way this could cause a problem.
