### ISSUE TITLE
Promise<Promise<T>> to Promise<T> autojoin does not work for RemotePromises.

### ISSUE THREAD

**Issue by dwrensha** [capnproto/capnproto#341]
As per [this documentation](https://github.com/sandstorm-io/capnproto/blob/0fb92820af3c9f31117081b3c08e01066e07ed55/c%2B%2B/src/kj/async.h#L146-L148), I expect the following program to print "in foo()" when it is run:

``` capnp
# test-wait.capnp
@0xdc4d9ce7f7ca0267;

interface Foo {
  foo @0 () -> ();
}
```

``` cpp
// test_wait.c++

#include "capnp/capability.h"
#include "test-wait.capnp.h"
#include <iostream>
#include <kj/async.h>

class FooImpl: public Foo::Server {
  kj::Promise<void> foo(FooContext context) override {
    std::cout << "in foo()\n";
    return kj::READY_NOW;
  }
};

int main() {
  kj::EventLoop loop;
  kj::WaitScope waitScope(loop);
  Foo::Client client(kj::heap<FooImpl>());

  kj::evalLater([&]() {
    return client.fooRequest().send();
  }).wait(waitScope);
}
```

However, the program does not actually print anything, because `foo()` never gets called. To get it to work, we need to wait again!

``` cpp
  kj::evalLater([&]() {
    return client.fooRequest().send();
  }).wait(waitScope).wait(waitScope);
```

**Comment by dwrensha** [comment]
Maybe we could define an `KJ_WARN_UNUSED_VALUE` annotation and apply it to `RemotePromise`. Then the compiler could at least provide a hint to the programmer when this problem arises.

**Comment by kentonv** [comment]
Does GCC and/or Clang implement an appropriate type attribute for KJ_WARN_UNUSED_VALUE to be based on? I haven't been able to find anything.

**Comment by kentonv** [comment]
It occurs to me that, arguably, `Promise<RemotePromise<T>>` should reduce to `RemotePromise<T>`, *not* `Promise<Response<T>>`. That way, you can pipeline on it...
