### ISSUE TITLE
Doesn't work under Windows Subsystem for Linux

### ISSUE THREAD

**Issue by realuser** [capnproto/capnproto#458]
In Windows 10 64-bit I have enabled [Windows Subsystem for Linux (WSL)](https://msdn.microsoft.com/en-us/commandline/wsl/about), which gives me Bash on Ubuntu 14.04 LTS on Windows.

I'm following these steps:
```
curl -O https://capnproto.org/capnproto-c++-0.5.3.1.tar.gz
tar zxf capnproto-c++-0.5.3.1.tar.gz
cd capnproto-c++-0.5.3.1
./configure
make -j6 check
```
It appears to compile fine but then tests seem to fail.

FAIL: capnp-test
PASS: capnp-evolution-test
PASS: src/capnp/compiler/capnp-test.sh

[test-suite.log.txt](https://github.com/sandstorm-io/capnproto/files/954459/test-suite.log.txt)

looking at test-suite.log, it appears the following tests fail:

```
[----------] Global test environment tear-down
[==========] 407 tests from 45 test cases ran. (69 ms total)
[  PASSED  ] 373 tests.
[  FAILED  ] 34 tests, listed below:
[  FAILED  ] AsyncUnixTest.Signals
[  FAILED  ] AsyncUnixTest.SignalWithValue
[  FAILED  ] AsyncUnixTest.SignalWithPointerValue
[  FAILED  ] AsyncUnixTest.SignalsMultiListen
[  FAILED  ] AsyncUnixTest.SignalsMultiReceive
[  FAILED  ] AsyncUnixTest.SignalsAsync
[  FAILED  ] AsyncUnixTest.SignalsNoWait
[  FAILED  ] AsyncUnixTest.ReadObserver
[  FAILED  ] AsyncUnixTest.ReadObserverMultiListen
[  FAILED  ] AsyncUnixTest.ReadObserverMultiReceive
[  FAILED  ] AsyncUnixTest.ReadObserverAsync
[  FAILED  ] AsyncUnixTest.ReadObserverNoWait
[  FAILED  ] AsyncUnixTest.WriteObserver
[  FAILED  ] AsyncUnixTest.SteadyTimers
[  FAILED  ] AsyncUnixTest.Wake
[  FAILED  ] AsyncIo.SimpleNetwork
[  FAILED  ] AsyncIo.AddressParsing
[  FAILED  ] AsyncIo.OneWayPipe
[  FAILED  ] AsyncIo.TwoWayPipe
[  FAILED  ] AsyncIo.PipeThread
[  FAILED  ] AsyncIo.PipeThreadDisconnects
[  FAILED  ] AsyncIo.Timeouts
[  FAILED  ] SerializeAsyncTest.ParseAsync
[  FAILED  ] SerializeAsyncTest.ParseAsyncOddSegmentCount
[  FAILED  ] SerializeAsyncTest.ParseAsyncEvenSegmentCount
[  FAILED  ] SerializeAsyncTest.WriteAsync
[  FAILED  ] SerializeAsyncTest.WriteAsyncOddSegmentCount
[  FAILED  ] SerializeAsyncTest.WriteAsyncEvenSegmentCount
[  FAILED  ] TwoPartyNetwork.Basic
[  FAILED  ] TwoPartyNetwork.Pipelining
[  FAILED  ] TwoPartyNetwork.Release
[  FAILED  ] TwoPartyNetwork.Abort
[  FAILED  ] EzRpc.Basic
[  FAILED  ] EzRpc.DeprecatedNames

34 FAILED TESTS
FAIL capnp-test (exit status: 1)
```

Should this work in this environment?

**Comment by kentonv** [comment]
It appears that WSL does not implement the `signalfd()` syscall, which is required by the KJ event loop used for Cap'n Proto RPC. If you don't use RPC (specifically, you don't use libkj-async nor libcapnp-rpc), you can probably ignore these errors and carry on.

It's possible to force KJ to use a slower `poll()`-based event loop using `-DKJ_USE_EPOLL=0`, which will avoid using `signalfd()`:

    ./configure CXXFLAGS=-DKJ_USE_EPOLL=0

But when I tried this instead, various tests hung. I don't have time to dig into this, unfortunately.

(Note also that `-DKJ_USE_EPOLL=0` changes the ABI of the library. That means that all apps using Cap'n Proto must also be compiled with this flag, which may be challenging.)

**Comment by RReverser** [comment]
OK so after fixes in:
 - https://github.com/capnproto/capnproto/pull/773
 - https://github.com/capnproto/capnproto/pull/775
 - https://github.com/capnproto/capnproto/pull/776

there is no more hanging tests but bunch of failing one, for various reasons.

List for tracking purposes:
- [ ] 1
  ```
  [ TEST ] async-io-test.c++:337: legacy test: AsyncIo/Udp
  kj/async-io-test.c++:484: failed: expected ancillary.isTruncated
  ```

- [ ] 2
  ```
  [ TEST ] async-unix-test.c++:426: legacy test: AsyncUnixTest/WriteObserver
  kj/async-unix-test.c++:454: failed: expected !(writable)
  ```

- [ ] 3
  ```
  [ TEST ] filesystem-disk-test.c++:274: DiskFile
  kj/filesystem-disk-unix.c++:441: failed: ftruncate(fd, size): Invalid argument
  ```

- [ ] 4
  ```
  [ TEST ] filesystem-disk-test.c++:527: DiskDirectory symlinks
  kj/filesystem-disk-test.c++:573: failed: expected !dir->exists(Path("foo"))
  ```

- [ ] 5
  ```
  [ TEST ] filesystem-disk-test.c++:833: DiskFile holes
  kj/filesystem-disk-test.c++:864: failed: expected meta.spaceUsed <= 2 * 65536
  kj/filesystem-disk-test.c++:887: failed: expected file->stat().spaceUsed == meta.spaceUsed
  kj/filesystem-disk-test.c++:895: failed: expected copy->stat().spaceUsed == meta.spaceUsed
  kj/filesystem-disk-test.c++:920: failed: expected file->stat().spaceUsed < meta.spaceUsed
  ```

**Comment by GitMensch** [comment]
Much if not all of those should be fixed with WSL2.

**Comment by kentonv** [comment]
Yes, this issue is probably obsolete since WSL2 uses a real Linux kernel.
