### ISSUE TITLE
What does the " KJ_IREQUIRE(!isWaiting());" exception mean?

### ISSUE THREAD

**Issue by nneesshh** [capnproto/capnproto#486]
file: async-inl.h
line: 760
 void get(ExceptionOrValue& output) noexcept override {
    KJ_IREQUIRE(!isWaiting());
    output.as<T>() = kj::mv(result);
  }

sometimes I got the exception at line "KJ_IREQUIRE(!isWaiting());", 
whats' wrong does this exception mean?
and whats' wrong usage would trigger this exception?

Any help is appreciate!

**Comment by kentonv** [comment]
Hmm, that's deep in the implementation of Cap'n Proto's async I/O framework. In theory it "should never happen".

Could you provide a full stack trace and/or some example code that triggers this, for me to debug?

**Comment by nneesshh** [comment]
hi, kentonv, sorry about that I can't provide any reprouduce code, because it is just triggerred on my project startup once. WHEN I relaunched my project, it disappeared. SO I think maybe some exception on project startup causes initializing order changed, but I don't know what triggerred this.

**Comment by kentonv** [comment]
OK, I'm closing this for now, but let me know if you are able to reproduce.
