### ISSUE TITLE
0.6.0 test fails with seg fault on Debian 3.16

### ISSUE THREAD

**Issue by pianomanfrazier** [capnproto/capnproto#493]
I downloaded capnproto on the [install](https://capnproto.org/install.html) page and followed the directions.

`make -j6 check` failed with the following test-suite log.

[test-suite.txt](https://github.com/capnproto/capnproto/files/1059234/test-suite.txt)

**Comment by kentonv** [comment]
Hmm, this looks like the GCC bug I worked around with d624d56e6e752308819dddfbe839ebd3297f375b. I guess I should do a point release.

**Comment by kentonv** [comment]
try: http://capnproto.org/capnproto-c++-0.6.1-rc1.tar.gz

**Comment by pianomanfrazier** [comment]
Yes that version passes all tests. Thanks.

**Comment by kentonv** [comment]
Great, 0.6.1 has been released!
