### ISSUE TITLE
relativePath  and canonicalizePath not working well on Windows (msvc)

### ISSUE THREAD

**Issue by diorcety** [capnproto/capnproto#494]
In relativePath and canonicalizePath the used path seperator is "/" which is not working with windows "\" paths

I have as base: 
C:\\X\\lib\\site-packages\\xschemas\\camera.capnp
as add:
image.capnp
and output:
image.capnp

**Comment by diorcety** [comment]
Added to this these functions are duplicated

**Comment by kentonv** [comment]
We should switch over to the new KJ Filesystem API in 0.7, which should fix this as a side-effect.

**Comment by melak47** [comment]
Does this somehow affect import search paths, too?
For example, given
```
src
├── bar.capnp
└── foo.capnp

> cat src/foo.capnp
@0x86855fed67c81a9e;

> cat src/bar.capnp
@0xb8bebfb9acf548e7;

using Foo = import "foo.capnp";
```
`capnp compile -oc++ src/bar.capnp` works,
`capnp compile -oc++ src\bar.capnp` fails:
`src\bar.capnp:3:20-31: error: Import failed: foo.capnp`

**Comment by kentonv** [comment]
@melak47 Probably, yes. The code only treats '/' as a separator, not '\', so if you say "look for foo.capnp relative to bar/baz\qux.capnp", it's going to look for "bar/foo.capnp", not "bar/baz\foo.capnp".
