### ISSUE TITLE
Is anyone maintaining C# version of capnproto?

### ISSUE THREAD

**Issue by lcy03406** [capnproto/capnproto#499]
The link of ( C# by @mgravell ) in https://capnproto.org/otherlang.html is broken. I searched for capnproto-net and found some forks and donno which one is the 'official' now.

**Comment by hof** [comment]
See also: https://groups.google.com/forum/#!topic/capnproto/uGTiKEXAUy0

**Comment by kentonv** [comment]
Closing because this is not an actionable issue for the C++ repository, but feel free to continue discussion on the group thread mentioned above.
