### ISSUE TITLE
Failure to compile with uClibc (missing execinfo.h)

### ISSUE THREAD

**Issue by sonologic** [capnproto/capnproto#510]
uClibc lies about it's identity, and defines __GLIBC__ in features.h. However, uClibc does not implement execinfo.h, and thus compilation of capnproto fails.

I'm creating a pull request to add an explicit check for execinfo.h to configure.ac, and then use config.h in c++/src/kj/exception.c++ to see if we can have backtraces or not instead of checking for (__linux__ && __GLIBC__) || __APPLE__.

**Comment by kentonv** [comment]
Fixed by #511.

**Comment by aleksander** [comment]
For those who faced this bug with capnproto version without #511 merged in: there is another way, uClibc can be built with UCLIBC_HAS_BACKTRACE flag enabled (development/debugging options in uclibc-menuconfig) which enables support for execinfo.h. So there is no need to disable backtrace support for uClibc.
