### ISSUE TITLE
Header miniposix.h is installed by cmake but not installed by autoconf

### ISSUE THREAD

**Issue by katreniak** [capnproto/capnproto#515]
As I wrote code generator starting by copying `capnpc-c++.c++`, I happened to use `miniposix.h` file. Then I realized that the header file is installed by `cmake` but not by `autoconf`.

What are the long term plans with this file? It was changed to `noinst_HEADER` in https://github.com/capnproto/capnproto/pull/202. Can it be installed in `autoconf`? Can it be non installed in `cmake`?

**Comment by kentonv** [comment]
This header was not intended to be part of the public API, as it's kind of a hack. It looks like it's installed by the cmake build by mistake.

I would suggest copying the parts you need. Copying may sound ugly but these are really trivial definitions -- they are unlikely to change over time in a way that you would want to track. Keeping a private copy ensures that we can make changes to the header (e.g. eliminating it, if we come up with better abstractions) without breaking your code.

FWIW I think that capnpc-c++.c++ only depends on the header for the STDIN_FILENO and STDOUT_FILENO constants and the mkdir() wrapper.

**Comment by katreniak** [comment]
I already did copy the file locally, I will stick to it. Thanks!

 #516 fixes the cmake "mistake"
