### ISSUE TITLE
How to generate tests output in xml format

### ISSUE THREAD

**Issue by hemantabhagat** [capnproto/capnproto#519]
Hi,

I am able to ran all capnprotp tests successfully. I would like to generate the test output in xml format also. Is there any way to do that?

Thanks,
Hemant

**Comment by kentonv** [comment]
Sorry, there is no way to do that. What do you need it for?

**Comment by hemantabhagat** [comment]
We have a code analysis product and it has integration with gtest. But it works on gtest results in xml format.

**Comment by kentonv** [comment]
OK, but why are you trying to analyze Cap'n Proto's tests? I'm trying to understand the broader purpose here.

**Comment by hemantabhagat** [comment]
Basically I am working on a product which does static analyse of the code on cloud and local environment.
Along with static analysis we also show the unit test execution status and code coverage status on our UI (if the source code contains unit tests using gtest). Currently only gtest support is there as it is widely used.

For our internal testing purpose, I downloaded Cap’n Proto project as it has unit tests using GTest. But after building and running the tests we found we cannot generate the gtest output in xml format. Hence I asked for help.

Thanks,
Hemant

**Comment by kentonv** [comment]
Cap'n Proto 0.5.x and below used gtest but 0.6 no longer does. As of 0.6, Cap'n Proto uses its own small testing framework. It does not support XML output.

If you're just looking for sample gtest-based projects to throw at your tool, you can try Cap'n Proto 0.5.3.1.

https://capnproto.org/capnproto-c++-0.5.3.1.tar.gz

If I understand correctly, you don't have a specific need for Cap'n Proto's tests to produce XML going forward; you were just looking for samples to try your tool on. So, I'm closing this issue as I think there's no action needed. Let me know if I misunderstood.

**Comment by hemantabhagat** [comment]
Yes, that is what I need it for. Thank you very much for additional information. I will try out the mentioned version. And thank you again for your time and efforts.

Thanks,
Hemant

**Comment by hemantabhagat** [comment]
Hi,

Now I am able to get the xml output.

I am curious to know that why you changed the unit test framework from gtest. I am trying to understand the problems with gtest. Because I am also planning to add unit tests to my project.

Any insights from you will be helpful to me.

Thanks,
Hemant

**Comment by kentonv** [comment]
A lot of small reasons, including but not limited to:

* KJ (the C++ utility library bundled with Cap'n Proto) already had a powerful assertion framework that could replace most of the functionality of gtest on its own. All that was needed on top of that was a way to define tests and run them (not hard).
* Having a dependency on gtest led to a surprising number of logistical issues, such as:
    * gtest is hostile towards being system-installed. They intentionally disable shared library support, and they encourage users to bundle a specific version of gtest with their code. Cap'n Proto did exactly that, but distro package maintainers tend to hold different opinions. Some feel very strongly that bundling is wrong, and would insist that Cap'n Proto should work with the system-installed gtest, even though gtest doesn't want to be system-installed. While I understand gtest's arguments, I think that their insulation inside Google has led to a lack of understanding of how things are done in the open source ecosystem.
    * gtest's original project location on Google Code -- which we depended on -- disappeared when Google Code decided to surrender to Github. No redirects were provided, so a bunch of stuff broke, which was annoying.
    * gtest was Cap'n Proto's only external dependency. Having zero external dependencies is nice for a lot of reasons.
    * etc.
* gtest's style of C++ is different from KJ's style and this led to friction. For example:
    * gtest implements stringification by expecting types to implement `operator<<(std::ostream&, T&)`. KJ absolutely avoids the standard iostream classes because they are atrociously designed (being one of the oldest parts of the library) and instead uses a different stringification framework. Since gtest always wants parameters to its assertions to be stringifyable, lots of little shims had to be written.
    * gtest's style of test fixtures is not RAII.
    * gtest introduces lots of macros names with no vendor prefix, leading to collisions.
    * gtest's limited support for exceptions (which Google doesn't use internally) assumes an exception heirarchy, which goes against KJ's exception style.
    * etc.

**Comment by hemantabhagat** [comment]
Thanks you very much for all the valuable information.
This would definitely help us in decision making. I will also explore the KJ library.

Thanks,
Hemant
