### ISSUE TITLE
Codegen issue on little endian 64-bit MIPS (mips64el) in 0.6.1

### ISSUE THREAD

**Issue by thomaslee** [capnproto/capnproto#541]
Planning to dig into this more in qemu when I get a sec, but wanted to raise it here in the interim:

> The latest mips64el build of capnproto failed, as detailed at
> https://buildd.debian.org/status/fetch.php?pkg=capnproto&arch=mips64el&ver=0.6.1-1&stamp=1503916947&raw=0
> and (very briefly) excerpted below:
>
>  src/capnp/test.capnp.h:12247:29: error: 'Pipeline' in 'struct
>  capnp::AnyList' does not name a type
>     inline  ::capnp::AnyList::Pipeline getAnyListAsList();
>                               ^~~~~~~~

Originally reported via the Debian bug tracker https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873540

Big endian MIPS appears to be fine:

https://buildd.debian.org/status/package.php?p=capnproto&suite=unstable

Seems to manifest as a codegen issue -- perhaps something (endianness quirks?) tripping up hasDiscriminantValue() in capnpc-c++.c++. Possible we're assuming big endian MIPS somewhere critical that might explain this?

**Comment by kentonv** [comment]
This is really weird. The `AnyList` type has a kind of `FieldKind::LIST` (set on line 1312), which should make `shouldIncludePipelineGetter` be set false according to:

      bool shouldIncludePipelineGetter = !hasDiscriminantValue(proto) &&
          (kind == FieldKind::STRUCT || kind == FieldKind::BRAND_PARAMETER);

I can't imagine why this would hit mipsel specifically.

Does this affect all uses of `AnyList` as a field type, or only this specific case?

**Comment by thomaslee** [comment]
> Does this affect all uses of AnyList as a field type, or only this specific case?

Not 100% sure since I don't have ready access to a mips64el host, but from the logs we can see at least one other list type impacted by a similar issue -- albeit in the same source file:

```
src/capnp/test.capnp.h:12247:29: error: 'Pipeline' in 'struct capnp::AnyList' does not name a type
   inline  ::capnp::AnyList::Pipeline getAnyListAsList();
                             ^~~~~~~~
src/capnp/test.capnp.h:13689:73: error: 'Pipeline' in 'struct capnp::List<capnproto_test::capnp::test::TestInterface>' does not name a type
   inline  ::capnp::List< ::capnproto_test::capnp::test::TestInterface>::Pipeline getList();
```

I'm not seeing any complaints about TestAnyOthers.anyListField, which is also defined in test.capnp. However, I *am* seeing the compiler gripe about e.g. TestLists.list0 et al, though it's a different error:

```
In file included from ./src/capnp/layout.h:39:0,
                 from ./src/capnp/generated-header-support.h:32,
                 from src/capnp/test-import.capnp.h:7,
                 from src/capnp/test-import.capnp.c++:4:
./src/capnp/blob.h:47:9: note: candidate: constexpr capnp::Text::Pipeline::Pipeline()
   class Pipeline {};
         ^~~~~~~~
./src/capnp/blob.h:47:9: note:   candidate expects 0 arguments, 1 provided
./src/capnp/blob.h:47:9: note: candidate: constexpr capnp::Text::Pipeline::Pipeline(const capnp::Text::Pipeline&)
./src/capnp/blob.h:47:9: note:   no known conversion for argument 1 from 'capnp::AnyPointer::Pipeline' to 'const capnp::Text::Pipeline&'
./src/capnp/blob.h:47:9: note: candidate: constexpr capnp::Text::Pipeline::Pipeline(capnp::Text::Pipeline&&)
./src/capnp/blob.h:47:9: note:   no known conversion for argument 1 from 'capnp::AnyPointer::Pipeline' to 'capnp::Text::Pipeline&&'
In file included from src/capnp/test-import.capnp.h:16:0,
                 from src/capnp/test-import.capnp.c++:4:
src/capnp/test.capnp.h: In member function 'capnp::List<capnproto_test::capnp::test::TestLists::Struct0>::Pipeline capnproto_test::capnp::test::TestLists::Pipeline::getList0()':
src/capnp/test.capnp.h:25320:115: error: no matching function for call to 'capnp::List<capnproto_test::capnp::test::TestLists::Struct0>::Pipeline::Pipeline(capnp::AnyPointer::Pipeline)'
   return  ::capnp::List< ::capnproto_test::capnp::test::TestLists::Struct0>::Pipeline(_typeless.getPointerField(0));
```

Seems to imply we're not only generating the getter, but also generating the underlying Pipeline struct, right? (even if the generated code is messed up elsewhere)

Then elsewhere in the logs, we've got similar complaints about capnp::Text::Pipeline:

```
In file included from ./src/capnp/layout.h:39:0,
                 from ./src/capnp/generated-header-support.h:32,
                 from src/capnp/test-import2.capnp.h:7,
                 from src/capnp/test-import2.capnp.c++:4:
./src/capnp/blob.h:47:9: note: candidate: constexpr capnp::Text::Pipeline::Pipeline()
   class Pipeline {};
         ^~~~~~~~
./src/capnp/blob.h:47:9: note:   candidate expects 0 arguments, 1 provided
./src/capnp/blob.h:47:9: note: candidate: constexpr capnp::Text::Pipeline::Pipeline(const capnp::Text::Pipeline&)
./src/capnp/blob.h:47:9: note:   no known conversion for argument 1 from 'capnp::AnyPointer::Pipeline' to 'const capnp::Text::Pipeline&'
./src/capnp/blob.h:47:9: note: candidate: constexpr capnp::Text::Pipeline::Pipeline(capnp::Text::Pipeline&&)
./src/capnp/blob.h:47:9: note:   no known conversion for argument 1 from 'capnp::AnyPointer::Pipeline' to 'capnp::Text::Pipeline&&'
In file included from src/capnp/test-import.capnp.h:16:0,
                 from src/capnp/test-import2.capnp.h:17,
                 from src/capnp/test-import2.capnp.c++:4:
src/capnp/test.capnp.h: In member function 'capnp::Text::Pipeline capnproto_test::capnp::test::TestMoreStuff::MethodWithNullDefaultParams::Pipeline::getA()':
src/capnp/test.capnp.h:32799:63: error: no matching function for call to 'capnp::Text::Pipeline::Pipeline(capnp::AnyPointer::Pipeline)'
   return  ::capnp::Text::Pipeline(_typeless.getPointerField(0));
```

As though the compiler's getting very confused about the types it's dealing with.

Full log output available here: https://buildd.debian.org/status/fetch.php?pkg=capnproto&arch=mips64el&ver=0.6.1-1&stamp=1503916947&raw=0 ... Recognize this probably isn't much to go on. If nothing leaps out at you, I'll request mips64el porterbox access later this week & try to reproduce.

**Comment by kentonv** [comment]
So it appears that many of the list-typed fields are being treated as pipeline-able, contrary to the line I quoted earlier. I really don't see how this is possible.

It might be worth running the compiler under valgrind. Specifically the capnpc-c++ subcommand. So first you'd generate the codegen request like:

    ./capnp -o- -Isrc --src-prefix=src src/capnp/test.capnp > codegen-request.bin

Then you could run capnpc-c++ under valgrind:

    mkdir tmp
    cd tmp
    valgrind ../capnpc-c++ < codegen-request.bin

That said, I'm not seeing any issues raised on x86-64.

**Comment by thomaslee** [comment]
Never did get around to digging deeper, but the build was later retried & succeeded anyway. Possible this was actually a Debian bug, perhaps in gcc. Closing this for now, but will reopen if it resurfaces. Sorry for the false alarm!
