### ISSUE TITLE
Can cap'n support some structs like iovec ?

### ISSUE THREAD

**Issue by shanshanpt** [capnproto/capnproto#545]
Hi, Can cap'n support some structs like iovec ? :)
Hmm...the rpc I used that needed the iovec struct :( ,  so...

Thanks~

**Comment by shanshanpt** [comment]
2.
Forgive me not to open a new issue :)
One more question:

**_This is my .canp file:_**
struct BigData {
	data @1 :Data;
}

**_My code: write msg to fd_**
// I have a big blob data to write and receive
const uint64_t gcount = 1024 * 8 * 1024 * 1024;

::capnp::MallocMessageBuilder message;
BigData::Builder bigData = message.initRoot<BigData>();
// I dont want to copy, so I used the Orphanage.
capnp::Orphanage orphan = message.getOrphanage();
bigData.adoptData(orphan.referenceExternalData(::capnp::Data::Reader(data, gcount)));
writePackedMessageToFd(fd1, message);

**_when I read the msg from fd2:_**
(The code is running in the other thread)
::capnp::StreamFdMessageReader message(fd2);
BigData::Reader bigData = message.getRoot<BigData>();
const unsigned char * ptr = bigData.getData().begin();
cout << ptr << endl;

**_Error is _**
libc++abi.dylib: terminating with uncaught exception of type kj::ExceptionImpl: kj/units.c++:28: failed: integer overflow
libc++abi.dylib: terminating with uncaught exception of type kj::ExceptionImpl: kj/io.c++:48: failed: expected n >= minBytes; Premature EOF

I am try to change my code as follow:
::capnp::ReaderOptions opt;
opt.traversalLimitInWords = gcount;   // reader option
::capnp::PackedFdMessageReader message(fd2, opt);

But also the same error.

I dont why. Please give me any help ~ Thanks ~ :)

**Comment by kentonv** [comment]
> Hi, Can cap'n support some structs like iovec ? :)

I don't understand what you mean here. Do you want your message to contain iovecs, or are you saying you want the Cap'n Proto C++ API to support a serialization method that gives you iovecs, or something else? Maybe you could describe what you're trying to do with iovec...

> const uint64_t gcount = 1024 * 8 * 1024 * 1024;

It looks like you have a data blob of 8 GB here. Unfortunately Cap'n Proto only supports encoding up to 512MB in one data blob. You'll need to split the blob into multiple pieces.

I think your uncaught exception should be thrown by the code that constructs the message, not by the code reading the message. Is that what you're seeing?

**Comment by shanshanpt** [comment]
1. Hmm... I saw the function FdOutputStream::write, every segment was send as a iovec[i]. So I think it's what I want.
2. Yes, when I set  "const uint64_t gcount = 8 * 1024 * 1024;", I can run program successful.

And...
Is KJ an IO library like libevent? Can I use something like libevent to replace it?  Now I may not give up my IO library, so I want to use the can'p as the data transfer format, and I will receive the bytes stream and the parse them into message by myself. What do you think of this difficulty? And can u give me any advice. Or, you suggest the KJ?  :)  Thanks.  :)

**Comment by kentonv** [comment]
KJ includes an asynchronous I/O event framework which does similar things to libevent. Cap'n Proto's RPC layer depends on KJ's async layer. However, you can use Cap'n Proto's serialization layer without using its RPC layer. If you use only the serialization layer, then you do not need to use KJ's event framework. (KJ's event framework is complied as a separate library, libkj-async.so, and Cap'n Proto RPC is in a library libcapnp-rpc.so. If you only want serialization, you only need libcapnp.so and libkj.so.)

It's also possible to integrate KJ's event framework with other libraries (like libevent), although this is somewhat complicated.

**Comment by shanshanpt** [comment]
OK, thanks so much. 👍
