### ISSUE TITLE
MSVC workaround for kj/parse/common.h fails with clang/llvm

### ISSUE THREAD

**Issue by erikmchut** [capnproto/capnproto#559]
We use clang/llvm for windows compilation, and the workarounds that were added to kj/parse/common.h for Visual Studio fail to compile under an llvm toolchain.

Our current workaround is to remove the _MSC_VER guards in kj/parse/common.h. We need to keep them elsewhere else for win32/win64 portability.

Here is an example compile command and error:
`
$ clang -fms-compatibility -fms-extensions -fdelayed-template-parsing -fexceptions -mthread-model posix -fno-threadsafe-statics -target x86_64-pc-win32 -Wno-msvc-not-found -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -D_WIN32 -D_MT -D_DLL -Xclang -disable-llvm-verifier -Xclang '--dependent-lib=msvcrt' -Xclang '--dependent-lib=ucrt' -Xclang '--dependent-lib=oldnames' -Xclang '--dependent-lib=vcruntime' -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE '-fms-compatibility-version=19' -Wno-invalid-constexpr -U__GNUC__ -U__gnu_linux__ -U__GNUC_MINOR__ -U__GNUC_PATCHLEVEL__ -U__GNUC_STDC_INLINE__ -fcolor-diagnostics -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -fcxx-exceptions '-std=c++14' -MD -MF bazel-out/win_x86_64-opt/bin/external/capnproto/_objs/capnp-lib/external/capnproto/c++/src/capnp/schema-parser.d '-frandom-seed=bazel-out/win_x86_64-opt/bin/external/capnproto/_objs/capnp-lib/external/capnproto/c++/src/capnp/schema-parser.o' '-DKJ_USE_FUTEX=0' -iquote external/capnproto -iquote bazel-out/win_x86_64-opt/genfiles/external/capnproto -iquote external/bazel_tools -iquote bazel-out/win_x86_64-opt/genfiles/external/bazel_tools -isystem external/capnproto/c++/src -isystem bazel-out/win_x86_64-opt/genfiles/external/capnproto/c++/src -isystem external/bazel_tools/tools/cpp/gcc3 -Wno-sign-compare -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -isystem external/msvctoolchain/x86_64/include/msvc -isystem external/msvctoolchain/x86_64/include/um -isystem external/msvctoolchain/x86_64/include/ucrt -isystem external/msvctoolchain/x86_64/include/shared -isystem external/msvctoolchain/x86_64/include/winrt -c external/capnproto/c++/src/capnp/schema-parser.c++ -o bazel-out/win_x86_64-opt/bin/external/capnproto/_objs/capnp-lib/external/capnproto/c++/src/capnp/schema-parser.o)
ERROR: /private/var/tmp/_bazel_mc/c4f4f6f74f33415f35a1ab44963d1e4f/external/capnproto/BUILD:37:1: C++ compilation of rule '@capnproto//:capnp-lib' failed: Process exited with status 1 [sandboxed].
In file included from external/capnproto/c++/src/capnp/compiler/lexer.c++:22:
In file included from external/capnproto/c++/src/capnp/compiler/lexer.h:29:
In file included from external/capnproto/c++/src/capnp/compiler/lexer.capnp.h:7:
In file included from external/capnproto/c++/src/capnp/generated-header-support.h:31:
In file included from external/capnproto/c++/src/capnp/raw-schema.h:32:
In file included from external/msvctoolchain/x86_64/include/msvc/atomic:12:
external/msvctoolchain/x86_64/include/msvc/type_traits:1915:2: error: no type named 'type' in 'std::result_of<const kj::parse::EndOfInput_ &(capnp::compiler::Lexer::ParserInput)>'
        using result_of_t = typename result_of<_Ty>::type;
        ^~~~~
external/capnproto/c++/src/kj/parse/common.h:106:1: note: in instantiation of template type alias 'result_of_t' requested here
using OutputType = typename OutputType_<
^
external/capnproto/c++/src/kj/parse/common.h:361:20: note: in instantiation of template type alias 'OutputType' requested here
          instance<OutputType<FirstSubParser, Input>>(),
                   ^
external/capnproto/c++/src/kj/parse/common.h:354:19: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::EndOfInput_ &>::parseNext<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Statement> > >' requested here
      return rest.parseNext(input, kj::fwd<InitialParams>(initialParams)...,
                  ^
external/capnproto/c++/src/kj/parse/common.h:341:12: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::ParserRef<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Statement> > > &, const kj::parse::EndOfInput_ &>::parseNext<capnp::compiler::Lexer::ParserInput>' requested here
    return parseNext(input);
           ^
external/capnproto/c++/src/capnp/compiler/lexer.c++:38:63: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::ParserRef<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Statement> > > &, const kj::parse::EndOfInput_ &>::operator()<capnp::compiler::Lexer::ParserInput>' requested here
  kj::Maybe<kj::Array<Orphan<Statement>>> parseOutput = parser(parserInput);
                                                              ^
In file included from external/capnproto/c++/src/capnp/compiler/lexer.c++:22:
In file included from external/capnproto/c++/src/capnp/compiler/lexer.h:29:
In file included from external/capnproto/c++/src/capnp/compiler/lexer.capnp.h:7:
In file included from external/capnproto/c++/src/capnp/generated-header-support.h:31:
In file included from external/capnproto/c++/src/capnp/raw-schema.h:32:
In file included from external/msvctoolchain/x86_64/include/msvc/atomic:12:
external/msvctoolchain/x86_64/include/msvc/type_traits:1915:2: error: no type named 'type' in 'std::result_of<const kj::parse::ParserRef<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Statement> > > &(capnp::compiler::Lexer::ParserInput)>'
        using result_of_t = typename result_of<_Ty>::type;
        ^~~~~
external/capnproto/c++/src/kj/parse/common.h:106:1: note: in instantiation of template type alias 'result_of_t' requested here
using OutputType = typename OutputType_<
^
external/capnproto/c++/src/kj/parse/common.h:361:20: note: in instantiation of template type alias 'OutputType' requested here
          instance<OutputType<FirstSubParser, Input>>(),
                   ^
external/capnproto/c++/src/kj/parse/common.h:341:12: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::ParserRef<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Statement> > > &, const kj::parse::EndOfInput_ &>::parseNext<capnp::compiler::Lexer::ParserInput>' requested here
    return parseNext(input);
           ^
external/capnproto/c++/src/capnp/compiler/lexer.c++:38:63: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::ParserRef<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Statement> > > &, const kj::parse::EndOfInput_ &>::operator()<capnp::compiler::Lexer::ParserInput>' requested here
  kj::Maybe<kj::Array<Orphan<Statement>>> parseOutput = parser(parserInput);
                                                              ^
In file included from external/capnproto/c++/src/capnp/compiler/lexer.c++:22:
In file included from external/capnproto/c++/src/capnp/compiler/lexer.h:29:
In file included from external/capnproto/c++/src/capnp/compiler/lexer.capnp.h:7:
In file included from external/capnproto/c++/src/capnp/generated-header-support.h:31:
In file included from external/capnproto/c++/src/capnp/raw-schema.h:32:
In file included from external/msvctoolchain/x86_64/include/msvc/atomic:12:
external/msvctoolchain/x86_64/include/msvc/type_traits:1915:2: error: no type named 'type' in 'std::result_of<const kj::parse::EndOfInput_ &(capnp::compiler::Lexer::ParserInput)>'
        using result_of_t = typename result_of<_Ty>::type;
        ^~~~~
external/capnproto/c++/src/kj/parse/common.h:106:1: note: in instantiation of template type alias 'result_of_t' requested here
using OutputType = typename OutputType_<
^
external/capnproto/c++/src/kj/parse/common.h:361:20: note: in instantiation of template type alias 'OutputType' requested here
          instance<OutputType<FirstSubParser, Input>>(),
                   ^
external/capnproto/c++/src/kj/parse/common.h:354:19: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::EndOfInput_ &>::parseNext<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Token> > >' requested here
      return rest.parseNext(input, kj::fwd<InitialParams>(initialParams)...,
                  ^
external/capnproto/c++/src/kj/parse/common.h:341:12: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::ParserRef<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Token> > > &, const kj::parse::EndOfInput_ &>::parseNext<capnp::compiler::Lexer::ParserInput>' requested here
    return parseNext(input);
           ^
external/capnproto/c++/src/capnp/compiler/lexer.c++:60:59: note: in instantiation of function template specialization 'kj::parse::Sequence_<const kj::parse::ParserRef<capnp::compiler::Lexer::ParserInput, kj::Array<capnp::Orphan<capnp::compiler::Token> > > &, const kj::parse::EndOfInput_ &>::operator()<capnp::compiler::Lexer::ParserInput>' requested here
  kj::Maybe<kj::Array<Orphan<Token>>> parseOutput = parser(parserInput);
                                                          ^

`

**Comment by kentonv** [comment]
I'd be happy to accept a pull request that adds appropriate checks to see if the compiler is Clang. I imagine you'd do something like:

    #if _MSC_VER && !__clang__

It would be very helpful if you could contribute a patch as I don't have easy access to an environment with Clang running in MSVC emulation mode.

**Comment by erikmchut** [comment]
Sure thing, PR at https://github.com/capnproto/capnproto/pull/561

I verified this works when cross-compiling to windows x86_64 from llvm on OS X
