### ISSUE TITLE
Windows build fails with Visual Studio 2015 Update 1

### ISSUE THREAD

**Issue by G-glop** [capnproto/capnproto#573]
The build fails due to ambiguous comparison operators in kj/units.h. When Visual Studio is reinstalled with update 3 the issue goes away.

Don't know if it's worth fixing. Maybe  just give a heads up in the installation instructions?

**Comment by kentonv** [comment]
The installation instructions do say "Cap’n Proto requires Visual Studio 2015 Update 3 or newer." in the Prerequisites section. Do you feel we should repeat this in other places?

**Comment by G-glop** [comment]
It is also the first step when using Cap'n Proto with Visual Studio. So i don't think mentioning it more would help. Ideal-world solution would be to check Visual Studio updates in CMake. Alternatively in the build process itself.

Closing because of false positive.
