### ISSUE TITLE
Using LPTSTR as LPSTR is undefined

### ISSUE THREAD

**Issue by Leandros** [capnproto/capnproto#574]
`debug.c++`, line 367. The call to the function `FormatMessageA` requires the user to pass in a `LPSTR`, but the argument `&ptr` is getting cast to `LPTSTR`, which might be defined to be a wide-string if `UNICODE` is defined. It's better to explicitly cast to `LPSTR`, or even better, since the "ASCII" API is long deprecated, use `FormatMessageW` and convert the returned wide-string into UTF-8, by using `WideCharToMultiByte`.

As of right now, defining `UNICODE` does not allow to compile Cap'n Proto. MSVC will throw the following error:

```
c:\<redacted>\capnproto-c++-0.6.1\src\kj\debug.c++(367,55): error C2664: 'DWORD FormatMessageA(DWORD,LPCVOID,DWORD,DWORD,LPSTR,DWORD,va_list *)': cannot convert argument 5 from 'LPTSTR' to 'LPSTR'
```

**Comment by kentonv** [comment]
Looks like I fixed this at 418e0ad4c10b55a57dcb2b903828d3b8390653cd, but I forgot there was a bug for it. (The code uses `FormatMessageW` now.)
