### ISSUE TITLE
capnp_generate_cpp() where src_prefix / output_dir are not nested

### ISSUE THREAD

**Issue by aldanor** [capnproto/capnproto#586]
If schema is located in `foo/schema.capnp` and output dir is to `bar/`, then `capnp_generate_cpp()` erroneously complains that

```
  Could not determine output path for 'schema.capnp'
  ('/home/schema.capnp') with source
  prefix '/home/foo' into
  '/home/bar'.
```

where the following is set:

```cmake
set(CAPNPC_SRC_PREFIX "${CMAKE_CURRENT_SOURCE_DIR}/foo" CACHE STRING "" FORCE)
set(CAPNPC_OUTPUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/bar" CACHE STRING "" FORCE)
file(MAKE_DIRECTORY "${CAPNPC_OUTPUT_DIR}")
...
capnp_generate_cpp(CAPNP_SOURCES CAPNP_HEADERS schema.capnp)
```

Whereas command line tool deals perfectly fine with that:

```sh
$ capnpc -o c++:bar --src-prefix=foo foo/schema.capnp

$ ls bar
schema.capnp.c++
schema.capnp.h
```

**Comment by kentonv** [comment]
Hi Ivan,

The error message suggests that the compiler was invoked like:

    capnpc -o c++:bar --src-prefix=foo schema.capnp

I.e., `schema.capnp` is found in the current directory, not under `foo/`. In that case the error is correct.

I don't really know cmake, but it seems like this is what you asked for here:

    capnp_generate_cpp(CAPNP_SOURCES CAPNP_HEADERS schema.capnp)

Perhaps what you really want is:

    capnp_generate_cpp(CAPNP_SOURCES CAPNP_HEADERS foo/schema.capnp)

?

**Comment by aldanor** [comment]
@kentonv Yep, that's what I've tried initially, which seems to fail as well with

```
  Cap'n Proto schema file
  'foo/foo/schema.capnp'
  does not exist!
```

Which led me to believe that there's some inconsistency there after all :)

**Comment by harrishancock** [comment]
`capnp_generate_cpp()` checks for existence of each schema file argument and errors out if one doesn't exist. It prepends the src-prefix path to each schema file argument when checking for existence: https://github.com/capnproto/capnproto/blob/master/c%2B%2B/cmake/CapnProtoMacros.cmake#L74

If `capnp` interprets file path arguments differently, then this check is incorrect and we should remove it, or possibly change it to test for existence relative to `CMAKE_CURRENT_SOURCE_DIR`.

**Comment by kentonv** [comment]
@harrishancock Indeed, the capnp compiler expects filenames passed to it are relative to the current directory (or absolute), *not* relative to the src prefix, so it seams this check is wrong.

Little-known fact: You can specify multiple `--src-prefix`es, and the tool will assume the most-specific one that matches the file name. This lets you process input from multiple source trees in a single invocation. (But I don't think it's necessary to support this in the cmake rules.)

**Comment by harrishancock** [comment]
Pushed a PR to fix this. @aldanor, I tested the use case you outlined with the PR, and it seems to work. This snippet:

```cmake
set(CAPNPC_SRC_PREFIX "${CMAKE_CURRENT_SOURCE_DIR}/foo" CACHE STRING "" FORCE)
set(CAPNPC_OUTPUT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/bar" CACHE STRING "" FORCE)
file(MAKE_DIRECTORY "${CAPNPC_OUTPUT_DIR}")
...
capnp_generate_cpp(CAPNP_SOURCES CAPNP_HEADERS foo/schema.capnp)  # Note foo/ prefix
```

correctly compiles the input and places it in `${CMAKE_CURRENT_SOURCE_DIR}/bar`.

**Comment by aldanor** [comment]
@harrishancock That's great, thanks! Yes, that's how I'd expect it to work, matching what CLI does. Lf to it getting merged.

/* Apologies if slightly off-topic, but are there any plans for version bump anytime soon? */
