### ISSUE TITLE
Strange link issue on Linux [C++][LINUX]

### ISSUE THREAD

**Issue by skyloupe** [capnproto/capnproto#602]
Get the following linker error on Linux, however on Windows and Mac same project compiles and links successfully:

geoffrey@jethro:~/work/capnsamples/build$ cmake --build .
Scanning dependencies of target testy
[ 33%] Building CXX object c++/testy/CMakeFiles/testy.dir/main.cpp.o
[ 66%] Building CXX object c++/testy/CMakeFiles/testy.dir/myproto.capnp.c++.o
[100%] Linking CXX executable testy
/home/geoffrey/apps/capnproto/lib/libcapnp-json.a(json.c++.o): In function `capnp::JsonCodec::encodeRaw(capnp::JsonValue::Reader) const':
json.c++:(.text+0x64a): undefined reference to `kj::StringTree::flatten() const'
/home/geoffrey/apps/capnproto/lib/libcapnp-json.a(json.c++.o): In function `capnp::JsonCodec::Impl::encodeList(kj::Array<kj::StringTree>, bool, unsigned int, bool&, bool) const':
json.c++:(.text._ZNK5capnp9JsonCodec4Impl10encodeListEN2kj5ArrayINS2_10StringTreeEEEbjRbb[_ZNK5capnp9JsonCodec4Impl10encodeListEN2kj5ArrayINS2_10StringTreeEEEbjRbb]+0x417): undefined reference to `kj::StringTree::StringTree(kj::Array<kj::StringTree>&&, kj::StringPtr)'
collect2: error: ld returned 1 exit status
c++/testy/CMakeFiles/testy.dir/build.make:120: recipe for target 'c++/testy/testy' failed
make[2]: *** [c++/testy/testy] Error 1
CMakeFiles/Makefile2:85: recipe for target 'c++/testy/CMakeFiles/testy.dir/all' failed
make[1]: *** [c++/testy/CMakeFiles/testy.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Failing project is located at:

https://github.com/gatkinso/capnsamples

PS - this project is in its infancy - you may need to tweak the directory setting in the CMakeLists.txt file to get it to compile on your system (or build and install capnproto in $HOME/apps/capnproto).

**Comment by kentonv** [comment]
Hi @skyloupe,

I haven't tested it, but I think the problem may be with this line:

    target_link_libraries(${TGT_NAME} capnp kj capnp-json kj-async)

On some OSs and some linkers, the order of libraries matters. You need to list each library before all of its dependencies. In your case, capnp-json is failing to find symbols defined in kj, because kj is listed before capnp-json. Try changing the order to:

    target_link_libraries(${TGT_NAME} capnp-json capnp kj-async kj)

**Comment by skyloupe** [comment]
Yes that is it.  Thanks!
