### ISSUE TITLE
EagerlyEvaluate documentation doesn't match implementation

### ISSUE THREAD

**Issue by G-glop** [capnproto/capnproto#611]
As i understand, exceptions propagate through the promise chain either to be caught by Promise::then (which returns a substitue value) or rethrown at the site calling Promise::wait.

eagerlyEvaluate's handler should just look at the exception while it's propagating, and return nothing.

The problem is that eagerlyEvaluate treats it's argument as Promise::then's errorHandler.

Example:
```
kj::Promise<int> promise = kj::evalNow([&]() {return 1; });

promise = promise.then([&](auto c) {
		printf("first callback\n");
		KJ_FAIL_ASSERT("an exception");
		return c;
	}).eagerlyEvaluate([&](kj::Exception&& e) {
		printf("eager evaluation callback\n");
		return 2; //won't compile without returning int
	});

promise = promise.then([&](auto c) {
		printf("second callback\n"); //shouldn't execute since an exception is propagating
		return c;
	});

promise.wait(aio.waitScope);
```

A workaround is to manually specify the return type, and rethrow the exception
```
promise = promise.then([&](auto c) {
		printf("first callback\n");
		KJ_FAIL_ASSERT("an exception");
		return c;
	}).eagerlyEvaluate([&](kj::Exception&& e) -> int {
		printf("eager evaluation callback\n");
		throw e;
	});

promise = promise.then([&](auto c) {
		printf("second callback\n"); 
	return c;
        });

promise.wait(aio.waitScope);
```

**Comment by kentonv** [comment]
Hi @G-glop,

This is working as intended: The callback passed to `.eagerlyEvaluate()` is intended to behave the same as one passed to `.catch_()` or as the second argument to `.then()`. I can see your argument, that `.eagerlyEvaluate()` probably usually wants to propagate the exception after logging it or something, and so maybe that should be the default behavior. However, I think it could also be confusing to be inconsistent with `.catch_()`. So, it's hard to say which is the better design. But, it's probably a moot point anyway: lots of code has already been written using the current behavior, and could be broken by any change, so we probably can't change it.

**Comment by G-glop** [comment]
I thought that's how it should work because of the comments for eagerlyEvaluate:

```
  // Force eager evaluation of this promise.  Use this if you are going to hold on to the promise
  // for awhile without consuming the result, but you want to make sure that the system actually
  // processes it.
  //
  // `errorHandler` is a function that takes `kj::Exception&&`, like the second parameter to
  // `then()`, except that it must return void.
```

**Comment by kentonv** [comment]
Ah, yes, that comment seems wrong. Thanks for pointing it out.
