### ISSUE TITLE
Documentation: Cap'n Proto requires GCC 4.8.1, not 4.8.0

### ISSUE THREAD

**Issue by roquo** [capnproto/capnproto#616]
I tried to build the release version of capnproto v0.6.1 but i got a lot of erros like expected initializer or expected ';' 
I followed the instructions from the website with
`autoreconf -i` 
`./configure`
`make -j6 check`
make then fails. 

I am working on Red Hat Linux Enterprise with GCC-4.8.0

**Comment by kentonv** [comment]
Hi @roquo,

Could you please provide a complete log of the errors? Obviously we don't expect there to be errors so I'll need to know exactly what the errors were and what lines they were on in order to understand what went wrong.

**Comment by roquo** [comment]
make output:
[makeLog.txt](https://github.com/capnproto/capnproto/files/1639741/makeLog.txt)

configure output:
[configureLog.txt](https://github.com/capnproto/capnproto/files/1639739/configureLog.txt)

**Comment by kentonv** [comment]
Hi @roquo,

It looks like your compiler is missing the C++11 feature "Rvalue references for *this". It looks like this feature was added in GCC 4.8.1:

https://gcc.gnu.org/projects/cxx-status.html

You mentioned you're using 4.8.0, so that seems to be the problem. It seems like we need to update our documentation to say that 4.8.1 is required.

**Comment by roquo** [comment]
Hi @kentonv,

this solved the first problem. I know its inappropriate to post this here, but when I am using make and configure, where can I tell the compiler to search for my libs (especially libstdc++6.so.6)? 

I got the error in the picture below and I have to tell the compiler, that my libs are not in /usr/lib64/ but in some home directory (i don't have any root rights)
![grafik](https://user-images.githubusercontent.com/35525625/35089458-4708a912-fc37-11e7-973c-5d083df36593.png)

Sorry, if i sound stupid, i am new to linux

**Comment by kentonv** [comment]
You need to pass the `-L` flag to the linker. Try something like:

    ./configure LIBS="-L/path/where/libraries/live"

You'll also need to set the `LD_LIBRARY_PATH` environment variable when running the program, to tell it where to find the dynamic libraries (or you could link statically, or you could use `-Wl,-rpath,<dir>` when linking to bake the path into the binary).

Note that building against a custom libstdc++ might involve some additional complications but unfortunately I don't have much experience with that.

**Comment by roquo** [comment]
Thanks a lot @kentonv 

Everything went fine, I hope there won't be any issues any more.
