### ISSUE TITLE
JSON encoder writes uint64 and int64 as strings

### ISSUE THREAD

**Issue by wridgers** [capnproto/capnproto#617]
I think this was an intentional decision, but I believe it to be incorrect.

> 64-bit integers are represented as decimal strings since Javascript numbers cannot represent 64-bit ints without precision loss.

(from here[1])

JSON is not Javascript Object. AFAICT from this[2] specification and this RFC[3] there is no restriction on the length of a number in JSON.

1: https://groups.google.com/forum/#!topic/capnproto/SZ4qquBoeeQ
2: https://www.json.org/
3: https://tools.ietf.org/html/rfc7159

**Comment by katreniak** [comment]
Copy & paste from rfc7159

````
   This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.
````

**Comment by wridgers** [comment]
Encoding 64-bit integers as strings makes its output harder to deal with - if whatever is consuming the JSON can't process it correctly, then the input to `JsonCodec` should be changed or `JsonCodec` should have some form of "compatibility mode". (as in, that should be a decision left to the developer). They're going to get bitten, as I was, by sudden unexpected strings anyway. 😄

**Comment by katreniak** [comment]
I would say that that json aware api design shall avoid 64-bit integers.

> They're going to get bitten, as I was, by sudden unexpected strings anyway.

Documentation may help here. Needs contributions :)

**Comment by kentonv** [comment]
Sorry, this is working as intended. As ugly as it is, this is pretty standard practice -- [Protocol Buffers actually does the same thing](https://developers.google.com/protocol-buffers/docs/proto3#json). Since all int64s are consistently encoded as strings (even for values that could be exactly-represented as numbers), it should be easy to catch this in testing.

With that said, you can get the behavior you want by registering a custom type handler for int64s using `JsonCodec::addTypeHandler()`.

Something like (not tested):

    class Int64Handler: public capnp::JsonCodec::Handler<int64_t> {
    public:
      void encode(const JsonCodec& codec, int64_t input, JsonValue::Builder output) const override {
        output.setNumber(input);
      }
      int64_t decode(const JsonCodec& codec, JsonValue::Reader input) const override {
        KJ_REQUIRE(input.isNumber());
        return static_cast<int64_t>(input.getNumber());
      }
    };

    JsonCodec myCodec;
    Int64Handler handler;
    myCodec.addTypeHandler(handler);

You'll need to repeat the process for `uint64_t`.

Of course, note that since the underlying JSON parser parses all numbers as doubles, this type handler will suffer from the same loss of precision that you'd see in JavaScript. Sorry, even though the spec is vague, reality is that basically all JSON implementations parse numbers to IEEE-754 doubles.

**Comment by wridgers** [comment]
Hi @kentonv, thanks for responding.

I tried your suggestion but didn't have much success. Here's my `Int64Hander`:

```
  class Int64Handler: public capnp::JsonCodec::Handler<int64_t> {
  public:
    void encode(const capnp::JsonCodec& codec, capnp::ReaderFor<int64_t> input, capnp::JsonValue::Builder output) const override {
      output.setNumber(input);
    }

    int64_t decode(const capnp::JsonCodec& codec, capnp::JsonValue::Reader input) const override {
      KJ_UNIMPLEMENTED("Int64Handler::decode");
    }
  };
```

It will compile, but segfaults when I try running it. I'm not really sure what I'm doing wrong.

I also had a go at making a void hander, but I get the same kind of result.

```
  class VoidHandler: public capnp::JsonCodec::Handler<capnp::Void> {
  public:
    void encode(const capnp::JsonCodec& codec, capnp::ReaderFor<capnp::Void> input, capnp::JsonValue::Builder output) const override {
      output.setNull();
    }

    capnp::Void decode(const capnp::JsonCodec& codec, capnp::JsonValue::Reader input) const override {
      KJ_UNIMPLEMENTED("VoidHandler::decode");
    }
  };

m_json = new capnp::JsonCodec();
VoidHandler voidHandler;
m_json->addTypeHandler(voidHandler);
```

Is there anything I'm obviously doing wrong? Any pointers (pun!) would be greatly appreciated. :)

**Comment by wridgers** [comment]
I figured out my silly mistake, it was unrelated. Thanks anyway! :)
