### ISSUE TITLE
Question: how to do packed structs?

### ISSUE THREAD

**Issue by jamespinkerton** [capnproto/capnproto#621]
Hi I was wondering if there's any way to generate C structs with the attributes:

```
__attribute__((aligned(64)))
__attribute__((packed))
```

Thanks so much!

**Comment by kentonv** [comment]
Hi James,

Sorry, Cap'n Proto is not intended to be compatible with C structs. While Cap'n Proto messages use similar layout techniques to what a C compiler might do with a C struct, there are important differences made for the purposes of compatibility across languages and architectures, space efficiency, and relocatability. There's no way to tell Cap'n Proto to use a layout that is exactly compatible with a C struct (even without special attributes).

**Comment by kentonv** [comment]
Though with that said, note that all Cap'n Proto structures use 64-bit alignment, and fields are re-ordered for maximum packing efficiency (without any need to sacrifice alignment).
