### ISSUE TITLE
Document that a non-null empty struct pointer should have offset of -1

### ISSUE THREAD

**Issue by popham** [capnproto/capnproto#625]
Suppose I've got a trivial struct that I've upgraded, say

```
Person {}
Org {
  name @0 :Text;
  accountant @1 :Person;
}
```

became

```
Person {
  id @0 :UInt64 = 7;
}
Org {
  name @0 :Text;
  accountant @1 :Person = (id=1);
}
```

Further suppose that my compile of the updated schema receives a zero-width `Person`, `p`.

If I build a message rooted with `Org` and, first thing, I set its `accountant` field to `p`, then I wouldn't be surprised if [allocate](https://github.com/capnproto/capnproto/blob/02be7235a84515687a291630c8e52b0dc93ed8ff/c%2B%2B/src/capnp/layout.c%2B%2B#L1764) yields a zero-width object immediately following the `accountant` field's pointer, i.e. with a zero offset. This zero-width, zero-offset struct pointer is null, right? So when I get the field it'll be upgraded to (id=1), right?

Alternatively, if I build a message rooted with `Org` and, first thing, I set its `name` field to "Oh, Lord!". Now when I set the `accountant` field to `p` I expect  `allocate` to yield a zero-width object with a *non*zero offset. This struct pointer is *non*null, right? So when I get the field under this scenario it'll be upgraded to (id=7), right?

If I've correctly characterized both scenarios, then the behavior seems indefensible. Have I missed something? My instinct is to encode all zero-width structs with an offset of -1.

**Comment by kentonv** [comment]
> My instinct is to encode all zero-width structs with an offset of -1.

Good instinct.

https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/layout.c++#L166-L173

**Comment by popham** [comment]
Thanks

**Comment by kentonv** [comment]
Let's keep this open as an issue to document this better.
