### ISSUE TITLE
Does not compile under Clang 5 due to missing project()s.

### ISSUE THREAD

**Issue by Timmmm** [capnproto/capnproto#629]
On OSX (and possibly others), using Clang 5, which is the default you get from `brew install llvm`, capnproto unfortunately doesn't compile. This is because it is [missing a `project()` call](https://gitlab.kitware.com/cmake/cmake/issues/17712) ([more info](https://gitlab.kitware.com/cmake/cmake/issues/17714)) in the root `CMakeLists.txt`.

The simplest way to solve this is to move the `project()` call from the `c++/CMakeLists.txt` to the root `CMakeLists.txt`. Or you could delete the root `CMakeLists.txt` and tell everyone to run CMake in `c++` - that seems to match what your test scripts do. Or have a `project()` in both files. That's probably the safest option. I'll submit a pull request for that.

Also `project()` should come *after* the `cmake_minimum_required()`.

**Comment by kentonv** [comment]
Fixed by #630. Thanks!
