### ISSUE TITLE
Reuse MallocMessageBuilder

### ISSUE THREAD

**Issue by sachnk** [capnproto/capnproto#639]
Hi,

I'm using MallocMessageBuilder to build many small messages in loop to send on a socket. Is there a way for me to "clear" the builder, without triggering deallocation of the underlying memory, so that each message is builds on the same memory to avoid allocation overhead?

It seems allocating a MallocMessageBuilder for every message is inefficient due to memory allocations?

**Comment by katreniak** [comment]
`MallocMessageBuilder` has constructor to support this optimization:

````
  explicit MallocMessageBuilder(kj::ArrayPtr<word> firstSegment,
      AllocationStrategy allocationStrategy = SUGGESTED_ALLOCATION_STRATEGY);
  // This version always returns the given array for the first segment, and then proceeds with the
  // allocation strategy.  This is useful for optimization when building lots of small messages in
  // a tight loop:  you can reuse the space for the first segment.
  //
  // firstSegment MUST be zero-initialized.  MallocMessageBuilder's destructor will write new zeros
  // over any space that was used so that it can be reused.
````

**Comment by kentonv** [comment]
Yes, you should allocate a large static buffer and pass it as the first parameter to the `MallocMessageBuilder` constructor. As long as the message stays smaller than the buffer, no allocation will be needed. If the message grows larger than the first buffer, more segments will be allocated, and those segments will be freed by the destructor. So, choose the buffer size to be the maximum amount of memory that you want  to hold on to and reuse.
