### ISSUE TITLE
enum to string

### ISSUE THREAD

**Issue by sachnk** [capnproto/capnproto#649]
Hi,

I have a bunch of enums defined in my capnp schema. In my C++ code, I need to generate some ad-hoc json that should have the string representation of the enums defined in my schema. Obviously, capnp internally can convert enums to their corresponding strings, but are those methods publicly available to end-users?

I also know that capnp has a json codec, but creating a schema entry for the ad-hoc json is a bit too heavy-weight... the ad-hoc json is really meant for debugging.

Thanks!

**Comment by kentonv** [comment]
Hi @sachnk,

You can use `kj::str()`, the KJ universal stringification function:

    kj::String text = kj::str(enumValue);

If you need a `const char*`, you can then do:

    const char* cString = text.cStr();

(Note the `const char*` is owned by the `String` value, so either keep it around or make a copy.)

In general, `kj::str()` can be used to stringify many Cap'n Proto (and KJ) types. It can also be used for concatenation: pass multiple values and they'll be concatenated.

    const char* name = "Alice";
    int age = 24;
    auto text = kj::str("My name is ", name, " and I am ", age, " years old.");

Also note that if you need more details about the enum value (not just its name), you can get it through the dynamic API:

    capnp::DynamicEnum dynamic = capnp::toDynamic(enumValue);
    auto typeName = dynamic.getSchema().getProto().getDisplayName();

**Comment by sachnk** [comment]
Hi @kentonv ,

Thanks for the help with this earlier -- wanted to follow-up on doing the reverse of my original question, i.e. if I have a string, and I want to match it to a corresponding enum, how can I go about doing that?

Thanks!
