### ISSUE TITLE
Problem building with android api >= 23

### ISSUE THREAD

**Issue by plesner** [capnproto/capnproto#668]
There's a problem building for android with api >= 23:

```
capnproto/c++/src/kj/debug.c++:250:23: error: no viable overloaded '='
        sysErrorArray = strerror_r(errorNumber, buffer, sizeof(buffer));
        ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
capnproto/c++/src/kj/string.h:53:7: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'int' to 'const kj::StringPtr' for 1st argument
class StringPtr {
      ^
capnproto/c++/src/kj/string.h:53:7: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'int' to 'kj::StringPtr' for 1st argument
1 error generated.
```

I've fixed the problem in a fork (see https://gitlab.com/tundra1/capnproto/commit/eb8daba47118fa8ba4d5a7df0e0e44d49b1d7f31), would you be interested in a pull request?

**Comment by kentonv** [comment]
Yes, please.

But I'm confused by the commit -- it looks like your modification will still use this code path for api >= 23, and only disable fir for api < 23?

**Comment by plesner** [comment]
You're right, I got the versions mixed up in the description. The problem is with versions < 23, even with USE_GNU they had the posix version of strerror_r.

I'll submit a PR.
