### ISSUE TITLE
Support for trees of unions

### ISSUE THREAD

**Issue by Timmmm** [capnproto/capnproto#681]
It seems to be impossible to have a tree type where the generic tree node is a union of the possible node types. For example like this:

```
struct ExecuteProgram {
  code @0 :Text;
}

struct SequenceProgram {
  programs @0 :List(Program)
}

struct IfProgram {
  condition @1 :Program;
  trueBody @2 :Program;
  falseBody @3 :Program;
}

struct Program {
  union {
    execute @0 :ExecuteProgram;
    sequence @1 :SequenceProgram;
    if @2 :IfProgram;
  }
}
```

**Comment by kentonv** [comment]
Hi @Timmmm,

Why do you say this is impossible? The code you give seems like it should work just fine.

**Comment by Timmmm** [comment]
Ugh you are correct. Actually it *doesn't* work fine. It gives a parse error at `:List(Program)` but because the only error message for parse errors is `Parse error` I was forced to assume that this wouldn't work because it hadn't seen the `Program` type yet.

In fact I was missing a semicolon. See #680.
