### ISSUE TITLE
writeMessage ignores error handler

### ISSUE THREAD

**Issue by bazurbat** [capnproto/capnproto#682]
I writing a client and a service using CapnProto which should be able restore the broken connections. For this I'm trying to figure out the the various error scenarios and how to handle them and found the following strange case which I'm unable to explain. For example, given the following client:
```c++
#include <ipctest.capnp.h>

#include <capnp/message.h>
#include <capnp/serialize-async.h>
#include <capnp/serialize.h>
#include <kj/async-io.h>
#include <kj/async.h>
#include <kj/debug.h>

#include <chrono>
#include <thread>

using namespace std;
using namespace capnp;
using namespace kj;

int main()
{
    StringPtr address{"127.0.0.1:3457"};

    auto ioContext = setupAsyncIo();
    auto networkAddress = ioContext.provider->getNetwork().parseAddress(address).wait(ioContext.waitScope);
    auto connection = networkAddress->connect().wait(ioContext.waitScope);
    
    for (int i = 1; i <= 5; i++) {
        KJ_DBG("write", i);
        capnp::MallocMessageBuilder builder;
        auto message = builder.initRoot<Message>();
        message.setId(i);

        writeMessage(*connection, builder)
            .then([] { KJ_DBG("written"); },
                  [] (Exception&& ex) { KJ_DBG("write failed", ex); })
            .wait(ioContext.waitScope);

        this_thread::sleep_for(chrono::seconds{3});
    }

    return 0;
}
```
and the server:
```c++
#include <capnp/serialize-async.h>
#include <kj/debug.h>

using namespace std;
using namespace kj;
using namespace capnp;

int main()
{
    StringPtr str{"127.0.0.1:3457"};

    auto ioContext = setupAsyncIo();
    auto address = ioContext.provider->getNetwork().parseAddress(str).wait(ioContext.waitScope);
    auto receiver = address->listen();

    KJ_DBG("listening");
    auto connection = receiver->accept().wait(ioContext.waitScope);

    const size_t num = 7*1024*1024;
    word* words = new word[num];
    ArrayPtr<const word> segment0(words, num);
    ArrayPtr<const ArrayPtr<const word>> segments(&segment0, 1);

    for (int i = 0; i < 31; i++) {
        KJ_DBG("write", i);
        writeMessage(*connection, segments).wait(ioContext.waitScope);
    }

    KJ_DBG("done");

    return 0;
}
```
and capnp:
```capnp
struct message {
    id @0 :uint8;
}
```
When I run the server, then the client, then kill the server (by CTRL-C) I see the following message in the console:
```
capnptest/stream_client.cpp:26: debug: write; i = 1
capnptest/stream_client.cpp:33: debug: written
capnptest/stream_client.cpp:26: debug: write; i = 2
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  kj/async-io-unix.c++:311: disconnected: ::writev(fd, iov.begin(), iov.size()): Connection reset by peer
```
and the program crashes. But in the case of the following client:
```c++
#include <ipctest.capnp.h>

#include <capnp/message.h>
#include <capnp/serialize-async.h>
#include <capnp/serialize.h>
#include <kj/async-io.h>
#include <kj/async.h>
#include <kj/debug.h>

#include <chrono>
#include <thread>

using namespace std;
using namespace capnp;
using namespace kj;

int main()
{
    StringPtr address{"127.0.0.1:3457"};

    auto ioContext = setupAsyncIo();
    auto networkAddress = ioContext.provider->getNetwork().parseAddress(address).wait(ioContext.waitScope);
    auto connection = networkAddress->connect().wait(ioContext.waitScope);
    
    for (int i = 1; i <= 5; i++) {
        KJ_DBG("read", i);
        readMessage(*connection)
            .then([] (Own<MessageReader>&& reader) -> Promise<void> {
                return READY_NOW;
            }, [] (Exception&& ex) { KJ_DBG("read failed", ex); })
            .wait(ioContext.waitScope);

        this_thread::sleep_for(chrono::seconds{3});
    }

    return 0;
}
```
there is the output:
```
capnptest/stream_client.cpp:36: debug: read; i = 1
capnptest/stream_client.cpp:36: debug: read; i = 2
capnptest/stream_client.cpp:40: debug: read failed; ex = kj/async-io.c++:34: failed: expected result >= minBytes; Premature EOF
stack: 0x461c9d 0x460f0f 0x451721 0x454d42 0x45bc96 0x404cf0 0x407bd2 0x403540
    kj/async-io.c++:29: returning here
    capnp/serialize-async.c++:79: returning here
    stream_client.cpp:?: returning here
capnptest/stream_client.cpp:36: debug: read; i = 3
capnptest/stream_client.cpp:40: debug: read failed; ex = capnp/serialize-async.c++:156: failed: expected success; Premature EOF.
stack: 0x407c40 0x409488 0x40868a 0x451721 0x454d42 0x403540
    stream_client.cpp:?: returning here
```
I'm using Linux system, and see that both cases are have KJ_NONBLOCKING_SYSCALL in async-io-unix.c++ call in their internal functions. I do not understand why the behaviour is different. My expectation is that error handler after writeMessage should catch the exception is as in the readMessage case.

Wrapping the writeMessage call in evalLater and attaching the error handler to that solves the issue but I'm wondering which other exceptional cases I'm missing. My understanding is that try catch construct should not be necessary for normal capnp/kj usage. Please explain.

**Comment by bazurbat** [comment]
Thank you for the answer! The function throwing the exception synchronously was my suspicion as well but I wanted to be sure. It seems I've never managed to make the `tryInternalRead` function to throw which confused me initially, but after a few more experiments with inserting fails in CapnProto sources I think I have better understanding.

Could you expand a bit about synchronous in asynchronous exceptions typically end up in the same place? Do you mean `std::terminate`? In my case I have a long chain of return promises so that asynchronous error handlers and potential synchronous catches would be in a very different places. It might not even possible to handle the exception at the place of the call or higher in the stack. Are you suggesting to wrap all functions in `evalNow` on the call site if the caller installing a custom error handler because there is no way of knowing if it is required without analysing the sources? This is not very obvious from the API. I agree that it might be tedious to guarantee not throwing from the library side but otherwise this responsibility is pushed to the client or middleware. Is it intended? I do not see the `evalNow` used much in CapnProto sources itself, so maybe my assumption is wrong. I'm still trying to find the best patterns on how to use CapnProto in a fault tolerant way but custom error handlers are very hard to grep for. Maybe you can suggest some places in the sources to read for the recommended practices?

**Comment by kentonv** [comment]
Hi @bazurbat,

KJ exception handling is intended to be coarse-grained. The intent is that when a program is functioning "correctly", no exceptions occur at all. The only reasons you should catch an exception are:

* To display or log the error for consumption by a human.
* To contain the fault so that only the specific task fails, rather than causing the entire process to fail.
* To automatically retry in the case of "disconnected" (retry immediately) and "overloaded" (retry later) exceptions.

These things are all things you'd do at a high level in your program. The vast majority of code should not concern itself with catching exceptions, but should just let them propagate to a higher level.

When you do have the rare bit of code that needs to catch exceptions, you should normally wrap the entire "task" in a single `kj::runCatchingExceptions()` or `kj::evalNow()` -- use the former for purely-synchronous code, and the latter for code that returns a Promise.

Hmm, maybe what we should really do is deprecate `.catch_()` (and two-argument `.then()`) altogether, and introduce in their place a function `kj::runCatchingExceptionsAsync()` that is used like:

    kj::runCatchingExceptionsAsync([&]() {
      return someAsyncCode()
          .then(...)
          .then(...);
    }, [](kj::Exception&& e) {
      // Error handling code that will catch both synchronous and asynchronous exceptions.
    });

**Comment by bazurbat** [comment]
Thank you for the explanations! Sorry for the late response. I was on a vacation. I still has other questions but do not want steer this issue off topic. I will stick with `evalNow` for this particular case so the issue can be considered resolved.
