### ISSUE TITLE
question: how about the version 0.7?

### ISSUE THREAD

**Issue by nneesshh** [capnproto/capnproto#694]
Hi, everyone!
Is there a plan to release 0.7 version recently? Comming soon or later？

**Comment by kentonv** [comment]
I'm hoping to do a release in mid-to-late July.

**Comment by kentonv** [comment]
Release candidate:

* http://capnproto.org/capnproto-c++-0.7.0-rc1.tar.gz
* http://capnproto.org/capnproto-c++-win32-0.7.0-rc1.zip

Sorry it took so long.

**Comment by kentonv** [comment]
(Final release should be this week, assuming no one discovers anything horribly wrong.)

**Comment by kentonv** [comment]
https://capnproto.org/news/2018-08-28-capnproto-0.7.html
