### ISSUE TITLE
Inconsistent behavior in encoding integers via Windows build

### ISSUE THREAD

**Issue by slnovak** [capnproto/capnproto#712]
Hi,

I've been using Cap'n Proto v0.6.1 on Windows and came across a bug that I had a colleague verify. I've found that after writing a message to disk (with a MSVC-built client program -- see below) containing a simple struct with integer fields to disk, the `capnp.exe decode` command fails to decode the file if a certain value is encoded in the struct (`north=10`). However, using another value, such as `north=1`, does not result in a corrupted file. The same output file is also unable to be decoded using a GCC-built version of the `capnp` executable when a "bad" value is originally encoded into the message using the MSVC library of Cap'n Proto.

However, this behavior does not happen for a message written to disk from a GCC-built version of the client code. In other words, if I compile the same client program on Linux and encode `north=10`, both the GCC and MSVC version of the `capnp`/`capnp.exe` executable can correctly decode the file.

For example, here's the program that I've used to reproduce the issue:

```c++
// main.cpp
int main()
{
   capnp::MallocMessageBuilder builder;

   auto node = builder.initRoot<Node>();

   node.setNorth(1); // "1" results in a file that can be decoded via `capnp decode` but "10" results in a corrupted output file.
   node.setEast(2);
   node.setSouth(3);
   node.setWest(4);

#ifdef _WIN32
   int fd = _open("output.idx", O_CREAT | O_RDWR);
#else
   int fd = open("output.idx", O_CREAT | O_RDWR);
#endif

   ::capnp::writeMessageToFd(fd, builder);

#ifdef _WIN32
   _close(fd);
#else
   close(fd);
#endif

   return 0;
}
```

The schema is given as:

```
struct Node {
    north @0 :Int32;
    east @1 :Int32;
    south @2 :Int32;
    west @3 :Int32;
}
```

(AFAIK, the `east`, `south`, and `west` fields are not necessary to reproduce the problem.)

Using both GCC and MSVC versions of that program with "good" (`north=1`) and "bad" (`north=10`) value encoded shows that the MSVC version of the program renders corrupt data:

```
# Compile main.cpp with a "north" value of "10" (a "bad" value) using both MSVC and GCC

# Generate output.idx using MSVC-built program and "bad" value of "10"
» bin/capnpbug.exe

# Decode output.idx using Windows executable :boom:
» capnp.exe decode node.capnp Node < output.idx 
(north = 2573, east = 512, south = 768, west = 1024)
(north = 0, east = 0, south = 0, west = 0)
*** ERROR CONVERTING PREVIOUS MESSAGE ***
The following error occurred while converting the message above.
This probably means the input data is invalid/corrupted.
Exception description: expected n >= minBytes; Premature EOF
Code location: kj\io.c++:53
*** END ERROR ***

# Decode output.idx using Linux executable. :boom:
» capnp decode node.capnp Node < output.idx
(north = 2573, east = 512, south = 768, west = 1024)
*** Uncaught exception ***
kj/io.c++:48: failed: expected n >= minBytes; Premature EOF
stack: 0x7f0dc328bb50 0x7f0dc328b994 0x7f0dc34f87e7 0x414b77 0x415751 0x7f0dc3294fdc 0x7f0dc329686a 0x7f0dc32969e7

# Generate output.idx using GCC-built program and "bad" value of "10"
» bin/capnpbug 

# capnp can decode it.
» capnp decode node.capnp Node < output.idx
(north = 10, east = 2, south = 3, west = 4)

# capnp.exe can decode it.
» capnp.exe decode node.capnp Node < output.idx
(north = 10, east = 2, south = 3, west = 4)

# Change main.cpp to modify "north" value from "10" to "1", a "good" value and rebuild
# both versions of the executable.

# Generate output.idx using MSVC-built program and "good" value of "1"
» bin/capnpbug.exe

# We can decode it on Windows.
» capnp.exe decode node.capnp Node < output.idx
(north = 1, east = 2, south = 3, west = 4)

# We can decode it on Linux.
» capnp decode node.capnp Node < output.idx
(north = 1, east = 2, south = 3, west = 4)

# Generate output.idx using GCC-built program and "good" value of "1"
» bin/capnpbug

# We can decode it on Windows.
» capnp.exe decode node.capnp Node < output.idx 
(north = 1, east = 2, south = 3, west = 4)

# We can decode it on Linux.
» capnp decode node.capnp Node < output.idx
(north = 1, east = 2, south = 3, west = 4)
```

(Note, I've run the Windows-related commands in both cmd.exe and WSL's bash.exe to cover my bases. The behavior is the same.)

I'm not too familiar with the design of Cap'n Proto to dive in to figure out where this issue is coming from. Although I've had a colleague verify this bug, are there any other Windows users who would be interested in verifying the above behavior?  The steps for recreating are:

1. Compile the above main.cpp using Microsoft Visual Studio.
2. Run the resulting program.
3. Run `capnp.exe node.capnp Node < output.idx` and verify the tool fails.
4. Change the `north` field from `10` to `1`. Re-compile, run the program, and verify step 3 works.

Otherwise, does anyone have any insight into what could be the issue?

Thanks!!

**Comment by kentonv** [comment]
Hi Stefan,

The problem here is Windows/MS-DOS newline translation. You need to pass `O_BINARY` as a flag to `open()`. Otherwise, `\n` will be automatically converted to `\r\n`, corrupting the output. Similarly, on input, `\r\n` will be converted to `\n`, unless you open with `O_BINARY`.

This is an extremely frustrating "feature" of Microsoft operating systems. :(

**Comment by slnovak** [comment]
Thanks @kentonv!!
