### ISSUE TITLE
kj::Promise::wait() hangs forever

### ISSUE THREAD

**Issue by mamiral** [capnproto/capnproto#726]
Hello,
I'm very much liking your library - great work!

But I'm having a strange issue. 
Scenario:
1) Connect to rpc-server that is not a rpc-server (I use socat to listen to specified port)
2) Issue a command on the client (eg. somethingSomething.send().wait())
3) Ctrl-C on the client - you cant. ::wait blocks infinitely or till you kill the server

Is this mistake in my implementation? Or does wait() need some optional "timeout" parameter?

Thanks!
br

ps. Has development stoped?  Sure hope not!
pps. Can this be used in production?

**Comment by kentonv** [comment]
Hi @mamiral,

There is no timeout by default, so if you connect to a server that accepts the connection and receives packets but never responds, then indeed it will hang forever (although ctrl+C should work).

If you'd like to implement timeouts, you can use the `kj::Timer` interface's `timeoutAfter()` method.

    auto io = kj::setupAsyncIo();
    ...
    io.provider->getTimer().timeoutAfter(5 * kj::SECONDS, somethingSomething.send()).wait()

> ps. Has development stoped? Sure hope not!

https://github.com/capnproto/capnproto/commits/master :)

> pps. Can this be used in production?

It is used in production by many companies, such as at my employer, Cloudflare.

**Comment by kentonv** [comment]
Closing because this is a question, not an actionable issue. FWIW the best place to ask questions is: https://groups.google.com/group/capnproto
