### ISSUE TITLE
Setting a struct in a list to itself loses information

### ISSUE THREAD

**Issue by joonazan** [capnproto/capnproto#729]
I have code that sometimes effectively calls `list.setWithCaveats(i, list[i]);`. The result is that the union still has the same tag, but the data inside is zero.

**Comment by kentonv** [comment]
Thanks, this indeed looks buggy. It looks like this would have the effect of nulling out all the pointer fields (fields with struct, list, text, data, or capability type), while data fields (booleans, integers, floats, union tags) would remain unchanged.
