### ISSUE TITLE
Centos 6 compilation problem

### ISSUE THREAD

**Issue by smirnov-vs** [capnproto/capnproto#743]
I was not able to compile lib on centos 6 with devtoolset-7.
aligned_alloc() is not supported on this system.
I've added `__unix__` macro to branch with posix_memalign and it worked. (table.c++)
I have no idea is it final resolution or it is only fixing my case, so I'm writing this information here for you :)

**Comment by smirnov-vs** [comment]
test fail and not completed

`
2: [ TEST ] async-io-test.c++:50: legacy test: AsyncIo/SimpleNetwork
2: kj/async-io-unix.c++:522: failed: ::socket(addr.generic.sa_family, type, 0): Address family not supported by protocol
2: stack: 7d2197 5ef67c 615659 612d3b 798b6e 79c2d3 5ef734 5ef7a6 5c94b2 5efa6b 7ee406 7f2525
2:     async-io-unix.c++:?: returning here
2:     async-io-test.c++:?: returning here
2:     async-io-test.c++:?: returning here
2:     async-io-test.c++:?: returning here
2:     async.c++:?: returning here
2:     async.c++:?: returning here
2:     async-io-test.c++:?: returning here
2:     async-io-test.c++:?: returning here
2:     ??:?: returning here
2:     async-io-test.c++:?: returning here
2:     ??:?: returning here
2:     ??:?: returning here
2: [ FAIL ] async-io-test.c++:50: legacy test: AsyncIo/SimpleNetwork (47403 μs)
`

and then stuck here
`
2: [ TEST ] filesystem-disk-test.c++:354: DiskFile::copy()
`

**Comment by kentonv** [comment]
Hmm, sounds like we'll need a patch that actually fixes CentOS then.

**Comment by timkpaine** [comment]
Maybe this helps? https://github.com/Microsoft/CNTK/issues/729#issuecomment-276086884

**Comment by haata** [comment]
I'm unfortunately running into this issue when compiling pycapnp with manylinux2010 (https://github.com/capnproto/pycapnp/issues/197) as it uses CentOS 6 as the base.

For now I'll probably just add a patch when bundling that detects if building with a glibc older than 2.16
```
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.16  aligned_alloc
```

```c
#if __APPLE__ || __BIONIC || (defined(__GLIBC__) && (__GLIBC__ == 2) && (__GLIBC_MINOR__ < 16))
   // OSX and Android lack aligned_alloc(), but have posix_memalign(). Fine.
    void* allocPtr;
    int error = posix_memalign(&allocPtr,
        sizeof(BTreeImpl::NodeUnion), newCapacity * sizeof(BTreeImpl::NodeUnion));
    if (error != 0) {
      KJ_FAIL_SYSCALL("posix_memalign", error);
    }
    NodeUnion* newTree = reinterpret_cast<NodeUnion*>(allocPtr);
#else
...
```

**Comment by kentonv** [comment]
I'd be happy to accept a PR that switches us to always use `posix_memalign()` (except on `_WIN32`). I don't think there's any point in trying to use `aligned_alloc()` until we discover a platform that has it but doesn't have `posix_memalign()`.
