### ISSUE TITLE
Missing requirement for c++14

### ISSUE THREAD

**Issue by luigino** [capnproto/capnproto#752]
Using capnproto 0.7.0 built with autotools on openSUSE Tumbleweed; kj/common.h needs c++14 but this requirement is not reflected in kj.pc.

**Comment by kentonv** [comment]
Hi Luigi,

Hmm, is it possible to specify a minimum C++ standard version in a pkgconfig file? We can't just add `-std=c++14` to the `Cflags` as this might break people who want to use C++17 or later. I suppose pkg-config needs some explicit support for the `-std` flag but I can't find any indication that it has such support.

**Comment by luigino** [comment]
You're right, this was a misguided request on my part.
The C++ standard version should be handled at application level instead.
