### ISSUE TITLE
CONST interferes with windows.h

### ISSUE THREAD

**Issue by joonazan** [capnproto/capnproto#755]
This file does not compile in the newest version of Visual Studio. It misinterprets the all caps CONST as const.

https://github.com/capnproto/capnproto/blob/f73ac9f6667d7b87c395d23f3753dde63937cf00/c%2B%2B/src/capnp/schema.capnp.h#L83

**Comment by joonazan** [comment]
This line also failed to build with Clang. The VC++ error message was just misleading. The real culprit here seems to be a specific version of Windows 10 SDK that defines CONST. Maybe includes could be reordered to avoid this?

`C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared\minwindef.h(153):  note: expanded from macro 'CONST'`

**Comment by joonazan** [comment]
I was able to fix this by including Cap'n Proto reflection before windows.h. Whether you want to do something about this in Cap'n Proto is up to you.

**Comment by kentonv** [comment]
Ouch, we have https://github.com/capnproto/capnproto/blob/master/c++/src/kj/windows-sanity.h for problems like this, but I don't think there's a C++-namespace-friendly way to declare a qualifier. We might just have to #undef CONST there and hope that no one is using this silly alias in their own code...

**Comment by jredmondson** [comment]
In the short term, for us users of capnp, what is the best way to deal with this error right now on Windows? I don't see this remedied yet in the windows-sanity.h in source. Do we need to do a global search and replace of all CONST to CONST_ENUM or something like that within capnp until this is fixed? Undefining CONST seems very non-portable.

**Comment by jredmondson** [comment]
As an additional comment, to prevent problems like this in the future, wouldn't it be useful/better to prepend a CAPNP_ prefix to all enums like this so there's no chance that a portability issue like this might sprout up? E.g.

  enum Which: uint16_t {
    CAPNP_FILE,
    CAPNP_STRUCT,
    CAPNP_ENUM,
    CAPNP_INTERFACE,
    CAPNP_CONST,
    CAPNP_ANNOTATION,
  };

**Comment by jredmondson** [comment]
BTW, I can confirm that if you simply replace the 6 instances of this enum in schema.capnp.h, this did remove the errors for me.

Node::CONST->Node::CAPNP_CONST  is the easiest search and replace since CONST also appears in UNCONSTRAINED, which is used in the file. The only other replace is the enum value CONST within the Which enum.

**Comment by kentonv** [comment]
The easiest work-arounds are either:

1. Try to include windows.h *after* capnp headers.
2. Do `#undef CONST` after windows.h before including capnp headers.

The naming conventions have been debated many times before but the fact of the matter is we can't really change them this late in the game. It's not as easy as simply going around adding some prefixes as the file is generated code from `schema.capnp`.
