### ISSUE TITLE
Version mismatch between generated code and library headers.

### ISSUE THREAD

**Issue by crackcomm** [capnproto/capnproto#756]
I am trying to build [hugo-sandstorm](https://github.com/crackcomm/hugo-sandstorm/)  locally, I've updated dependencies but I can't get it to compile.

```sh
    default: In file included from tmp/sandstorm/web-session.capnp.c++:4:
    default: In file included from tmp/sandstorm/web-session.capnp.h:16:
    default: In file included from tmp/sandstorm/grain.capnp.h:18:
    default: tmp/sandstorm/powerbox.capnp.h:13:2: error: "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
    default: #error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
    default:  ^
```

I am using capnproto on `f73ac9f6667d7b87c395d23f3753dde63937cf00` and latest sandstorm (`240`) the code is here: https://github.com/crackcomm/hugo-sandstorm

**Comment by kentonv** [comment]
Hi Łukasz,

This is a likely problem with your build or your install, not with Cap'n Proto itself. The error indicates that you have multiple versions of Cap'n Proto installed, and somehow you're getting the `capnp` command-line tool from one version while the headers are coming from a different version.

Looking at your code, it appears you've changed `setup.sh` to download Cap'n Proto 0.6.0, whereas previously it was downloading and building from git master. I'm not sure if that's the cause of the problem, but either way I think you should probably change it back to using the version from git. In the Sandstorm ecosystem, the rule is generally to always use capnp from git master.

**Comment by crackcomm** [comment]
I will try to replicate it and report the errors but I suspect it would be solved with proper dependencies.

Is it possible that there is old standard library to build the new `kj` library? It was some templates error.

**Comment by kentonv** [comment]
Sorry, without the error message I have no idea what could have gone wrong.
