### ISSUE TITLE
How to detect the type from `FlatArrayMessageReader`

### ISSUE THREAD

**Issue by lecler-i** [capnproto/capnproto#783]
Hello,

I am trying to pass some messages to an other application, and don't find anyway to deduct the type of it !

For example if I have those :

```
struct Foo {
  x @0: Void;
}
struct Bar {
  y @0: Void;
}
```

Can I do some thing of the sort ?

```
void* data_ptr; // Some data I received
ssize_t data_size; // The size of the data

auto arr = kj::ArrayPtr<capnp::word const>(
            reinterpret_cast<capnp::word const *>(data_ptr),
            data_size / sizeof(capnp::word const *));

auto msgReader = capnp::FlatArrayMessageReader(arr);

// Pseudo code
if (msgReader.type() == Foo::type) {
  auto foo = msgReader.getRoot<Foo>();
} else if (msgReader.type() == Bar::type) {
  auto bar = msgReader.getRoot<Bar>();
}
```

I spent few hours searching trought source code and the closest solution I found is by using `DynamicStruct`, but for this I need to pass a `Schema`... but I have plenty of those...

Sorry I know it is not the best place for questions but I don't know where else to ask.

Thomas

**Comment by UnePierre** [comment]
Hi Thomas,

How about you marshal your type together with a Uint64 to store the SchemaId?
    Message : struct {
         type @0 : TypeId; // from schema.capnp
         content @1 : AnyPointer;
    }

(cellphone for texting, untested code)

This does the trick for me.
Good luck!
Max

**Comment by lecler-i** [comment]
Thanks for the suggestion, yes it would work like this !
But the type id isn't aldready included by `capnp` in the data ?

I tought so, looking at the generated files...

```
struct Foo {
  Foo() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c53e38397b6dc6fe, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};
```

**Comment by UnePierre** [comment]
No, this is a hen-and-egg problem: either you already know the type, then you also know the schemaId, or you know neither.
As far as I know, Capn'Proto does not transport the schema by itself, because of the overhead in situations where you already know it upfront.

**Comment by lecler-i** [comment]
All right, I got you !

Merci Max :-)

**Comment by kentonv** [comment]
Hi @lecler-i,

@UnePierre is right, the type ID is not transmitted with the message by default, because it is usually redundant. You can use his approach of sending a `TypeId` (aka `UInt64`) and an `AnyStruct`, or you can use a union:

    struct Message {
      union {
        foo @0 :Foo;
        bar @1 :Bar;
      }
    }

Usually, you know that your message is one of a small number of possibilities, in which case the union approach is better.
