### ISSUE TITLE
Mention brew package in install instructions

### ISSUE THREAD

**Issue by zoidbergwill** [capnproto/capnproto#784]
We should mention in the install instructions that `brew install capnp` is a possible way to install on MacOS X. 

I am happy to make a PR for this, mentioning it in [install.md](https://github.com/capnproto/capnproto/blob/master/doc/install.md)

**Comment by kentonv** [comment]
It looks like it already is mentioned in install.md? Under "Installation: Unix > From Package Managers"...

**Comment by zoidbergwill** [comment]
Ahhh, you're right. My bad, thanks. Sorry, I missed that. Added in https://github.com/capnproto/capnproto/commit/23ab833b226b08fee2349cdd9e04e8d91e2c7eeb
