### ISSUE TITLE
small-size data performance worse than protobuf

### ISSUE THREAD

**Issue by yunhua-deng** [capnproto/capnproto#790]
According to our experiments, if the size of the message is less than 256 bytes, cap'proto gets slower than protobuf in deserialization. Could it be the memory management overhead in deserilizing each message?

**Comment by kentonv** [comment]
Hi @yunhua-deng,

Can you provide the code of your benchmark?

Cap'n Proto can be deserialized without doing any memory allocations at all, whereas Protobuf generally requires quite a bit of allocation. I would have to see your code to understand why Cap'n Proto is not beating Protobuf in your case.

**Comment by yunhua-deng** [comment]
Hi @kentonv,

Actually, we are benchmarking the c-capnproto, and seeing that in deserilization there is some malloc overhead, https://github.com/opensourcerouting/c-capnproto/blob/master/tests/example-test.cpp#L98

For 4000000 messages with each of about 200 bytes in size, the serilization/deserilization times are as follows:
- protobuf: 650/750ms
- capnp: 280ms
- **c-capnp: 500/900ms**

**Comment by kentonv** [comment]
So it sounds like the issue is with c-capnproto specifically, and the C++ implementation is actually much faster? If so, I think you should file an issue on the c-capnproto project. It sounds like there's a missing optimization there. (But, I don't know anything about their code...)

**Comment by yunhua-deng** [comment]
Yes, I believe C++ implemetation is of deeply optimized! We have fired an issue in c project. FYI: https://github.com/opensourcerouting/c-capnproto/issues/31
