### ISSUE TITLE
Schema.capnp comments falsly claim that a generator request's `nodes` contain all parsed nodes

### ISSUE THREAD

**Issue by popham** [capnproto/capnproto#791]
To reduce verbosity of generics that I've been generating for Facebook's Flow static analyzer, I've been excluding generic types that don't get used (they exist on a `specialize` method, but not necessarily on class signatures). This means that to spec a generic return type I must examine that generic's nested nodes to decide which of the generic's parameters to include. Currently, however, the nested nodes of an imported generic are not necessarily part of the generator request's `nodes` list. I figured I would whine a little since this behavior contradicts the `nodes` comment:
>\# All nodes parsed by the compiler, including for the files on the command line and their
>\# imports.

More concretely, for the following pair of files `capnp compile -o - file1.capnp | capnp convert binary:text /path/to/schema.capnp CodeGeneratorRequest` excludes `file2.capnp:A.Inner` from its list of nodes.

```
@0xa41c6a846e102080; #file1.capnp

using import "file2.capnp".A;

struct B {
  b0 @0 :A;
}
```

```
@0xdf563878699d2a18; #file2.capnp

struct A(T) {
  struct Inner {
    i0 @0 :T;
  }
}
```

Is there any possibility that the `nodes` list can be expanded to include nodes like `file2.capnp:A.Inner`? Obviously I can compile file1.capnp and file2.capnp simultaneously to work around the issue, but I would rather not impose constraints beyond the compiler's.

**Comment by popham** [comment]
I just noticed https://groups.google.com/forum/#!searchin/capnproto/nestednodes%7Csort:date/capnproto/W0CgGgUMLlw/5i6VbdgiAQAJ. The behavior is expected :(

**Comment by kentonv** [comment]
Yeah, sorry, this is indeed indended behavior. In theory the presence of a nested type should not affect anything about the outer type, unless the outer type also uses the nested type in some way (e.g. as the type of a field).

What's the benefit of excluding unused type parameters, exactly?

**Comment by popham** [comment]
* Given two classes with (1) differing unused type parameters and (2) identical used type parameters, they both type check as equivalent. This avoids some error prone unsafe casting.
* A parameter that doesn't get used at all gets flagged by linters.
* It reduces verbosity. I'm flattening nested classes down to module-scoped classes, e.g. `A.B.C` -> `A_B_C__InstanceR`, `A_B_C__CtorR`, and possibly `A_B_C__GenericR<...>`. I expose a user friendly interface with an `A.B.C` lookup, but anytime a user wants to export a value under Flow that user needs to spec its type. With each of my parameters growing to 2 parameters under readers and 3 parameters under builders, I worry that the verbosity of these type names plus every parameter from the type's ancestors will impact schema designs. (Each parameter expands to 2 parameters for my readers and 3 parameters for my builders because Flow doesn't have a useful class-scoped typedef, e.g. [test/generic/schema.capnp](https://github.com/capnp-js/builder-core/blob/66c3035d55e08b1a37b0d80ea89b9c568c591289/test/generic/schema.capnp#L10) becomes [test/generic/schema.capnp-b.js](https://github.com/capnp-js/builder-core/blob/66c3035d55e08b1a37b0d80ea89b9c568c591289/test/generic/schema.capnp-b.js#L256)).

**Comment by kentonv** [comment]
It seems to me that if the developer has added a totally-unused type parameter to their schema, they probably had some purpose in mind for it, and having the compiler silently remove it is probably not what they actually want. If they really want it removed, they can explicitly do so.

Are you seeing actual use cases where unused type parameters are present, and removing them seems like what the developer would want?

**Comment by popham** [comment]
Unused parameters show up on a `specialize` signature even if none of the parameters get used. I wouldn't describe this as "silently remove[d]." I expect that among JavaScript development pipelines that include Flow, 99% also include a linter that will cry foul until the parameter is removed or the lint error is explicitly waived.

Given the verbosity that comes with including unused parameters, I feel that the compelling-use-case burden falls on developers that want them included. On builders, 1 schema parameter maps to 3 Flow parameters. 3 schema parameters? That's 9 Flow parameters. Even as currently implemented, many developers will avoid exporting generics because of this verbosity. I feel confidant that these developers will easily eclipse the developers with totally-unused type parameters.

As implemented, I do anticipate this divergence from c++'s scoping to cause a bit of difficulty in navigating across languages, but not too much difficulty.

**Comment by kentonv** [comment]
Have you observed schemas is the wild that have totally-unused type parameters? I'm struggling to imagine why anyone would ever do this, and if no one ever does it, then it seems like no solution is needed?

**Comment by popham** [comment]
The problem is more general than the "totally-unused" case (if a parent scope's parameter goes unused in some subscope, then why include that parameter among the subscope's parameters?), but I'm starting to get that feeling where I've been banging my head against the wall trying to prove a false proposition. I'm having a much easier time arguing your position. I'll switch it to bind all parameters.

**Comment by popham** [comment]
Zoiks! Including all of the type parameters increased Flow's analysis time from 29s to 3m 57s on my [test schema](https://gist.github.com/popham/d3300db02264a04bad2dd5cc998957bb). These analysis times come from a synchronous Flow call, but Flow also provides a server that retains a lot of state, thereby reducing analysis time. I'll stick with all of the parameters for now, but I anticipate possibly going back to my goofy BS.
