### ISSUE TITLE
AddressBook example throwing exception for 300M rows

### ISSUE THREAD

**Issue by snjvss11** [capnproto/capnproto#796]
Hi,

I just compiled and ran Addressbook example with 300M rows. Writing the message looks to be fine but read message is throwing exception wordsPerElement <= wordCount; INLINE_COMPOSITE list's elements overrun its word count" . I tried seeing the number of segments created and it always shows 4. Can you help me out on this. Is there any way i can put 500M or 1B rows in a single list?

Thanks

**Comment by snjvss11** [comment]
Here is  a write method:
void writeAddressBook(int fd) 
{
  ::capnp::MallocMessageBuilder message;

  AddressBook::Builder addressBook = message.initRoot<AddressBook>();
  std::cout << " Enter the numbe rof records to form message " << std::endl;
  long loopcount =0;
  std::cin >> loopcount;
  
  ::capnp::List<Person>::Builder people = addressBook.initPeople(loopcount);
  for ( long i =0 ;i<loopcount;i++){

  Person::Builder alice = people[i];
  alice.setId(123);
  alice.setName("Alice");
  alice.setEmail("alice@example.com");
  ::capnp::List<Person::PhoneNumber>::Builder alicePhones =
      alice.initPhones(1);
  alicePhones[0].setNumber("555-1212");
  alicePhones[0].setType(Person::PhoneNumber::Type::MOBILE);
  alice.getEmployment().setSchool("MIT");
  }
  /*
  Person::Builder bob = people[1];
  bob.setId(456);
  bob.setName("Bob");
  bob.setEmail("bob@example.com");
  auto bobPhones = bob.initPhones(2);
  bobPhones[0].setNumber("555-4567");
  bobPhones[0].setType(Person::PhoneNumber::Type::HOME);
  bobPhones[1].setNumber("555-7654");
  bobPhones[1].setType(Person::PhoneNumber::Type::WORK);
  bob.getEmployment().setUnemployed();
 */
 
  writePackedMessageToFd(fd, message);
}

**Comment by snjvss11** [comment]
Here is the read method:
void printAddressBook(int fd) {
  ::capnp::PackedFdMessageReader message(fd);

  AddressBook::Reader addressBook = message.getRoot<AddressBook>();

  for (Person::Reader person : addressBook.getPeople()) {
    std::cout << person.getName().cStr() << ": "
              << person.getEmail().cStr() << std::endl;
    for (Person::PhoneNumber::Reader phone: person.getPhones()) {
      const char* typeName = "UNKNOWN";
      switch (phone.getType()) {
        case Person::PhoneNumber::Type::MOBILE: typeName = "mobile"; break;
        case Person::PhoneNumber::Type::HOME: typeName = "home"; break;
        case Person::PhoneNumber::Type::WORK: typeName = "work"; break;
      }
      std::cout << "  " << typeName << " phone: "
                << phone.getNumber().cStr() << std::endl;
    }
    Person::Employment::Reader employment = person.getEmployment();
    switch (employment.which()) {
      case Person::Employment::UNEMPLOYED:
        std::cout << "  unemployed" << std::endl;
        break;
      case Person::Employment::EMPLOYER:
        std::cout << "  employer: "
                  << employment.getEmployer().cStr() << std::endl;
        break;
      case Person::Employment::SCHOOL:
        std::cout << "  student at: "
                  << employment.getSchool().cStr() << std::endl;
        break;
      case Person::Employment::SELF_EMPLOYED:
        std::cout << "  self-employed" << std::endl;
        break;
    }
  }
}

**Comment by kentonv** [comment]
The maximum segment size is 4GB, which means that this is also the maximum physical size of any one object (such as a list). A single `Person` is 40 bytes, so 300M `Person`s would be ~12GB, exceeding the limit. Unfortunately this is a fundamental limitation of Cap'n Proto's wire format. You will need to split very large lists into multiple pieces.

With that said, this really ought to throw at write time, in addition to read time, so I'll leave this bug open for that.

**Comment by snjvss11** [comment]
Hi,

Thanks for the info.
I tried making it a lists of list approach as below:

struct PersonList{
        peoples @0 :List(Person);
}
struct AddressBook {
  people @0 :List(PersonList);
}
 I am doing write as  below:
 AddressBook::Builder addressBook = message.initRoot<AddressBook>();
  long loopcount = 100000000
long perlistcount = 100;
  int total_list = loopcount/perlistcount;
  ::capnp::List<PersonList>::Builder peoples = addressBook.initPeople(total_list);
  for ( int i=0;i<total_list;i++){
        PersonList::Builder persons = peoples[i];
        ::capnp::List<Person>::Builder people = persons.initPeoples(perlistcount);
  for ( long i =0 ;i<perlistcount;i++){

  Person::Builder alice = people[i];
  alice.setId(123);
  alice.setName("Alice");
  alice.setEmail("alice@example.com");
  ::capnp::List<Person::PhoneNumber>::Builder alicePhones =
      alice.initPhones(1);
  alicePhones[0].setNumber("555-1212");
  alicePhones[0].setType(Person::PhoneNumber::Type::MOBILE);
  alice.getEmployment().setSchool("MIT");
  }
  }
 writePackedMessageToFd(fd, message);

And reading it like:
  ::capnp::PackedFdMessageReader message(fd);//,opt);

  AddressBook::Reader addressBook = message.getRoot<AddressBook>();

  for (PersonList::Reader persons : addressBook.getPeople()) {
        for ( Person::Reader person : persons.getPeoples()){
    std::cout << person.getName().cStr() << ": "
              << person.getEmail().cStr() << std::endl;
}
}

For 100M rows:
If I make the number of items per list as 100 , it works fine. But if I make # of items per list as 1000 it doesnt work. I am seeing more number of rows in my file and the program runs indefinitely in the for loop. Can you suggest where its going wrong.
For 150M it doesnt work at all. 
Thanks

**Comment by kentonv** [comment]
Is it the read loop or the write loop that doesn't work?

Note that using "packed" format means you can't mmap() the file and therefore can't do random access. For very large files, random access is usually important and so you should avoid packed format.

FWIW, you can also do List(List(Person)). The intermediate PersonList isn't necessary.

**Comment by kentonv** [comment]
I'm not able to reproduce this. When I try to allocate an oversized struct list, I get an exception like "total size of struct list is larger than max segment size".
