### ISSUE TITLE
pwritev doesn't compile pass on android platform

### ISSUE THREAD

**Issue by faywong** [capnproto/capnproto#800]
in filesystem-disk-unix.c++

```c++
      KJ_SYSCALL(n = pwritev(fd, iov.begin(), count, offset));
```
there's in only pwrite available in android ndk.

**Comment by kentonv** [comment]
Odd. I test every release on Android. Are you building from the latest release (0.7) or from git master?

**Comment by faywong** [comment]
from release(0.7)

**Comment by 9468305** [comment]
In `~/Android/sdk/ndk-bundle/sysroot/usr/include/sys/uio.h`, 
```
#if defined(__USE_GNU)

#if __ANDROID_API__ >= 24
ssize_t preadv(int __fd, const struct iovec* __iov, int __count, off_t __offset) __RENAME_IF_FILE_OFFSET64(preadv64) __INTRODUCED_IN(24);
ssize_t pwritev(int __fd, const struct iovec* __iov, int __count, off_t __offset) __RENAME_IF_FILE_OFFSET64(pwritev64) __INTRODUCED_IN(24);
ssize_t preadv64(int __fd, const struct iovec* __iov, int __count, off64_t __offset) __INTRODUCED_IN(24);
ssize_t pwritev64(int __fd, const struct iovec* __iov, int __count, off64_t __offset) __INTRODUCED_IN(24);
#endif /* __ANDROID_API__ >= 24 */

#endif
```

`sys/uio.h` is included by `fcntl.h`, which is included by `filesystem-disk-unix.c++` Line 33.

I suggest you run build with higher `__ANDROID_API__` and run compatibility tests with lower devices.

**Comment by kentonv** [comment]
I'd be happy to accept a pull request which adds `|| (defined(__ANDROID_API__) && __ANDROID_API__ < 24)` to this `#if`:

https://github.com/capnproto/capnproto/blob/2500a628f0c834a6ff847138a6ef193a35efa3c3/c++/src/kj/filesystem-disk-unix.c++#L397-L401
