### ISSUE TITLE
Install location of json.capnp

### ISSUE THREAD

**Issue by keldu** [capnproto/capnproto#801]
Building and installing the current 0.7.0 release files from capnproto.org on debian buster(probably also on  stretch and others) results in json.capnp being installed in /usr/local/include/capnp/json.capnp instead of /usr/local/include/capnp/compat/json.capnp

**Comment by keldu** [comment]
Maybe I should elaborate on this.

json.capnp.h is installed in the compat folder, so if I build a protocol using the json.capnp file, the generated headers will try to include /usr/include/capnp/json.capnp.h which is in the compat folder.
In the source json.capnp is located in the compat folder, so I would suggest to fix this in the build process

**Comment by kentonv** [comment]
Yes, this appears to be a bug -- not in the cmake build, but in the autotools build. (The cmake build is an alternative that is not the primary build system.)

**Comment by kentonv** [comment]
Thanks for the report! I guess this is tricky to fix in a patch release since it could break people who have inadvertently become dependent on json.capnp being where it is...

**Comment by keldu** [comment]
You're right. I wouldn't try to fix this in 0.7.0. It's not impossible though, you could release a 0.7.1 version, but maybe it's not worth the hassle. 

I'm just building my own jsonrpc 2.0 protocol implementation and I must admit that it took me way too long to realize what the problem was. Other people may run into the same problem.

**Comment by kentonv** [comment]
Oh hey, you might want to check out the latest code in git. There's the beginnings of a JSON-RPC implementation there already:

https://github.com/capnproto/capnproto/tree/master/c++/src/capnp/compat

**Comment by kentonv** [comment]
Fixed by #960 (not released yet).
