### ISSUE TITLE
Parse error on simple example

### ISSUE THREAD

**Issue by EternalDeiwos** [capnproto/capnproto#803]
I'm getting a `Parse error` when attempting to compile this file -- the error complains at the struct definition (line 3).

```capnp

@0xe325a03d52f6b824

struct Test {
  prop @0 :Text;
}
```

This is running version `0.7.0` on MacOS and my installation was straight forward and uneventful.

Any ideas what I'm doing/did wrong?

**Comment by keldu** [comment]
I think your id "@0xe325a03d52f6b824" is supposed to have a semicolon at the end. "@0xe325a03d52f6b824;" should do the trick.

**Comment by EternalDeiwos** [comment]
That did the trick thanks 😅.
