### ISSUE TITLE
MinGW64 build fails

### ISSUE THREAD

**Issue by sparkchaser** [capnproto/capnproto#813]
I attempted to build capnproto (v0.7.0 from the release archive, and build d4d9700 from the repo) on Win 10 using [MinGW64](https://mingw-w64.org).  I compiled using the instructions on capnproto.org/install.html, both the "from release tarball" and the "from git" versions.  Every time, the build failed with the following errors:

```
/bin/sh ./libtool  --tag=CXX   --mode=link g++ -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR='"/mingw32/include"' -mthreads -O2 -DNDEBUG -mthreads -mthreads  -o capnp.exe src/capnp/compiler/module-loader.o src/capnp/compiler/capnp.o libcapnpc.la libcapnp-json.la libcapnp.la libkj.la
./.libs/lt-capnpc-c++.c: In function 'main':
./.libs/lt-capnpc-c++.c:319:16: warning: implicit declaration of function '_spawnv'; did you mean 'spawnv'? [-Wimplicit-function-declaration]
   rval = (int) _spawnv (_P_WAIT, lt_argv_zero, (const char * const *) newargz);
                ^~~~~~~
                spawnv
/tmp/ccWQvPfh.o:lt-capnpc-c++.c:(.text.startup+0x4a1): undefined reference to `_spawnv'
/tmp/ccWQvPfh.o:lt-capnpc-c++.c:(.text.startup+0x4a1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_spawnv'
collect2: error: ld returned 1 exit status
strip: './capnpc-c++.exe': No such file
./libtool: line 11135: ./capnpc-c++.exe: No such file or directory
libtool: link: g++ -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/mingw32/include\" -mthreads -O2 -DNDEBUG -mthreads -mthreads -o .libs/capnp.exe src/capnp/compiler/module-loader.o src/capnp/compiler/capnp.o  ./.libs/libcapnpc.dll.a ./.libs/libcapnp-json.dll.a /c/tools/capnproto-tools-win32-0.7.0/src/c++/.libs/libcapnp.dll.a ./.libs/libcapnp.dll.a /c/tools/capnproto-tools-win32-0.7.0/src/c++/.libs/libkj.dll.a ./.libs/libkj.dll.a -mthreads -L/mingw32/lib
./.libs/lt-capnp.c: In function 'main':
./.libs/lt-capnp.c:319:16: warning: implicit declaration of function '_spawnv'; did you mean 'spawnv'? [-Wimplicit-function-declaration]
   rval = (int) _spawnv (_P_WAIT, lt_argv_zero, (const char * const *) newargz);
                ^~~~~~~
                spawnv
/tmp/cc2wkl7h.o:lt-capnp.c:(.text.startup+0x4a1): undefined reference to `_spawnv'
/tmp/cc2wkl7h.o:lt-capnp.c:(.text.startup+0x4a1): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_spawnv'
collect2: error: ld returned 1 exit status
strip: './capnp.exe': No such file
./libtool: line 11135: ./capnp.exe: No such file or directory
echo capnp.exe capnpc-c++.exe src/capnp/test.capnp src/capnp/test-import.capnp src/capnp/test-import2.capnp src/capnp/compat/json-test.capnp | (read CAPNP CAPNPC_CXX SOURCES && ./$CAPNP compile --src-prefix=./src -o./$CAPNPC_CXX:src -I./src $SOURCES)
/bin/sh: ./capnp.exe: No such file or directory
make: *** [Makefile:4325: test_capnpc_middleman] Error 127
```

Both of these .c files are auto-generated.  When I modified the files /c++/libtool and /c++/build-aux/ltmain.sh and replaced `_spawnv` with `spawnv`, everything appears to build successfully.  Both of *these* files are also auto-generated, so something must not be getting detected correctly for this platform.

My platform:
```
$ uname -a
MINGW32_NT-10.0 sparkchaser 2.11.2(0.329/5/3) 2018-11-26 09:22 x86_64 Msys

$ gcc --version
gcc (GCC) 7.4.0
```

**Comment by kentonv** [comment]
Those files are generated by libtool. It seems like there is some incompatibility between libtool and MinGW. Unfortunately, this is not something that Cap'n Proto itself can fix. I honestly have not been able to get MinGW+libtool to work. When targeting MinGW, I always disable libtool by disabling building shared libraries:

    ./configure --disable-shared

This builds static libraries only, not DLLs.

Sorry, that's all we support with MinGW right now. If someone figures out how to make DLLs work I'm happy to accept a PR.

You can also try using cmake instead of autoconf, but I don't know if that builds DLLs either.

**Comment by sparkchaser** [comment]
I recommend adding that information to the install instructions, I'm likely not the only one with that problem.

Since I was able to work around the problem with a one-character change, hopefully somebody out there who knows libtool well can recommend a solution.

**Comment by sfhacker** [comment]
@sparkchaser Any news/update about this long standing issue?

![image](https://user-images.githubusercontent.com/25817529/92317328-ba295480-f042-11ea-910e-73bea2544d4c.png)

**Comment by sparkchaser** [comment]
Sorry, my autotools knowledge is very limited so I never was able to get
this working reliably.  If your license is compatible you can build a
static library as mentioned above.  Otherwise, on a Windows platform I
think your best bet is to use Visual Studio instead of MinGW, unfortunately.

I never tried building inside the WSL.  I expect that would work as well as
an Ubuntu build would, but I think the resulting program would require the
user to have WSL installed.

**Comment by sfhacker** [comment]
The question is ... how did you resolve this issue? Can you post here how you fixed your issue?

**Comment by sfhacker** [comment]
We use MinGW to build large projects from source all the time! We have had no issues so far!
We also use libtool every day, including to build capnproto.

![image](https://user-images.githubusercontent.com/25817529/92332829-de794580-f0c3-11ea-8156-cf736a26c253.png)

@sparkchaser Are you using some binary downloaded from the Internet?

**Comment by sparkchaser** [comment]
I didn't.  My original post lists an edit that I made to an auto-generated
file that avoided the compiler error, but it's a hacky manual step that
makes your overall build process complicated.  That was the only thing
resembling a fix or workaround that I was ever able to find.  The project I
was working on at the time was cancelled, so I didn't need the library any
more and stopped looking into it.  I think the only way to find a real
solution will be to find someone with real experience in autotools.

**Comment by sparkchaser** [comment]
This was over a year ago, but IIRC I was using the latest source downloaded
directly from GitHub.  I was also using MinGW 64, not the 32-bit version,
which (again IIRC) yielded different results.

**Comment by kentonv** [comment]
> If your license is compatible you can build a static library as mentioned above.

FWIW, Cap'n Proto is MIT-licensed, which makes it compatible with just about everything. There should be no legal problem with static linking.

Actually, static linking may be necessary on Windows as we have not added dllimport/dllexport qualifiers to our interfaces. I'm not sure if "export all" is an option on Windows the way it is on most other platforms.

**Comment by sfhacker** [comment]
I reckon this long standing open ticket should be closed at once!

All the best.

**Comment by kentonv** [comment]
@sfhacker I don't really understand you. Earlier in the thread you were asking for a solution to this issue, but now it sounds like you're saying it's fixed? Your tone is weird.

I did just try it and it does in fact appear that DLL building with libtool is working now, so I suppose we should indeed close this.
