### ISSUE TITLE
clang 8 build falied

### ISSUE THREAD

**Issue by chronoxor** [capnproto/capnproto#815]
clang 8 build failed with error:
```
[ 15%] Building CXX object modules/capnproto/c++/src/kj/CMakeFiles/kj.dir/encoding.c++.o
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/encoding.c++:242:19: error: no matching conversion for functional-style cast from 'const char8_t [4]' to 'kj::StringPtr'
    result.addAll(StringPtr(u8"\ufffd"));
                  ^~~~~~~~~~~~~~~~~~~~
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:70:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const char8_t [4]' to 'const kj::StringPtr' for 1st argument
class StringPtr {
      ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:70:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const char8_t [4]' to 'kj::StringPtr' for 1st argument
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:73:10: note: candidate constructor not viable: no known conversion from 'const char8_t [4]' to 'decltype(nullptr)' (aka 'nullptr_t') for 1st argument
  inline StringPtr(decltype(nullptr)): content("", 1) {}
         ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:74:10: note: candidate constructor not viable: no known conversion from 'const char8_t [4]' to 'const char *' for 1st argument
  inline StringPtr(const char* value): content(value, strlen(value) + 1) {}
         ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:141:20: note: candidate constructor not viable: no known conversion from 'const char8_t [4]' to 'ArrayPtr<const char>' for 1st argument
  inline constexpr StringPtr(ArrayPtr<const char> content): content(content) {}
                   ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:499:19: note: candidate constructor not viable: no known conversion from 'const char8_t [4]' to 'const kj::String' for 1st argument
inline StringPtr::StringPtr(const String& value): content(value.cStr(), value.size() + 1) {}
                  ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:83:10: note: candidate template ignored: substitution failure [with T = char8_t [4]]: no matching function for call to 'instance'
  inline StringPtr(const T& t): StringPtr(t.c_str()) {}
         ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:72:10: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  inline StringPtr(): content("", 1) {}
         ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:75:10: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
  inline StringPtr(const char* value, size_t size): content(value, size + 1) {
         ^
/home/travis/build/chronoxor/CppSerialization/modules/capnproto/c++/src/kj/string.h:78:10: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
  inline StringPtr(const char* begin, const char* end): StringPtr(begin, end - begin) {}
         ^
1 error generated.
modules/capnproto/c++/src/kj/CMakeFiles/kj.dir/build.make:257: recipe for target 'modules/capnproto/c++/src/kj/CMakeFiles/kj.dir/encoding.c++.o' failed
make[2]: *** [modules/capnproto/c++/src/kj/CMakeFiles/kj.dir/encoding.c++.o] Error 1
```

**Comment by kentonv** [comment]
Hi Ivan,

We use Clang 8 every day. More likely this is an issue with the target platform, which seemingly defines `char8_t` differently than others. What OS / platform was this on?

**Comment by chronoxor** [comment]
My Travis-CI config for clang 8 is the following:

```
    - os: linux
      compiler: clang
      env: OS=linux COMPILER=clang CLANG_VERSION=8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libstdc++-8-dev
            - cmake
```

**Comment by kentonv** [comment]
What CPU architecture?

**Comment by chronoxor** [comment]
linux/amd64

![image](https://user-images.githubusercontent.com/4397805/55735576-41c3fb80-5a2a-11e9-9c7c-8560f1aad649.png)

**Comment by kentonv** [comment]
Hmm, not sure what to say. I compile this code on clang8/linux/amd64 every day.

Were you building from git master or from a release?

**Comment by chronoxor** [comment]
I build from git master. Yesterday I moved linux x64 build from clang 7 to clang 8 on my Travis-CI and found the issue. I can prepare a PR with clang 8 setup in capnproto .travis.yml and will check if it reproduce.

**Comment by harrishancock** [comment]
It looks like `char8_t` is a C++20 feature: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0482r6.html

Apparently it is a backwards-incompatible change:

> Under this proposal, UTF-8 string literals no longer bind to references to array of type const char nor do they implicitly convert to pointer to const char.

**Comment by chronoxor** [comment]
See PR with Travis-CI build for clang 8: https://github.com/capnproto/capnproto/pull/816

**Comment by chronoxor** [comment]
> It looks like `char8_t` is a C++20 feature: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0482r6.html

Yes, I also experiment with CMAKE_CXX_STANDARD 20

**Comment by harrishancock** [comment]
FWIW, I can reproduce locally with `-std=c++2a`.

**Comment by kentonv** [comment]
I'm shocked that they can just go and make a backwards-incompatible change like that.

I guess some `reinterpret_cast`s are needed?

**Comment by harrishancock** [comment]
Maybe `kj::String/Ptr` needs a new constructor, behind an `#if defined(__cpp_char8_t)`. As I recall, it is implied that `kj::String`s refer to UTF-8-encoded data, correct? That is exactly the use case of `char8_t` -- to represent UTF-8 data.

Quite the mess, though. More background here: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r0.html

**Comment by kentonv** [comment]
Yeah sounds like we should accept char8_t to String and StringPtr, and reinterpret_cast them to char*...

**Comment by swamp-agr** [comment]
According to [**char8_t backward compatibility remediation**](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r0.html) I tried to implement `reintrerpret_cast` case:

<img width="898" alt="Screenshot 2020-05-12 at 18 16 44" src="https://user-images.githubusercontent.com/6595049/81711898-be6ea800-947c-11ea-92ef-8c6db23029e8.png">

File [encoding.c++:242](https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/kj/encoding.c%2B%2B#L242) was changed:
```
-    result.addAll(StringPtr(u8"\ufffd"));
+    result.addAll(StringPtr(reinterpret_cast<const char *>(u8"\ufffd")));
```

It works for me!

**Comment by kentonv** [comment]
@swamp-agr Care to submit a PR? Maybe we could roll this into a 0.8.1 release.

**Comment by swamp-agr** [comment]
Sounds good! Please expect PR any time soon!

**Comment by swamp-agr** [comment]
#1002 PR created!
