### ISSUE TITLE
Web site claims GCC 4.8 is sufficient, but GCC 4.9 is actually required

### ISSUE THREAD

**Issue by redmouth** [capnproto/capnproto#822]
configure: error: *** A compiler with support for C++14 language features is required.

g++ (Ubuntu 4.8.5-4ubuntu2) 4.8.5
os: ubuntu 16.04

**Comment by kentonv** [comment]
I think this is a documentation bug: The code (`c++/src/kj/common.h`) explicitly requires GCC 4.9, but the web page still claims GCC 4.8 is enough. You will need to upgrade to a newer compiler.

**Comment by stroucki** [comment]
Think it would be too hard to perhaps change the web site?

**Comment by kentonv** [comment]
@stroucki Sorry, forgot about this. Fixed now.
