### ISSUE TITLE
Can I use capnpc_c++ directly?

### ISSUE THREAD

**Issue by luxe** [capnproto/capnproto#823]
**problem:**
I want to build the captnproto compiler from source and then use it within my own project.
However, based on my build system, I don't think I can run binaries that call other binaries (which I believe is how `capnp` works).  `capnp` calls another binary? (i.e. the plugins `-oc++`).  
I'm wondering if there is a way to either use the plugin directly, or make the `capnp` stand-alone in not needing to call other binaries/plugins.  I'm also not entirely sure how the plugin works as a standalone tool, because the cli arguments look minimal.

**what I've done so far:**
While referencing the CMake build files, I wrote similar rules for [bazel](https://bazel.build/).  

It looks like this:
https://github.com/Unilang/unilang/blob/master/source/bazel/deps/build_files/captnproto.BUILD

I'm able to build the tool from source and run it within bazel's sandbox:  
```
./user_run @captnproto//:capnp_tool -- compile --help                                                                                 
INFO: Analysed target @captnproto//:capnp_tool (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @captnproto//:capnp_tool up-to-date:
  bazel-bin/external/captnproto/capnp_tool
INFO: Elapsed time: 0.354s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Usage: /home/thickey/.cache/bazel/_bazel_thickey/aa5b36515f1642402b9c7c4b6e735cad/execroot/__main__/bazel-out/k8-fastbuild/bin/external/captnproto/capnp_tool compile [<option>...] <source>...

Compiles Cap'n Proto schema files and generates corresponding source code in one
or more languages.

Options:
    -I<dir>, --import-path=<dir>
        Add <dir> to the list of directories searched for non-relative imports
        (ones that start with a '/').
    --no-standard-import
        Do not add any default import paths; use only those specified by -I.
        Otherwise, typically /usr/include and /usr/local/include are added by
        default.
    -o<lang>[:<dir>], --output=<lang>[:<dir>]
        Generate source code for language <lang> in directory <dir> (default:
        current directory).  <lang> actually specifies a plugin to use.  If
        <lang> is a simple word, the compiler searches for a plugin called
        'capnpc-<lang>' in $PATH.  If <lang> is a file path containing slashes,
        it is interpreted as the exact plugin executable file name, and $PATH is
        not searched.  If <lang> is '-', the compiler dumps the request to
        standard output.
    --src-prefix=<prefix>
        If a file specified for compilation starts with <prefix>, remove the
        prefix for the purpose of deciding the names of output files.  For
        example, the following command:
            capnp compile --src-prefix=foo/bar -oc++:corge foo/bar/baz/qux.capnp
        would generate the files corge/baz/qux.capnp.{h,c++}.
    --verbose
        Log informational messages to stderr; useful for debugging.
    --version
        Print version information and exit.
    --help
        Display this help text and exit.
```

I'm stuck trying to decide if I should use the c++ plugin directly to compile files (not sure if that's possible), or if I need to try to do something so bazel binaries can call other binaries in the same sandbox.   
Any suggestions?

**Comment by kentonv** [comment]
I'd be very surprised if Bazel doesn't give you a way to make this work. Many build tools are actually binaries that execute other binaries. For example, GCC invokes the C++ front-end and linker as separate binaries. Also, any kind of shell script would of course invoke other binaries.

With that said, if you really have to, you can split this into two steps like:

    capnp compile -o- my-schema.capnp > my-schema.intermediate
    capnp-c++ < my-schema.intermediate

The trick here is that `-o-` causes `capnp compile` to output the "code generator request" to standard output rather than invoking a plugin. The plugin expects to read a code generator request on standard input.

Note that if you want the generated files to be placed in a particular directory, you need to cd to that directory before invoking capnp-c++.

(Closing this because there's no action item for us, I think...)

**Comment by luxe** [comment]
thanks for the ideas. yea, I'll try figure out how to get binaries to call binaries in bazel

**Comment by luxe** [comment]
for anyone interested, I took the approach of creating temporary files (suggested by the author) and moving them to the right place.  This seemed easier than having programs call programs.  
The rules look as followed:

```
def capnp_to_intermediate(name,deps=[]):

    #the file names to use
    target_name = name + "_capnp_intermediate"
    explicit_input_file = name + ".capnp"
    explicit_result_file = name + ".capnp_intermediate"
    
    #converting hcp to hpp/cpp
    native.genrule(
        name = target_name,
        srcs = [explicit_input_file],
        outs = [explicit_result_file],
        tools = ["@captnproto//:capnp_tool"],
        cmd = """
    $(location @captnproto//:capnp_tool) compile -o- $(SRCS) > $(OUTS)
        """
    )

def intermediate_to_cpp(name,deps=[]):

    #the file names to use
    target_name = name + "_capnp"
    explicit_input_file = name + ".capnp_intermediate"
    explicit_result_h_file = name + ".capnp.h"
    explicit_result_cpp_file = name + ".capnp.c++"
    
    #converting hcp to hpp/cpp
    native.genrule(
        name = target_name,
        srcs = [explicit_input_file],
        outs = [explicit_result_h_file,explicit_result_cpp_file],
        tools = ["@captnproto//:capnpc_cpp"],
        output_to_bindir = False,
        cmd = """
    $(location @captnproto//:capnpc_cpp) < $(SRCS);
    cp -r code $(GENDIR)
        """
    )
```
