### ISSUE TITLE
Building on OpenBSD fails with undeclared identifier 'aligned_alloc'

### ISSUE THREAD

**Issue by pwrdwnsys** [capnproto/capnproto#833]
Build fails on OpenBSD 6.5 (release/amd64) with system default clang++ 7.0.1 (perhaps similar to #743?). Invoked configure as `./configure CC=clang++ CXX=clang++` owing to old g++ in OpenBSD base.

```
src/kj/table.c++:310:7: error: use of undeclared identifier 'aligned_alloc'
      aligned_alloc(sizeof(BTreeImpl::NodeUnion), newCapacity * sizeof(BTreeImpl::NodeUnion)));
      ^
1 error generated.
*** Error 1 in target 'src/kj/table.lo'
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -O2 -DNDEBUG -DKJ_HAS_OPENSSL -MT src/kj/string-tree.lo -MD -MP -MF src/kj/.deps/string-tree.Tpo -c src/kj/string-tree.c++ -o src/kj/string-tree.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -O2 -DNDEBUG -DKJ_HAS_OPENSSL -MT src/capnp/layout.lo -MD -MP -MF src/capnp/.deps/layout.Tpo -c src/capnp/layout.c++ -o src/capnp/layout.o >/dev/null 2>&1
*** Error 1 in /home/pwrdwnsys/tmp/capnproto-c++-0.7.0 (Makefile:2295 'src/kj/table.lo')
```

**Comment by kentonv** [comment]
I guess you'll need to add OpenBSD to the ifdef here:

https://github.com/capnproto/capnproto/blob/ca7565ece1ba6dbb384d9e8f63ae1169dde60d4e/c++/src/kj/table.c++#L291

I'm happy to accept a PR if it works.

**Comment by pwrdwnsys** [comment]
Thanks for the quick response! I added `__OpenBSD__` to the ifdef. I installed automake-1.16.1, autoconf-2.69p2, and libtool-2.4.2p0 packages and did the following:
```shell
export AUTOCONF_VERSION=2.69
export AUTOMAKE_VERSION=1.16
export LIBTOOL=/usr/local/bin/libtool
./configure CC=clang CXX=clang++
```
The build got further then failed with:
```
/bin/sh ./libtool  --tag=CXX    --mode=link clang++ -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR='"/usr/local/include"' -pthread  -O2 -DNDEBUG -pthread -DKJ_HAS_OPENSSL -release \([.][0-9]*\)*\(-.*\)*$/\1\3/g') -no-undefined  -o libkj.la -rpath /usr/local/lib src/kj/common.lo src/kj/units.lo  src/kj/memory.lo src/kj/refcount.lo src/kj/array.lo  src/kj/string.lo src/kj/string-tree.lo src/kj/hash.lo  src/kj/table.lo src/kj/encoding.lo src/kj/exception.lo  src/kj/debug.lo src/kj/arena.lo src/kj/io.lo src/kj/mutex.lo  src/kj/thread.lo src/kj/time.lo src/kj/filesystem.lo  src/kj/filesystem-disk-unix.lo src/kj/filesystem-disk-win32.lo  src/kj/test-helpers.lo src/kj/main.lo src/kj/parse/char.lo -lpthread -lpthread
/bin/sh: no closing quote
*** Error 1 in target 'libkj.la'
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -pthread -O2 -DNDEBUG -pthread -DKJ_HAS_OPENSSL -MT src/capnp/compiler/compiler.lo -MD -MP -MF src/capnp/compiler/.deps/compiler.Tpo -c src/capnp/compiler/compiler.c++ -o src/capnp/compiler/compiler.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -pthread -O2 -DNDEBUG -pthread -DKJ_HAS_OPENSSL -MT src/capnp/compiler/node-translator.lo -MD -MP -MF src/capnp/compiler/.deps/node-translator.Tpo -c src/capnp/compiler/node-translator.c++ -o src/capnp/compiler/node-translator.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/usr/local/include\" -pthread -O2 -DNDEBUG -pthread -DKJ_HAS_OPENSSL -MT src/capnp/compiler/parser.lo -MD -MP -MF src/capnp/compiler/.deps/parser.Tpo -c src/capnp/compiler/parser.c++ -o src/capnp/compiler/parser.o >/dev/null 2>&1
*** Error 1 in /home/pwrdwnsys/building/capnproto/c++ (Makefile:1913 'libkj.la')
```
I compared the libtool command line with the [SO_VERSION pattern from Makefile.am](https://github.com/capnproto/capnproto/blob/c9b926305330357a41ab693d26cb127478f4886b/c%2B%2B/Makefile.am#L240). Based on the output above, the first part of the pattern, `'s/^\([0-9]*[.][0-9]*[.][0-9]*\)`, is being lost as is the second of the two $ signs.

Having found a past BSD sed/regex issue in #210, I pulled the whole pattern from Makefile.am and tested it successfully in an OpenBSD shell with `echo 2.9.2 | sed -e 's/^\([0-9]*[.][0-9]*[.][0-9]*\)\([.][0-9]*\)*\(-.*\)*$$/\1\3/g'`.

**Comment by pwrdwnsys** [comment]
@kentonv After some more investigation, it looked like the system's default `make` was incorrectly parsing the SO_VERSION regex, so I installed GNU make 4.2 from packages to build with `gmake` and now the build works against my patch - I will submit as a PR shortly.

Where would be the best place for me to submit OpenBSD-specific build instructions?

**Comment by kentonv** [comment]
I guess this must be a problem with this line:

https://github.com/capnproto/capnproto/blob/23db5e3fd91104a0b2881d8f8ab3c10bf9dd8e75/c++/Makefile.am#L240

Can we fix that line somehow so that it doesn't require gmake? I'm not sure what about it is wrong for non-GNU make.

If it's not easy to fix that line, then can we detect whether we're using gmake and fail out early if not, with a message saying to use gmake?

This way people don't need to read docs (which they won't anyway...).

**Comment by kentonv** [comment]
Oh geez I see what it's doing. It thinks the closing parenthesis _inside_ the sed expression ends the `$(shell ...)` expansion, and it ends up replacing the whole thing with an empty string (not sure if it's executing it and getting no output due to the error, or if it's treating the whole thing as a variable name rather than a shell command and finding the variable doesn't exist).

Seemingly the closing parenthesis needs to be escaped somehow?

**Comment by kentonv** [comment]
Apparently the BSD way is to use a `!=` assignment, and GNU Make added support for this in version 4.0, released in 2013. That's probably old enough to require (after all we require C++14).

https://stackoverflow.com/questions/21874468/run-a-command-in-gnu-and-bsd-makefile-and-store-the-result-into-a-variable

Let me try it...

**Comment by kentonv** [comment]
Not quite so easy... See #837.

**Comment by kentonv** [comment]
Came up with a better solution in #838. @pwrdwnsys please let me know if it works for you.

**Comment by mbelop** [comment]
Btw, OpenBSD 6.5 does [implement aligned_alloc in libc](https://github.com/openbsd/src/blob/master/lib/libc/stdlib/malloc.c#L2058). While the C version is [behind a `__ISO_C_VISIBLE >= 2011` check](https://github.com/openbsd/src/blob/master/include/stdlib.h#L226) and doesn't require any compiler flags for clang, the C++ version (coming from LLVM) [requires C++17 or later](https://github.com/openbsd/src/blob/master/lib/libcxx/include/cstdlib#L158).
