### ISSUE TITLE
build in vs2015 failed: "You need Visual Studio 2017 or better to compile this code"

### ISSUE THREAD

**Issue by lianhub** [capnproto/capnproto#840]
I tried to build Capn-Proto in VS-2015, and I followed the instruction:
* cmake -G "Visual Studio 14 2015"

Why built the solution fail? I got errors:
* "You need Visual Studio 2017 or better to compile this code."

Any hint? Thanks!

Jerry

**Comment by kentonv** [comment]
Hmm, the instructions might be outdated. I think you now need:

    cmake -G "Visual Studio 15 2017"

Can you try that?

If that works I'll fix the docs.

**Comment by lianhub** [comment]
Yeah, I tried to build with vs-2017, but not all successful:
* ========== Build: 15 succeeded, 5 failed, 0 up-to-date, 0 skipped ==========

So, my further questions:
* should I use vs-2015, or vs-2017
* how to fix the building-problems in vs-2015, and vs-2017?

Thanks!
Jerry

**Comment by kentonv** [comment]
Visual Studio 2017 is required, yes.

What are the errors you are seeing when building with VS 2017?

**Comment by lianhub** [comment]
I uninstalled and reinstalled vs-2017, now all builds successfully! 

So thank **Kentonv** for your quick response, will test more on Cap'n!

**Comment by kentonv** [comment]
Documentation fixed partially in 107b8d0 and more completely in 6b6f824a416cb8218fe9a0b92d2691a9152507c9.
