### ISSUE TITLE
how to setup "Addressbook" sample in vs-2017?

### ISSUE THREAD

**Issue by lianhub** [capnproto/capnproto#843]
I create a C++ console application in vs-2017
```
#include "addressbook.capnp.h"
#include <capnp/message.h>
#include <capnp/serialize-packed.h>
#include <iostream>

using addressbook::Person;
using addressbook::AddressBook;
using namespace capnp;

int main()
{
    MallocMessageBuilder message;

    std::cout << "Hello World!\n"; 
}
```
But I got error when building the project:

> Error	LNK2019 unresolved external symbol "public: __thiscall capnp::MallocMessageBuilder::MallocMessageBuilder ...

> Error	LNK2019 unresolved external symbol "public: virtual __thiscall capnp::MallocMessageBuilder::~MallocMessageBuilder ...

> Error	LNK1120	2 unresolved externals

what could be wrong? 
* I use "capnp compile" to compile address-book schema successfully.
* I add include path for <capnp/...>
* do I need to add path for any *.lib files?

Thanks!
Jerry

**Comment by KubaO** [comment]
Yes, you need to include the capnp library. Capnproto code needs the runtime code - that code is static and not generated, and comes from that library.

**Comment by kentonv** [comment]
Yes, as @KubaO said, you need to link against the .libs that were produced when you compiled Cap'n Proto. For basic serialization you need libkj.lib and libcapnp.lib. (For RPC you also need libkj-async.lib and libcapnp-rpc.lib, but your example doesn't use RPC.)
