### ISSUE TITLE
Support for duplicate enumerants

### ISSUE THREAD

**Issue by KubaO** [capnproto/capnproto#845]
As it says in the box: it'd be cool to be able to refer to a given canonical enumerant using multiple names. Merely dropping the error message is insufficient, as it'd let protocol bugs slip through. I propose the following syntax:

```
enum Example {
  enumerant0 @0;
  shadows0 (enumerant0) @0;
  enumerant1 @1;
}
```

I imagine that allowing something like `shadows0 @enumerant0;` would be more painful to parse, but that's another possibility. Or perhaps `shadows0 (enumerant0)` with `@0` being optional.

If this would be of interest, I'd take on it since some of our internal APIs would be nicer if this was allowed.

**Comment by kentonv** [comment]
This has come up before and I'm not a fan of supporting this. Many languages do not support duplicate enumerants -- C/C++ is an outlier here. Protobuf supported duplicate enumerants and it created a lot of pain for implementations other than C++.

I'd argue instead that the right way to declare an alias is as a constant:

    const shadows0 :Example = enumerant0;

Currently you can't declare constants inside an enum block, so you don't get the same scoping. If there's a real need for allowing same-scope enumerant aliases then I'd want to explore whether we can come up with a way to declare constants in enum scope, with code generator magic to make it do what you want.

But before considering that I'd really like to see compelling use cases. The use cases I've seen historically for declaring aliases really did not need to be in the same scope -- it worked fine to declare them as constants along-side the enum.

**Comment by KubaO** [comment]
Would it be OK to add the suggestion to use consts to the error message about duplicated ordinals, then, so that duplicated enumerants would guide the user towards the right way? I'd do a PR if that'd be OK, it's trivial change anyway.

**Comment by KubaO** [comment]
I have little idea how compelling a use case must be. I have a message that carries properties of physical measurement units, and some units have more than one name. E.g. a `meter` is also a `length` unit.

**Comment by KubaO** [comment]
I'll close it for now, until someone comes up with new ideas.
