### ISSUE TITLE
Parametrize AnyPointer with optional list, capability and struct types.

### ISSUE THREAD

**Issue by KubaO** [capnproto/capnproto#847]
### Motivation

```
interface Object {
  getData @0 (recursive :Bool) -> (data :Data);
  struct Data {
    self @0 :Object;
    subObject1 @1 :AnyPointer(Object, Object.Data);
    subObject2 @2 :AnyPointer(Object, Object.Data);
    imagineLotsaOtherSubObjectsHere @3 :Void;
    someProperty @4 :Text;
  }
}
```

Suppose you want to get the data of a certain object only: call `getData(false)` on that object, and you get `Data` with all `subObject`s referencing capabilities. To get data of sub-objects would require explicit `getData` calls on their capabilities. But if you want to get the data of all the child objects recursively with one call, you'd call `getData(true)`, and `subObject`s would point to `Object.Data` (or null at the leaves).

One could imagine that `getData` accepted some more detailed definition of a query or a filter, to specify what objects in the tree the client is interested in.

### A Palatable Workaround

A self-documenting type alias can be used, but that doesn't improve type safety.

```
interface Object {
  getData @0 (recursive :Bool) -> (data :Data);
  struct Data {
    self @0 :Object;
    subObject1 @1 :Object.OrData;  # vs. AnyPointer(Object, Object.Data)
    subObject2 @2 :ObjectB.OrData;
  }
  using OrData = AnyPointer;
}

interface ObjectB {
  getData @0 (recursive :Bool) -> (data :Data);
  struct Data {
    self @0 :ObjectB;
    ...
  }
  using OrData = AnyPointer;
}
```

### Encoding Changes

None. The change only adds a modicum of type-safety and self-documentation to `AnyPointer`.

### Schema Changes

The schema remains fully backwards compatible: the `AnyPointer` parametrization is an optional feature. Plain `AnyPointers` will keep the binary representation of the schema bit-identical. Impact on existing users and existing code if the feature is not used should be thus nil.

With parametrization, a single pointer is appended to the `Type` struct, and all existing schema users should be ignoring that pointer unless they use a broken home-grown schema binary reader that doesn't properly ignore future fields.

1. Grammar change: Allow parametrizing `AnyPointer` on up to three types: a capability type, a struct type, and a list type (Data or Text included), given in any order in parentheses following `AnyPointer`. The tag to discriminate between those types is embedded into the pointer itself. E.g.:

    foo @0 :AnyPointer(SomeStruct, List(Element));

2. Protocol change: change the type of `Type.anyPointer.unconstrained.anyKind` from `Void` to `List(Type)`, where the list of types provides up to three parametrizing types.

```
--- schema.capnp	2019-06-25 14:03:41.000000000 -0400
+++ schema.capnp	2019-06-25 14:03:46.000000000 -0400
 @0xa93fc509624c72d9;
 $import "/capnp/c++.capnp".namespace("capnp::schema");
 struct Node @0xe682ab4cf923a417 {  # 40 bytes, 6 ptrs
@@ -142,7 +142,7 @@
       union {  # tag bits [64, 80)
         unconstrained :group {  # union tag = 0
           union {  # tag bits [80, 96)
-            anyKind @18 :Void;  # bits[0, 0), union tag = 0
+            anyKind @18 :List(Type);  # ptr[0], union tag = 0
```

3. Add `annotation names(field, enumerant, struct, enum, interface, method, param, group, union): List(Text)` to `c++.capnp` (and other codegens, as they gather support for this). This annotation overrides codegen-default names for the type-constrained setters/getters for the `AnyPointer(...)` field. The names are taken to be in the same order as the parameters to `AnyPointer`. Empty text or null text mean "use the default name`.

  The `name: Text` annotation still applies to the pointer field itself of course.

### Codegen Changes 

1. Add `bool has<PointerField><Type>()` to the reader and writer, for each type the pointer is parametrized on. 

2. Add `Type::Reader get<PointerField><Type>()` getter to the reader and writer, for each parametrization.

3. Add `Type::Builder get<PointerField><Type>(...)` convenience setters to the builder, for each parametrization (going through `AnyPointer::Builder` would still work of course).

Above, the `<PointerField><Type>` default name uses `name: Text` annotation on the pointer for `<PointerField>`, if provided. The default name is overridden with the one from the `names` annotation to the pointer, if provided.

**Comment by kentonv** [comment]
I think this use case is best solved by generics:

```
interface Object {
  getData @0 () -> (data :Data(Object));
  getDataRecursive @1 () -> (data :Data(Data));
  struct Data(T) {
    self @0 :Object;
    subObject1 @1 :T;
    subObject2 @2 :T;
    imagineLotsaOtherSubObjectsHere @3 :Void;
    someProperty @4 :Text;
  }
}
```

**Comment by KubaO** [comment]
Sweet. I like solutions that require no new code.
