### ISSUE TITLE
Allow explicitly controlling interface method parameter and return struct types.

### ISSUE THREAD

**Issue by KubaO** [capnproto/capnproto#848]
### Proposal

Allow replacing any of the lists of parameters or results with an explicit structure type that carries the parameters and results:

interface Foo {
  myMethod @0 MyMethodOptions -> MyMethodReturn;
}

Those structs would be explicit replacements for `Foo.MyMethodParams` and `Foo.MyMethodResults` that are currently generated by the codegen, i.e. the codegen would use those types as-is.

### Motivation

When a method is known to require future upgrades to its options or return data, one often ends up with:

```
myMethod @0 (options :MyMethodOptions) -> (result :MyMethodReturn);

struct MyMethodOptions {...}
struct MyMethodReturn {...}
```

This adds an unnecessary extra layer of indirection: the RPC protocol carries the parameter and return values a structs, so there are underlying `Params` and `Results` structs that are redundant.

```
struct MyMethodParams { options @0 :MyMethodOptions; }
struct MyMethodResults { results @0: MyMethodReturn; }
```

See also a related bug #849.

### Impact

No encoding changes. Backwards-compatible schema grammar change. No changes to schema protocol. *No changes needed to code generators*, since the parser can capture these user-provided types in the existing schema protocol.

**Comment by kentonv** [comment]
The exact syntax you propose is already supported today.

**Comment by KubaO** [comment]
Lol. Wow. Thanks!
