### ISSUE TITLE
word-by-word 'encoding' explanation of "AddressBook" binary file? 

### ISSUE THREAD

**Issue by lianhub** [capnproto/capnproto#850]
I produced unpacked encoding file of "AddressBook" demo successfully(see bottom), based on sample codes.
But I am confused by some encoding words:
* (see my own interpretation at the bottom, correct me If I am wrong.)
* For the **1st-person 'id'** word:    **7B 00 00 00 02 00 00 00**
-- 0x7B = 123, which is id=123----------ok!
-- 'id' is type UInt32, so '7B 00 00 00' ----- ok!
-- **but what is "02 00 00 00"?**

Thanks,
Jerry

=========== unpacked Binary "encoding" file of "AddressBook" demo =============
```
Offset(h) 00 01 02 03 04 05 06 07	 08 09 0A 0B 0C 0D 0E 0F

00000000  00 00 00 00 23 00 00 00	 00 00 00 00 00 00 01 00    ....#... ........
	   (frame header)	 	  ('AddressBook' struct pointer)
			
00000010  01 00 00 00 57 00 00 00	 08 00 00 00 01 00 04 00    ....W... ........
	('people' list pointer)	        ('people' list tag)
		 
00000020  7B 00 00 00 02 00 00 00	 21 00 00 00 32 00 00 00    {....... !...2...
	   (1st-'person' 'id')        (1st-'person' 'name' pointer)
			
00000030  21 00 00 00 92 00 00 00	 29 00 00 00 17 00 00 00    !...’... ).......
	 (1st-'person' 'email' pointer)   (1st-'person' 'phones' pointer)
		
00000040  39 00 00 00 22 00 00 00	 C8 01 00 00 00 00 00 00    9..."... È.......
 (1st-'person' 'employment' pointer)    (2nd-'person' 'id')
		
00000050  35 00 00 00 22 00 00 00	 35 00 00 00 82 00 00 00    5..."... 5...‚...
00000060  39 00 00 00 27 00 00 00	 00 00 00 00 00 00 00 00    9...'... ........
00000070  41 6C 69 63 65 00 00 00	 61 6C 69 63 65 40 65 78    Alice... alice@ex
00000080  61 6D 70 6C 65 2E 63 6F        6D 00 00 00 00 00 00 00    ample.co m.......
00000090  04 00 00 00 01 00 01 00	 00 00 00 00 00 00 00 00    ........ ........
000000A0  01 00 00 00 4A 00 00 00	 35 35 35 2D 31 32 31 32    ....J... 555-1212
000000B0  00 00 00 00 00 00 00 00	 4D 49 54 00 00 00 00 00    ........ MIT.....
000000C0  42 6F 62 00 00 00 00 00	 62 6F 62 40 65 78 61 6D    Bob..... bob@exam
000000D0  70 6C 65 2E 63 6F 6D 00	 08 00 00 00 01 00 01 00    ple.com. ........
000000E0  01 00 00 00 00 00 00 00	 09 00 00 00 4A 00 00 00    ........ ....J...
000000F0  02 00 00 00 00 00 00 00	 09 00 00 00 4A 00 00 00    ........ ....J...
00000100  35 35 35 2D 34 35 36 37	 00 00 00 00 00 00 00 00    555-4567 ........
00000110  35 35 35 2D 37 36 35 34	 00 00 00 00 00 00 00 00    555-7654 ........
```

**Comment by KubaO** [comment]
To understand the binary format, you should look at the annotated schema that the `capnpc` can generate for you:

```
capnp compile -ocapnp addressbook.capnp
# or equivalently
capnpc -ocapnp addressbook.capnp
```

Here's the relevant output:

```
struct Person @0x98808e9832e8bc18 {  # 8 bytes, 4 ptrs
  id @0 :UInt32;  # bits[0, 32)
  name @1 :Text;  # ptr[0]
  email @2 :Text;  # ptr[1]
  phones @3 :List(PhoneNumber);  # ptr[2]
  employment :group {
    union {  # tag bits [32, 48)
      unemployed @4 :Void;  # bits[0, 0), union tag = 0
      employer @5 :Text;  # ptr[3], union tag = 1
      school @6 :Text;  # ptr[3], union tag = 2
      selfEmployed @7 :Void;  # bits[0, 0), union tag = 3
    }
  }
}
```

So, as you see, the `employment` union tag is encoded in bits `[32,48)`, or bytes `[4,6)`. The bits `[48,64)` remain unassigned and will be zeroes in this version of the `Person` structure. But if new fields were added, those bits could be used for something.

The `employment` is not a pointer. It's a union, i.e. there's a 16-bit tag, and a shared area where various options from the union would fit. In the example, the `employment-tag` is 2, that is `school`, and thus `ptr[3]` points to `school: Text`. The other fields (`unemployed`, `employer`, `selfEmployed`) are excluded, and in the C++ interface the `addresbook::person::reader::hasSchool()` would be true, but `hasUnemployed()`, `hasEmployer()` and `hasSelfEmployed()` would be false.

Note: The notation `[a,b)` is an interval closed on the left side (`[` means "closed"), i.e. including `a`, and open on the right side (`)` means "open"), i.e. excluding `b`. So an interval `[32,48)` includes bits 32...47.

**Comment by kentonv** [comment]
@KubaO's analysis is correct. Thanks, Kuba!

Closing this since I think it is answered and in any case it isn't an action item for the project. FWIW, you can also post questions like this in [the discussion group / mailing list](https://groups.google.com/group/capnproto).
