### ISSUE TITLE
Cannot build "calculator client/server" sample in vs-2017

### ISSUE THREAD

**Issue by lianhub** [capnproto/capnproto#853]
When I tried to build sample 'calculator server' in vs-2017, I got error of "10 unresolved externals"! (see bottom)
* I have added all *.lib files to project properties (Linker)
* **kj.lib, kj-async.lib, kj-gzip.lib, kj-http.lib, kj-test.lib**
* **capnp.lib, capnpc.lib, capnp-json.lib, capnp-rpc.lib**
* And I add "**#pragma comment(lib,"Ws2_32.lib")**" already

Any hint?  Thanks!

Jerry

========= build error message ====================================
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual class kj::Promise<void> __thiscall Calculator::Server::dispatchCall(unsigned __int64,unsigned short,class capnp::CallContext<struct capnp::AnyPointer,struct capnp::AnyPointer>)" (?dispatchCall@Server@Calculator@@UAE?AV?$Promise@X@kj@@_KGV?$CallContext@UAnyPointer@capnp@@U12@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual class kj::Promise<void> __thiscall Calculator::Server::evaluate(class capnp::CallContext<struct Calculator::EvaluateParams,struct Calculator::EvaluateResults>)" (?evaluate@Server@Calculator@@MAE?AV?$Promise@X@kj@@V?$CallContext@UEvaluateParams@Calculator@@UEvaluateResults@2@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual class kj::Promise<void> __thiscall Calculator::Server::defFunction(class capnp::CallContext<struct Calculator::DefFunctionParams,struct Calculator::DefFunctionResults>)" (?defFunction@Server@Calculator@@MAE?AV?$Promise@X@kj@@V?$CallContext@UDefFunctionParams@Calculator@@UDefFunctionResults@2@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual class kj::Promise<void> __thiscall Calculator::Server::getOperator(class capnp::CallContext<struct Calculator::GetOperatorParams,struct Calculator::GetOperatorResults>)" (?getOperator@Server@Calculator@@MAE?AV?$Promise@X@kj@@V?$CallContext@UGetOperatorParams@Calculator@@UGetOperatorResults@2@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2019	unresolved external symbol "public: class capnp::Request<struct Calculator::Value::ReadParams,struct Calculator::Value::ReadResults> __thiscall Calculator::Value::Client::readRequest(class kj::Maybe<struct capnp::MessageSize>)" (?readRequest@Client@Value@Calculator@@QAE?AV?$Request@UReadParams@Value@Calculator@@UReadResults@23@@capnp@@V?$Maybe@UMessageSize@capnp@@@kj@@@Z) referenced in function "class kj::Promise<double> __cdecl readValue(class Calculator::Value::Client)" (?readValue@@YA?AV?$Promise@N@kj@@VClient@Value@Calculator@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2019	unresolved external symbol "public: virtual class kj::Promise<void> __thiscall Calculator::Value::Server::dispatchCall(unsigned __int64,unsigned short,class capnp::CallContext<struct capnp::AnyPointer,struct capnp::AnyPointer>)" (?dispatchCall@Server@Value@Calculator@@UAE?AV?$Promise@X@kj@@_KGV?$CallContext@UAnyPointer@capnp@@U12@@capnp@@@Z) referenced in function "[thunk]:public: virtual class kj::Promise<void> __thiscall Calculator::Value::Server::dispatchCall`adjustor{8}' (unsigned __int64,unsigned short,class capnp::CallContext<struct capnp::AnyPointer,struct capnp::AnyPointer>)" (?dispatchCall@Server@Value@Calculator@@W7AE?AV?$Promise@X@kj@@_KGV?$CallContext@UAnyPointer@capnp@@U12@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual class kj::Promise<void> __thiscall Calculator::Value::Server::read(class capnp::CallContext<struct Calculator::Value::ReadParams,struct Calculator::Value::ReadResults>)" (?read@Server@Value@Calculator@@MAE?AV?$Promise@X@kj@@V?$CallContext@UReadParams@Value@Calculator@@UReadResults@23@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2019	unresolved external symbol "public: class capnp::Request<struct Calculator::Function::CallParams,struct Calculator::Function::CallResults> __thiscall Calculator::Function::Client::callRequest(class kj::Maybe<struct capnp::MessageSize>)" (?callRequest@Client@Function@Calculator@@QAE?AV?$Request@UCallParams@Function@Calculator@@UCallResults@23@@capnp@@V?$Maybe@UMessageSize@capnp@@@kj@@@Z) referenced in function "public: __thiscall <lambda_821cf49ca2a9fb4738a301b90d77819e>::operator()(class kj::Array<double> &&)" (??R<lambda_821cf49ca2a9fb4738a301b90d77819e>@@QAE@$$QAV?$Array@N@kj@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2019	unresolved external symbol "public: virtual class kj::Promise<void> __thiscall Calculator::Function::Server::dispatchCall(unsigned __int64,unsigned short,class capnp::CallContext<struct capnp::AnyPointer,struct capnp::AnyPointer>)" (?dispatchCall@Server@Function@Calculator@@UAE?AV?$Promise@X@kj@@_KGV?$CallContext@UAnyPointer@capnp@@U12@@capnp@@@Z) referenced in function "[thunk]:public: virtual class kj::Promise<void> __thiscall Calculator::Function::Server::dispatchCall`adjustor{4}' (unsigned __int64,unsigned short,class capnp::CallContext<struct capnp::AnyPointer,struct capnp::AnyPointer>)" (?dispatchCall@Server@Function@Calculator@@W3AE?AV?$Promise@X@kj@@_KGV?$CallContext@UAnyPointer@capnp@@U12@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual class kj::Promise<void> __thiscall Calculator::Function::Server::call(class capnp::CallContext<struct Calculator::Function::CallParams,struct Calculator::Function::CallResults>)" (?call@Server@Function@Calculator@@MAE?AV?$Promise@X@kj@@V?$CallContext@UCallParams@Function@Calculator@@UCallResults@23@@capnp@@@Z)	calc-server	D:\capn\capnproto-c++-0.7.0\calc-server\calc-server.obj	1	

Error	**LNK1120	10 unresolved externals**	calc-server	D:\capn\capnproto-c++-0.7.0\Debug\calc-server.exe	1

**Comment by kentonv** [comment]
Hi @lianhub,

It looks to me like you did not link the compiled generated code `calculator.capnp.obj`, which should be compiled from `calculator.capnp.c++`, which is generated by the capnp compiler from `calculator.capnp`.

**Comment by lianhub** [comment]
What do you mean by "link the calculator.capnp.obj"?
* I generated "calculator.capnp.h" and "calculator.capnp.c++"
* And I "#include calculator.capnp.h"
* what is further to be done?

Thanks!

**Comment by jclee** [comment]
Most likely, you need to explicitly add the generated `calculator.capnp.c++` to your project so that the compiler knows to compile it and the linker knows to link it in.  Including its header file in some other compilation unit is not sufficient.

**Comment by lianhub** [comment]
I already copied both "`calculator.capnp.h`" and "`calculator.capnp.c++`" to my project folder.

**Comment by jclee** [comment]
I assume from your error message that just dumping c++ files in your project's folder is not sufficient for VS to know that it needs to build and link them when building the project.  You might want to try explicitly adding `calculator.capnp.c++` to the project, per this MSDN blog post: https://blogs.msdn.microsoft.com/benwilli/2015/05/21/visual-studio-tip-8-adding-existing-files-with-show-all-files/

**Comment by lianhub** [comment]
I already followed the instructions as described in your` msdn.microsoft` link.
I just tried the following steps:
* delete `calculator.capnp.c++`
* and I got the same error
* which means `calculator.capnp.c++` is not used.
* what else can be done? (I already followed the instructions)

**Comment by jclee** [comment]
Sorry, I'm not sure.  `calculator.capnp.c++` is certainly required -- it is why you are getting the linker error messages.  It seems likely that some aspect of your manually generated project file or local environment is preventing Visual Studio from recognizing the `.c++` file as a file that needs to be built and linked into the project result.  (You could test whether the file is being compiled by temporarily introducing a "#error" line in the file; if the compiler does not report the error in the file, your project is not correctly configured to build and link the file.)

The project files automatically generated by CMake are known to work, as they are currently passing continuous integration builds on appveyor.  You might want to try generating and building the solution file via CMake, per the build instructions on the website: https://capnproto.org/install.html#installation-windows

Assuming that the sample builds correctly in the CMake-generated solution, you could then proceed by identifying the differences in configuration between your project file and the CMake one.

**Comment by kentonv** [comment]
@lianhub Sorry, but this is not a problem with Cap'n Proto, it's a problem with your build system (Visual Studio). You have to figure out how to make it include `calculator.capnp.c++` in the project so that it actually compiles this file. We aren't going to be able to help you with this; we don't know Visual Studio any better than you do.

**Comment by lianhub** [comment]
Unfortunately, I could not find "calculator sample" if I followed instructions: [](https://capnproto.org/install.html#installation-windows)

@kentonv, Could you please add "calculator sample" to windows installation .zip file?

**Comment by kentonv** [comment]
@lianhub No. There is no need to install the sample. It's just a sample.

**Comment by lianhub** [comment]
I mean to add a test project with calculator client/server, just like all other projects `capnproto-c++-win32-0.7.0.zip`. Then if I do` cmake -G "Visual Studio 15 2017"`, there has a calculator client/server project ready to be tested.

**Comment by kentonv** [comment]
@lianhub I'd be willing to consider a PR adding it, if someone contributed one. I don't have time to work on it myself.

**Comment by lianhub** [comment]
somehow I made it working: change `calculator.capnp.c++`  to `calculator.capnp.cpp`, and add to the project.
Don't know why, just kind of "trial and error".
