### ISSUE TITLE
please reopen the closed issue #853

### ISSUE THREAD

**Issue by lianhub** [capnproto/capnproto#856]
As my problem is not solved yet!

Thanks,
Jerry

**Comment by kentonv** [comment]
@lianhub Your "problem" is not a problem with Cap'n Proto. It is not our job to teach you how to use your IDE.

Opening a new issue to complain about this is highly inappropriate. If you continue with this behavior, I will ban you from this project.

**Comment by lianhub** [comment]
Sorry, my fault. Please delete this issue completely.
