### ISSUE TITLE
Type-safety for generic interfaces across the client-server barrier.

### ISSUE THREAD

**Issue by KubaO** [capnproto/capnproto#860]
Unless I'm missing something major, the type-safety for generics only exists on the client side, and no type information is passed to the server. The server code can use concrete types, but doesn't know how to select the type needed.

E.g. suppose a server supports attaching multiple data types to a Node, and exposes this capability via a Setter:

```
interface Setter(T) {
  set @0 (value :T) -> ();
}

interface Node {
  getAnySetter @0 [T] () -> (setter :Setter(T));
}
```

The client gets a setter, `set`s it to choose a concrete type for it, then uses it type-safely.

But the server doesn't know what type is the setter trying to set. The server-side context for `Setter.set` has no type information available about what particular setter type was it.

It's understandable that there are many uses for the RPC protocol, and adding type information willy-nilly would be forcing an approach that's unsuitable for many users yet costs a word per every generic type parameter per call. So I'm not after that. I'm after a way of providing this functionality when desired, with least impact to the protocol as a whole.

I see four options of solving it:

## 1. Handwritten Code

Schema has node annotated as `interface Node $Cxx.namespace("example::detail")`, user hand-derives the "real" `Node` from it, and extends the `Client` with a generic shim that calls `getSetter` with `typeId` set appropriately. Not the biggest deal, but yuck. Schemas are supposed to be self-documenting...

## 2. Explicitly Injecting TypeId into a Generic Call

The current syntax doesn't support it, since default values are an invariant in type parameters (d'ohh):

```
interface Node {
  getSetter @0 [T] (typeId :UInt64 = T.typeId) -> (setter :T);   # doesn't work
  getSetter2 @0 [T] (typeId :UInt64 = Value.typeId) -> (setter :T); # works, but not very useful
}

struct Value @0xabcd {
  const typeId :UInt64 = 0xabcd;
}
```

The constant `typeId` is a crutch, the schema could make it easier, say add an implicit `_typeId` constant to all types - its value wouldn't appear in binary schema, since it's already there, but its *uses* would be propagated to generated code. E.g., in C++:

```
template <typename T> class Node::GetSetterParams::Builder {
  ...
  inline void setTypeId( ::uint64_t value = ::capnp::typeId<T>() );
  // this works today
}
```

Then `init` would need to call `setTypeId`, so  a special constructor for init-only use would be needed if we don't want to leak this into `init`. This default would not be anything like normal default field values, since it's not constant for the type: xor-with-default doesn't apply. It smells bad to make this look like a default, since it's nothing like it. .

## 3. Const Fields

Make a real-deal const field:

```
asSetter @0 [T] (const typeId :UInt64 = T._typeId) -> (setter :T);
# equivalent to
struct AsSetterParams(T) {
  const typeId @0 :Uint64 = T._typeId;
}
```

The field identifier is the only schema + syntax change. Codegens would use it to inject the value into the `init` of the structure.

## 4. Reified Specializations - Specialization by Substitution

Capnproto specializations are syntactic typesafe sugar, not a way of creating types: a new type has a unique typeId, whereas `MyInterface(MyConcreteType)` has same typeId as `MyInterface`. That's a fine decision, since including this information would add mostly uneeded cost.

Yet it would help to be able to reify specialized types, using existing types as templates to create new types. I'd love to have a `Setter(MyType)` be unique. In generated code, `Setter_MyType::Client` and `::Server` would derive from generic setters. Handling the specialization-by-substitution would be optional on the `Server` side, and all existing code would continue to build and interoperate with reified specializations *as long as they used pointer types*. Codegen would formalize this by making pointer-based reified specializations derive from the generic one, but the wire-incompatible ones would be separate types. 

This brings us back to specialization-by-substitution - not only for structs, but for all generic types, now and in the future, and would solve this problem without adding means of injecting type ids into calls... although I see those as somewhat orthogonal in the big scheme of things.

Is there any other way to address this? Am I missing something? Since I need this in production, and I needed it "yesterday", I added the support for const fields as the path of least resistance on my end, but I'd gladly use a better approach instead.

**Comment by kentonv** [comment]
Kuba, I sent you an e-mail a couple days ago. Can you please read it before submitting any more issues?

------

Generics in Cap'n Proto are designed to work similarly to e.g. Java, where generics can catch errors at compile time but are totally erased before runtime. In part this design is intended to ensure that languages that use type-erasure-based generics -- again, like Java -- can cleanly integrate Cap'n Proto generics.

It looks like you are trying to find a way to fill in a data parameter of a method call based on the type parameter. This is not type-erasure-friendly.

If I were going to solve this problem in a type-erasure-friendly way, I would create a new built-in type `TypeId(T)`. It would be encoded as a `UInt64`, but specializations can only encode the specific type ID for the type `T`. E.g. `capnp::typeId<T>()` would return `capnp::TypeId<T>` wrapping the type ID for `T`, and you would not be allowed to modify the wrapped ID without first casting it to a plain integer.

    asSetter @0 [T] (type: TypeId(T)) -> (setter :T);

The application would still be required to fill in the parameter `type` explicitly, but it would be impossible to write code that fills it with anything other than the type ID for `T`. (This sort of pattern is common in Java, BTW.)

With that said, I'm not convinced that such a feature would be worth implementing. It doesn't enable any new functionality, it only adds a tiny amount of type safety for a fairly unusual use case.

**Comment by KubaO** [comment]
That's a rather reasonable idea. I'll put it on my schedule somewhere, I like it.

I have lot of uses for data types that have related interface types that scream for data-dependent types of some sort. Usually there's some sort of an impedance mismatch: either things are easy at the client end, but nigh impossible on the server end, or vice versa. I've read all of sandstorm's schemas for inspiration, and didn't see any better alternatives. This may well be going totally against the grain of capnproto, though.

All in all, capnproto seems like a very elegant design that's so elegant that adding almost anything else to it makes it worse, not better. I have glossed over the CORBA 3 specs, and I have full understanding (I think) of why feature creep by committee is a bad thing. They did get to adding async calls, though. For what it's worth, lol.

I must have missed the email - sorry about that.
