### ISSUE TITLE
DiskFile holes fail

### ISSUE THREAD

**Issue by lguangyu** [capnproto/capnproto#863]
Trying local build (v0.7.0) on cluster server running Centos 7, x86-64, working space is IBM GSS GPFS 26. Building with GCC 7.2.0.
Failed on 1 test in total of 3 cases:
```
[ TEST ] kj/filesystem-disk-test.c++:834: DiskFile holes
kj/filesystem-disk-test.c++:875: failed: expected copy->stat().spaceUsed == meta.spaceUsed
1052672 != 8192
kj/filesystem-disk-test.c++:898: failed: expected copy->stat().spaceUsed == meta.spaceUsed
2097152 != 8192
kj/filesystem-disk-test.c++:924: failed: expected file->stat().spaceUsed < meta.spaceUsed
8192 == 8192
[ FAIL ] kj/filesystem-disk-test.c++:834: DiskFile holes (121566 μs)
```
It's apparent to me that the file system did sort of similar optimizations. Does anyone have any idea if it is safe to going on? Thanks for any information in advance!

**Comment by kentonv** [comment]
Hi @lguangyu,

You can safely ignore these. It probably means your filesystem doesn't support sparse files (or doesn't support them in quite the same way as others), but nothing in Cap'n Proto actually requires sparse files.

Let's leave this issue open as a reminder that I need to make this test more lenient. We shouldn't be shipping tests that fail based on the user's choice of filesystem...

**Comment by lguangyu** [comment]
Hi @kentonv,

Thank your for the quick reply! It is good to know that. The 0.6.1 build seems all green with identical configuration.. seems the sparse file logic is a new feature introduced in 0.7.0.
