### ISSUE TITLE
explaining concept of capability with an example?

### ISSUE THREAD

**Issue by lianhub** [capnproto/capnproto#875]
I was somewhat confused about what capability means.
* does capability mean interface?
* Why do we need a capability table?

can somebody explain it with "calculator" example? 
* For simplicity, please use "Evaluating a literal" as a demo. 
* If possible, please use RPC request/response packets to explain.

Thanks!
Jerry

**Comment by kentonv** [comment]
Hi @lianhub,

Questions like this are best asked on the mailing list: https://groups.google.com/group/capnproto

The issue tracker is best used to report specific bugs in Cap'n Proto which need to be fixed.

The basic answer to your question is that a "capability" is a reference to a remote RPC object. Whenever you have a field whose type is an interface type, we call its value a "capability". You can use a capability to make RPC calls.

This definition of "capability" comes from "capability-based security" and the "object capability model".

Here are some links to discussions of capabilities in the capability-based security sense:
* https://capnproto.org/rpc.html#distributed-objects
* https://en.wikipedia.org/wiki/Capability-based_security
* https://en.wikipedia.org/wiki/Object-capability_model
* http://www.erights.org/elib/capability/ode/index.html
