### ISSUE TITLE
Building under MSVC 2017: CMake option "BUILD_TESTING" appears to generate errors

### ISSUE THREAD

**Issue by sharpe5** [capnproto/capnproto#878]
Thank you for your excellent work on Capnproto. I'm evaluating both it and Flatbuffers, and so far Capnproto seems to have a far nicer API for building and editing buffers.

I'm trying to run the tests under Windows. However, when using CMake under MSVC 2017, I get the following error if I tick "BUILD_TESTING" (but not if I leave it unticked):

```
Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at c++/cmake/CapnProtoMacros.cmake:100 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
Call Stack (most recent call first):
  c++/src/capnp/CMakeLists.txt:209 (capnp_generate_cpp)


CMake Error at c++/cmake/CapnProtoMacros.cmake:100 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
Call Stack (most recent call first):
  c++/src/capnp/CMakeLists.txt:209 (capnp_generate_cpp)


CMake Error at c++/cmake/CapnProtoMacros.cmake:100 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
Call Stack (most recent call first):
  c++/src/capnp/CMakeLists.txt:209 (capnp_generate_cpp)


CMake Error at c++/cmake/CapnProtoMacros.cmake:100 (add_custom_command):
  add_custom_command called with OUTPUT containing a "#".  This character is
  not allowed.
Call Stack (most recent call first):
  c++/src/capnp/CMakeLists.txt:209 (capnp_generate_cpp)


Configuring incomplete, errors occurred!
```

Looking at the Appveyor results, it does not appear as if the tests are being automatically run:
https://ci.appveyor.com/project/kentonv/capnproto

I'm wondering if the tests run under Linux or MacOS?

**Comment by kentonv** [comment]
I have to admit I don't know how the cmake stuff works. But the CI definitely runs the tests -- you can see the test output at the bottom of any of the logs.

**Comment by jclee** [comment]
Looks like BUILD_TESTING defaults to on, and it doesn't look like Appveyor changes this setting.  Maybe check your Cmake version?  Appveyor logs say it is using `cmake version 3.15.1`.

**Comment by sharpe5** [comment]
You're right, the tests do run under MSVC. I was looking under the "Test"
tab in Appveyor, but they are in the console output.

We can definitely close this issue then.

**Comment by sharpe5** [comment]
Found the issue: it's appears to be a bug in CMake.

The path to my project was:
```
S:\Research\C#\github\capnproto_master
```

Changed it to to:

```
S:\Research\Cs\github\capnproto_master
```

... and everything worked perfectly.

CMake can fix this bug, or at the very least, provide a more meaningful error message. The current error message implies that the error is in the `script`, it needs to say that the error is in the `path to the project directory`, e.g.:

```
To fix, eliminate the '#' sign from the project directory path: S:\Research\C#\github\capnproto_master
```
