### ISSUE TITLE
std::copy doesn't work on List types?

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto#892]
```
struct Foo {
    field @0 List(Float32);
}
```

In C++:
```
Foo::Reader r = ...;
if (r.getField().size() != 11) {
    return;
}
std::array<float, 11> extracted;
std::copy(r.getField().begin(), r.getField().end(), extracted.begin());
```
I get a compiler error that there's no matching std::copy/std::copy_n:
```
error: no matching function for call to 'copy_n'
  std::copy(r.getField().begin(), r.getField().end(), extracted.begin());
  ^~~~~~~~~~~
C:/Users/vlovich/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\algorithm:1735:1: note: candidate template ignored: requirement '__is_input_iterator<IndexingIterator<const Reader, float> >::value' was not satisfied [with _InputIterator = capnp::_::IndexingIterator<const capnp::List<float, capnp::Kind::PRIMITIVE>::Reader, float>, _Size = unsigned int, _OutputIterator = float *]
copy_n(_InputIterator __first, _Size __orig_n, _OutputIterator __result)
^
C:/Users/vlovich/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/c++/v1\algorithm:1760:1: note: candidate template ignored: requirement '__is_random_access_iterator<IndexingIterator<const Reader, float> >::value' was not satisfied [with _InputIterator = capnp::_::IndexingIterator<const capnp::List<float, capnp::Kind::PRIMITIVE>::Reader, float>, _Size = unsigned int, _OutputIterator = float *]
copy_n(_InputIterator __first, _Size __orig_n, _OutputIterator __result)
```
Is it an oversight in how IndexingIterator is defined or are capnproto `List` objects incompatible with STL algorithms?

**Comment by vlovich** [comment]
std::transform using the identity function works so it does appear to be something related to the way the iterator is defined.

```
std::transform(r.getField().begin(), r.getField().end(), extracted.begin(), [](const auto& elem) {
    return elem;
  });
```

**Comment by kentonv** [comment]
Maybe it has to do with the fact that `operator[]` returns `T` and not `T&`? Unfortunately there's no way around this since the elements of a capnp list are constructed on-demand (e.g. for floats, byte-swapping may be needed on big-endian architectures).

FWIW, I would recommend factoring out the call to `getField()`, like:

    auto list = r.getField();
    std::copy(list.begin(), list.end(), extracted.begin());

Otherwise, you're performing all the pointer validation twice. Moreover, technically, the two calls return two different Reader objects, and comparing iterators from different objects is UB -- however, it will work in this case.

**Comment by kentonv** [comment]
My thought had been that maybe `__is_input_iterator` and `__is_random_access_iterator` expect that dereferencing iterators should return references.

However, it looks like you figured it out. I forgot about KJ_STD_COMPAT and that it's apparently necessary to explicitly declare iterator traits.

It is unfortunate that this is not very discoverable. I'd accept adding a `capnp/compat/std-iterator.h` if you think it would help, though IMO it doesn't seem much better. Maybe we just need an explanatory comment on IndexingIterator.
