### ISSUE TITLE
capnp headers aren't warning safe on MSVC

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto#893]
Our build infra builds with `/wd4200 /wd4996 /wd5030 /wd4244 /wd4267 /wd4305 /wd4324 /W3 /Z7` and capnp generates warnings. That's mostly fine because I explicitly disable warnings for the capnp build itself via `/w` but MSVC (at least 2017) has no facility (unlike GCC/clang) to designate an include path or headers as system headers. This means that all includes of capnp headers need to be wrapped in `__pragma(warning(push, 0))`, `__pragma(warning(pop))` (can't recall if the generated files themselves have a similar issue or if it's all just transitive from the library itself). 

Would it be in-scope to submit a PR fixing this & if so how would you like it fixed? Can either try to address the warnings (primarily unreferenced formal parameter) but there are others that show up in C++17 mode that could be trickier like in hash.h:74 "warning C4127: conditional expression is constant". 

My initial thought is to suppress the header warnings via push/pop as the original reasoning for using the system_header pragma for GCC/clang is to avoid having to deal with supporting the intersection of all the warnings from different compiler versions that users may be using when building the code.

**Comment by kentonv** [comment]
Yeah, we don't want to chase down every possible warning that a user might have enabled, so it would be best if we could suppress header warnings when included as a dependency. If you know a clean way to do that for MSVC, I'd accept a PR.
