### ISSUE TITLE
Use blocking STDIN_FILENO with KJ event loop

### ISSUE THREAD

**Issue by Sarcasm** [capnproto/capnproto#919]
Hello,
I'm using the KJ event loop to write a CLI application that reads commands from stdin, and writes results+notifications to stdout, and logs to stderr.

I'd like to integrate waiting for data from stdin in the main event loop.

I tried with to make an AsyncIoStream with:

```cpp
auto stdinStream = io.lowLevelProvider->wrapInputFd(STDIN_FILENO)
```

However, I have a few issues with `wrapInputFd()`:

1. It makes stdin non blocking. I'm not sure to want that, e.g. if I exec() another process I'm wondering if this will be inherited.
2. It makes stdout and stderr non-blocking as well, if they are all dup() of the same tty.
    This makes stdout/stderr unusable for my application, and its subprocesses.
3. It takes ownership of the file descriptor (not a big deal but would be happier to without).
4. Did not tried to understand why exactly, but it also makes the program loop indefinitely when running under strace (maybe due to stderr inheriting the non-blocking behavior).
5. I'd like to supports things STDIN_FILENO pointing to a regular file `./my-app < commands.txt`.
   In this case, I'm considering stdin always ready to be read.

Instead of working around each of these issues, I'm under the impression that it is best not to mess with the blocking behavior of STDIN_FILENO.

Right now, I'm considering spawning a thread to read from stdin and an eventfd (for cancellation), using poll() level-triggered interface, but it saddens me.

Is there a way to wait for data from stdin in a level-triggered way that I missed?
If not, does it make sense to add an API for that (e.g. OBSERVE_LEVEL_TRIGGERED)?

From what I see, EPOLLET cannot be disabled:
https://github.com/capnproto/capnproto/blob/17993afff8cb78543a4dffa2809b41b9c8fbe437/c%2B%2B/src/kj/async-unix.c%2B%2B#L350

And I cannot implement something like FdObserver, as it uses friendship to access the epollFd.

**Comment by kentonv** [comment]
I guess it's not just that you have to use level-triggered operation, but also you need to write your own `read()` code that is careful only to call `read()` when it definitely knows there is data available, otherwise you might accidentally block. The default implementation of `AsyncInputStream` won't necessarily give you that.

I think you can shim level-triggered events on top of `FdObserver` as follows: Any time you want to register for notification of readability, first use a direct call to `poll()` with just the one FD and zero timeout to check whether data is already available. If so, handle it. Only if no data is available, then call `fdObserver.whenBecomesReadable()`. When `whenBecomesReadable()` signals readability, make sure to check again whether data is actually available before you call `read()` -- in case of spurious signals.

We could also consider adding built-in support for explicitly level-triggered events. But, I'm not sure it would provide any real benefits in this case, and it might add significant implementation complexity.

**Comment by kentonv** [comment]
BTW, this doesn't ultimately help you here, but:

> It takes ownership of the file descriptor (not a big deal but would be happier to without).

This is only true if you pass the `TAKE_OWNERSHIP` flag (or if you pass a `kj::AutoCloseFd` by rvalue-reference, which implies ownership transfer).

**Comment by Sarcasm** [comment]
Thank you, I came out to the same conclusion, of using `poll()` with a null timeout, after reading the [AsyncStreamFd](https://github.com/capnproto/capnproto/blob/17993afff8cb78543a4dffa2809b41b9c8fbe437/c++/src/kj/async-io-unix.c++#L129) implementation and a good night sleep.

I did not think about `whenBecomesReadable()` spurious wakeups, however, I'm under the impression that the only way to no block in this case is to have a non-blocking file descriptor, as `poll()/select()` also seems subject to spurious wakeups.
I use stdin/stdout mostly for testing, and will eventually use an owned, edge-triggered, socket for real use, so that may not be an issue.

Ownership taking is not an issue with `FdObserver`, it was only an issue with `wrapInputFd()` which forces `TAKE_OWNERSHIP` on the underlying `FdObserver`.

Thank you for your time, and for KJ, I quite enjoy using and reading it.

**Comment by kentonv** [comment]
> poll()/select() also seem subjects to spurious wakeups.

Huh, I didn't actually know this, but I see it now under BUGS in the select(2) man page. I suspect these problems don't happen for TTYs, but if they do, it sounds like there's indeed no solution except to use non-blocking I/O.

Note that `whenBecomesReadable()` can wake up spuriously for additional reasons. Namely, when using edge-triggered event queue APIs, it's possible that a previous edge is still in the queue waiting to be delivered. You might `read()` all data in the FD, then have the edge notification delivered afterwards, even though no new data has arrived.

> Ownership taking is not an issue with FdObserver, it was only an issue with wrapInputFd() which forces TAKE_OWNERSHIP on the underlying FdObserver.

`wrapInputFd()` is what I was talking about. It takes a `flags` parameter, which defaults to zero. When passing an integer FD (not `kj::AutoCloseFd`), the call only takes ownership if you include `TAKE_OWNERSHIP` in the flags.

**Comment by Sarcasm** [comment]
I made an implementation that mimicks the `AsyncStreamFd::tryReadInternal()` but always `poll()` before `read()`, even after `whenBecomesReadable()`, so it should be ok for spurious wakeup.
Before polling `STDIN_FILENO`, I also check if it is pollable at all, as it could be a file.
If it is, I neither call `poll()` nor `whenBecomesReadable()`, I just assume `read()` will complete (even if that takes time). Might refactor this part to use `FdInputStream::tryRead()`.

This seems to cover most shell pipeline possibilities:

    # a tty
    ./myapp
    # a file
    ./myapp < some_command_file.txt
    # an empty file
    ./myapp < /dev/null
    # a pipe
    cat some_command_file.txt | ./myapp
    # an "interactive" pipe
    cat | ./myapp

You are right about `wrapInputFd()`, I didn't notice the overload (they are not next to each other).
It never took ownership of my fd as I was passing `STDIN_FILENO` to it, good to know.
