### ISSUE TITLE
Use blocking STDOUT_FILENO with KJ event loop

### ISSUE THREAD

**Issue by Sarcasm** [capnproto/capnproto#924]
This is a follow up to https://github.com/capnproto/capnproto/issues/919.

I don't want to make STDOUT_FILENO non-blocking, because it can have side-effect to stdin/stderr, e.g. when they all point to the same tty.
I'm fine with writing to stdout being blocking, so I made an `AsyncOutputStream` where the `write(...)` is just a call to `kj::FdOutputStream(STDOUT_FILENO).write(...)`.

However, there is one thing I'd like to watch when stdout is pollable, it's hangups / `whenWriteDisconnected()`.
So that my application can be stopped when the output stream read-end closes, e.g.:

    ./myapp | grep --max-count=1 SomeEvent

To support this, I used `kj::UnixEventPort::FdObserver::OBSERVE_WRITE`, but truth be told, it wasn't for waiting for writes, just to get an `FdObserver` that signals `whenWriteDisconnected()`.
And I realize now, that this had an unfortunate side-effect.

When running my application under strace, I now get an infinite loop, because strace writes to STDERR, which is shared with STDOUT:

    $ strace ./myapp
    ...
    [pid 15119] epoll_wait(3, [{EPOLLOUT, {u32=23202328, u64=23202328}}], 16, -1) = 1
    [pid 15119] epoll_wait(3, [{EPOLLOUT, {u32=23202328, u64=23202328}}], 16, -1) = 1
    [pid 15119] epoll_wait(3, [{EPOLLOUT, {u32=23202328, u64=23202328}}], 16, -1) = 1

My understanding is that each write to stderr strace make, generates an `epoll_wait()` event (not sure why, but why not?).
Each event generates an strace writes.
And this loop goes on indefinitely.

I found a way to watch only `whenWriteDisconnected()`, by instantiating an `FdObserver` that observes for nothing, value `0`: that is neither `OBSERVE_WRITE`, nor `OBSERVER_READ`, nor `OBSERVER_URGENT`.
This still watches hang-ups, since the epoll man page states that:

       EPOLLHUP
          Hang up happened on the associated file descriptor.
          epoll_wait(2) will always wait for this event; it is not necessary to set it in events.

With the current FdObserver code, this work fine:

https://github.com/capnproto/capnproto/blob/b301982c66f18d8f299537375f4293c5717f2e93/c++/src/kj/async-unix.c++#L341-L350

But I'm wondering if I'm relying on an implementation detail here, or if you think it is safe?
Also asking, in case there is a better method I did not think of.

**Comment by kentonv** [comment]
Interesting. I suppose every time data is consumed by the terminal emulator, it frees up space in the pipe buffer, which results in a "writable" edge event being signaled to the epoll.

FWIW, on platforms where KJ uses level-triggered events (e.g. non-Linux POSIX, or on Linux if you compile with `-DKJ_USE_EPOLL=0`), you would have ended up in an infinite loop here even without `strace`.

Your solution of creating an `FdObserver` that watches for nothing seems reasonable. If you'd like to make sure we don't accidentally break that usage in the future, you could submit a PR adding a unit test for this. :)

**Comment by Sarcasm** [comment]
Ah thank you for the `KJ_USE_EPOLL=0` remark.
Observing writes was really something I did not want I realize now.

I just submitted a PR #925 to avoid regression on this in the future.
