### ISSUE TITLE
Clarify packed input stream

### ISSUE THREAD

**Issue by Timmmm** [capnproto/capnproto#927]
I'm currently using reading/writing Capnp data to an `istream`/`ostream` like this:

```
  std::istream in = ...;
  kj::std::StdInputStream sis(in);
  capnp::InputStreamMessageReader message(sis, opts);

  auto dataReader = message.getRoot<cap::Data>();
  ...
```

My data has some `uint64` values that are usually small. To save space I'd like to use the packed format, but `PackedInputStream` has the following comment.

```
class PackedInputStream: public kj::InputStream {
  // An input stream that unpacks packed data with a picky constraint:  The caller must read data
  // in the exact same size and sequence as the data was written to PackedOutputStream.
```

What exactly does that mean? Can I really not do this?

```
  // Write
  dataWriter.setBar(1);
  dataWriter.setFoo(2);

  // Read
  auto foo = dataReader.getFoo();
  auto bar = dataReader.getBar();
```

Isn't that kind of insane? How are you supposed to use it?

**Comment by jclee** [comment]
I'm not an expert, but it looks like `PackedInputStream` is in a private namespace, indicating that it is documenting an internal implementation detail meant for anyone modifying capnproto itself.  If you are only using the public interface (`PackedMessageReader`, `writePackedMessage()`, etc.), you shouldn't need to worry about this constraint -- the intervening internal layers (`InputStreamMessageReader` and `writeMessage()`) should already guarantee that the sequence of raw buffer reads made to `PackedInputStream` match the raw buffer writes made to `PackedOutputStream`.

Moreover, I believe at the point your code is calling `setFoo()` or `getFoo()`, you are accessing data that is unpacked in memory, not triggering stream reads/writes, so the order of invocation should not matter.

**Comment by kentonv** [comment]
@jclee is correct. This comment is about an internal implementation detail which you don't need to worry about.

**Comment by Timmmm** [comment]
Aha, thanks! Not sure how I missed `PackedMessageReader`. :-)
