### ISSUE TITLE
There is visible ``</div>`` in documentation.

### ISSUE THREAD

**Issue by akhilman** [capnproto/capnproto#932]
There is visible ``</div>`` in section [Generic Types in Schema language reference](https://capnproto.org/language.html#generic-types).

![image](https://user-images.githubusercontent.com/180812/74058201-15955480-4a18-11ea-89cb-b3fb182cfbcb.png)

**Comment by kentonv** [comment]
Thanks. This was already reported in #897, so closing this issue.
