### ISSUE TITLE
capnproto 0.7.0 fails to build on gcc10 on i686 and armv7hl

### ISSUE THREAD

**Issue by Conan-Kudo** [capnproto/capnproto#937]
When rebuilding capnproto 0.7.0 with GCC 10 in Fedora rawhide, I've encountered different failures on i686 and armv7hl.

### i686

The `kj-heavy-tests-run` test suite failed with the following error:
```
2: [ TEST ] filesystem-disk-test.c++:833: DiskFile holes
2: kj/filesystem-disk-test.c++:887: failed: expected file->stat().spaceUsed == meta.spaceUsed
2: stack: 56692dfc 566dd63b f7de4b8b f7d7e441 f7de6388 f7de6aee f7d8fe37 f7d906a5 f7d7e441 f7d8b618 f7de38da f7996ebd 5663b154
2: kj/filesystem-disk-test.c++:920: failed: expected file->stat().spaceUsed < meta.spaceUsed
2: stack: 566d29bc 566dd83a f7de4b8b f7d7e441 f7de6388 f7de6aee f7d8fe37 f7d906a5 f7d7e441 f7d8b618 f7de38da f7996ebd 5663b154
2: [ FAIL ] filesystem-disk-test.c++:833: DiskFile holes (5662 μs)
```
Full build log: [capnproto-c++-0.7.0-5.fc33.i686-build.log.txt](https://github.com/capnproto/capnproto/files/4242628/capnproto-c%2B%2B-0.7.0-5.fc33.i686-build.log.txt)

### armv7hl

The `kj-tests-run` test suite failed with the following error:
```
1: [ TEST ] table-test.c++:786: large tree table
1: *** Received signal #11: Segmentation fault
1: stack: 
1/5 Test #1: kj-tests-run .....................***Failed    1.29 sec
```
Full build log: [capnproto-c++-0.7.0-5.fc33.armv7hl-build.log.txt](https://github.com/capnproto/capnproto/files/4242626/capnproto-c%2B%2B-0.7.0-5.fc33.armv7hl-build.log.txt)

**Comment by kentonv** [comment]
Thanks for the report!

The "DiskFile holes" failure is almost certainly due to the particular filesystem you're using, and its precise behavior around sparse files. We should really adjust that test to be less flaky on diverse filesystems.

The armv7hl test seems like a real problem. Could you try a debug build to get more information?

    ./configure CXXFLAGS=-g
    make clean
    make check

**Comment by Conan-Kudo** [comment]
The tests pass in this case.

```
make[3]: Entering directory '/builddir/build/BUILD/capnproto-c++-0.7.0-autotools'
PASS: capnp-test
PASS: capnp-evolution-test
PASS: src/capnp/compiler/capnp-test.sh
============================================================================
Testsuite summary for Capn Proto 0.7.0
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

I guess it's only happening with the CMake build. 😢

**Comment by kentonv** [comment]
Is Fedora still using the cmake build? We really want packagers to use the autotools build. We do not officially support the cmake build for anything other than Windows/MSVC. Can you please switch?

With that said, I have trouble imagining how choice of build system could lead to segfaults...

**Comment by Conan-Kudo** [comment]
Fedora is still using the CMake build because it provides both working pkgconfig and CMake configuration files that contemporary projects using capnproto expect, whether they use CMake or not. The Autotools build does not provide functionally useful CMake configuration (it can't, as it doesn't generate enough information).

The choice of buildsystem doesn't seem to be the cause of segfaults. It seems that the choice of compilation flags, however, is.

I can reproduce the failure on the autotools build system when I have the following flags set:

```
CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard
container=systemd-nspawn
LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a -mfpu=vfpv3-d16 -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard
```

**Comment by niekbouman** [comment]
BTW gcc10 is not officially released yet; could this be "just" a regression in gcc10 ?

**Comment by Conan-Kudo** [comment]
It's possible, I've just filed [RHBZ#1807872](https://bugzilla.redhat.com/show_bug.cgi?id=1807872) for that.

**Comment by Conan-Kudo** [comment]
@jakubjelinek has indicated he thinks that capnproto might be buggy here. Quoted from  [RHBZ#1807872#c1](https://bugzilla.redhat.com/show_bug.cgi?id=1807872#c1):

> Tried building it on x86_64 with `-O0 -g -fsanitize=undefined,address` and it FAILs there too, e.g.
```
src/capnp/compiler/module-loader.c++:118:65: runtime error: signed integer overflow: 1535247712000000000 * 73 cannot be represented in type 'long int'
src/kj/array.h:466:14: runtime error: reference binding to misaligned address 0x7f9ca0e74dae for type 'const struct ArrayDisposer', which requires 8 byte alignment
src/kj/string.c++:190:25: runtime error: negation of -9223372036854775808 cannot be represented in type 'long int'; cast to an unsigned type to negate this value to itself
src/kj/array.h:466:14: runtime error: reference binding to misaligned address 0x000000000002 for type 'const struct ArrayDisposer', which requires 8 byte alignment
0x000000000002: note: pointer points here
<memory cannot be printed>
```

> (just a couple of different messages from src/capnp/compiler/capnp-test.sh.log).
> Furthermore, lots of warnings like:
```
./src/kj/common.h:1267:23: warning: initializing ‘kj::ArrayPtr<const kj::ArrayPtr<const unsigned char> >::ptr’ from ‘std::initializer_list<kj::ArrayPtr<const unsigned char> >::begin’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
```
> So not really sure I want to spend too much time looking into it, because it is very likely just buggy package.

**Comment by kentonv** [comment]
Hi @jakubjelinek,

This project is extensively tested across three compilers (GCC, Clang, MSVC), four operating systems (Linux, Mac, Windows, Android), and four hardware architectures (x86, x64, arm32, arm64). We regularly run all our tests under Valgrind, we fuzz test with AFL and by hand. The code is currently serving millions of external requests per second in production (at my company alone).

Which is not to say that the problem here isn't a bug in our code, but I think it's unfair to blow off the whole project as buggy just because the 738-test suite produced a handful of sanitizer warnings, using a sanitizer that doesn't happen to be the one we've preferred to use historically.

I looked at the specific warnings, and none of them look like they could plausibly explain the segfault that Neal is seeing. Yes, we should probably tweak the code so that they don't show up in the first place, but they aren't the problem.

> Tried building it on x86_64 with -O0 -g -fsanitize=undefined,address and it FAILs there too, e.g.

The test that fails is failing only because it's expecting very specific output on stderr, but it's getting output that includes some sanitizer warnings. Everything else passes.

> runtime error: signed integer overflow

This is in a function that's computing a hash code. We should change it to use an unsigned int, sure, but that's not causing segfaults.

> runtime error: reference binding to misaligned address 0x7f9ca0e74dae

> runtime error: reference binding to misaligned address 0x000000000002

It does appear that we have some code path that binds a reference to an uninitialized pointer. But, it doesn't actually dereference it. Moreover, these errors appear to be happening specifically in the SchemaParser library, used for parsing `.capnp` files at runtime, which is not widely-used. It doesn't explain a segfault in the test for `kj::Table`.

> negation of -9223372036854775808 cannot be represented in type 'long int'

The code is:

    Unsigned u = negative ? -i : i;

The result ends up correct.

> does not extend the lifetime of the underlying array

This seems to be a new warning in GCC10 which is a false positive for our use case. We're not expecting the lifetime of the array to be extended. This is in the constructor of ArrayPtr, and the idea is that we're constructing a temporary ArrayPtr from a temporary initializer_list. Both temporaries last until the end of the statement where they were created.

**Comment by kentonv** [comment]
@Conan-Kudo FWIW you can run the specific test like:

    ./capnp-test -fkj/table-test.c++

Can you possibly run it under GDB and get a stack trace? I'd try it but I don't have access to a test machine of that specific architecture.

(It's weird that KJ wasn't able to produce its own stack trace... Does glibc's `backtrace()` not work on this platform?)

**Comment by jakubjelinek** [comment]
I didn't mean to say the whole package is buggy, just that the sanitizer diagnostics suggests real bugs that might explain the behavior.  The signed integer overflows might happen to work if you are lucky, but might result in miscompilations if you aren't.  Even for the negation you need -(Unsigned) i  if the value can be the signed type's minimum.
The binding to object with unaligned address might be harmless on x86_64 if the particular code isn't vectorized, but might be a problem on arm which I believe requires strict alignment, and the binding to NULL + epsilon is even more suspicious.

Anyway, I've bisected it on arm between -O2 and -O0 built objects and it seems the tests pass if
src/kj/capnp_test-table-test.o is built with -O0 and fails if it is built with -O2, will try to look on Monday which gcc commit changed the behavior and see what are the changes in that source file.

**Comment by jakubjelinek** [comment]
So, I've performed additional bisection, the first gcc revision where the test segfaults is https://gcc.gnu.org/r10-3980-g24d28a8778f4c7efcebea6c785806082eeacf9fe
which with additional -fno-ipa-ra (to avoid one function affecting another one) affected comparing to https://gcc.gnu.org/r10-3979 22 functions.  Hand bisecting that by patching the 3979 assembly with parts of 3979..3980 assembly changes shows that the only changes that matter for the segfault are in the _ZN2kj1_12_GLOBAL__N_111TestCase7863runEv function (i.e. kj::_::(anonymous namespace)::TestCase786::run() ) and the assembly changes are:
--- table-test.s	2020-03-02 13:25:28.069290194 +0100
+++ table-test.s	2020-03-02 13:28:08.178939410 +0100
@@ -23523,9 +23547,9 @@ _ZN2kj1_12_GLOBAL__N_111TestCase7863runE
 	add	r3, sp, #108
 	str	r3, [sp, #44]
 	str	r3, [sp, #120]
+	add	r3, sp, #276
 	mov	r0, fp
-	ldr	r3, [sp, #280]
-	ldr	r2, [sp, #276]
+	ldm	r3, {r2, r3}
 	str	r1, [sp, #112]
 	bl	_ZN2kj1_9BTreeImpl6verifyEjNS_13FunctionParamIFbjjEEE(PLT)
 	mov	r3, #0
@@ -23586,26 +23610,25 @@ _ZN2kj1_12_GLOBAL__N_111TestCase7863runE
 	bl	_ZN2kj1_5Debug5Fault5fatalEv(PLT)
 .LEHE349:
 .L3439:
-	mov	r1, r3
-	mov	r0, r3
-	add	r2, sp, #8
 	str	r3, [sp, #76]
 	str	r3, [sp, #80]
+	ldr	ip, .L3452+36
+	ldr	r2, .L3452+40
+	add	lr, sp, #8
+	add	r1, sp, #76
+	ldm	r1, {r0, r1}
 	str	r3, [sp, #188]
-	stm	r2, {r0, r1}
-	ldr	r2, .L3452+36
-	ldr	r1, .L3452+40
-.LPIC723:
-	add	r2, pc, r2
-	str	r2, [sp, #4]
-	ldr	r2, .L3452+44
-	mov	r0, r5
+	stm	lr, {r0, r1}
+	ldr	r1, .L3452+44
 .LPIC724:
 	add	r2, pc, r2
-	str	r2, [sp]
+.LPIC723:
+	add	ip, pc, ip
+	stm	sp, {r2, ip}
+	mov	r0, r5
+	movw	r2, #798
 .LPIC722:
 	add	r1, pc, r1
-	movw	r2, #798
 .LEHB350:
 	bl	_ZN2kj1_5Debug5Fault4initEPKciNS_9Exception4TypeES4_S4_NS_8ArrayPtrINS_6StringEEE(PLT)
 .LEHE350:
@@ -23615,13 +23638,13 @@ _ZN2kj1_12_GLOBAL__N_111TestCase7863runE
 .LEHE351:
 .L3440:
 	mov	r3, #0
-	mov	r1, r3
-	mov	r0, r3
 	ldr	lr, .L3452+48
-	ldr	ip, .L3452+52
-	add	r4, sp, #8
 	str	r3, [sp, #84]
 	str	r3, [sp, #88]
+	ldr	ip, .L3452+52
+	add	r4, sp, #8
+	add	r1, sp, #84
+	ldm	r1, {r0, r1}
 	str	r3, [sp, #188]
 	stm	r4, {r0, r1}
 	ldr	r1, .L3452+56
@@ -23643,13 +23666,13 @@ _ZN2kj1_12_GLOBAL__N_111TestCase7863runE
 .LEHE353:
 .L3441:
 	mov	r3, #0
-	mov	r1, r3
-	mov	r0, r3
 	ldr	lr, .L3452+60
-	ldr	ip, .L3452+64
-	add	r4, sp, #8
 	str	r3, [sp, #92]
 	str	r3, [sp, #96]
+	ldr	ip, .L3452+64
+	add	r4, sp, #8
+	add	r1, sp, #92
+	ldm	r1, {r0, r1}
 	str	r3, [sp, #188]
 	stm	r4, {r0, r1}
 	ldr	r1, .L3452+68
@@ -23671,13 +23694,13 @@ _ZN2kj1_12_GLOBAL__N_111TestCase7863runE
 .LEHE355:
 .L3442:
 	mov	r3, #0
-	mov	r1, r3
-	mov	r0, r3
 	ldr	lr, .L3452+72
-	ldr	ip, .L3452+76
-	add	r4, sp, #8
 	str	r3, [sp, #100]
 	str	r3, [sp, #104]
+	ldr	ip, .L3452+76
+	add	r4, sp, #8
+	add	r1, sp, #100
+	ldm	r1, {r0, r1}
 	str	r3, [sp, #188]
 	stm	r4, {r0, r1}
 	ldr	r1, .L3452+80
@@ -23782,8 +23805,8 @@ _ZN2kj1_12_GLOBAL__N_111TestCase7863runE
 	str	r3, [sp, #284]
 	add	r3, sp, #124
 	str	r3, [sp, #136]
-	ldr	r2, [sp, #284]
-	mov	r3, r4
+	add	r3, sp, #284
+	ldm	r3, {r2, r3}
 	str	r4, [sp, #288]
 	str	r1, [sp, #128]
 	bl	_ZN2kj1_9BTreeImpl6verifyEjNS_13FunctionParamIFbjjEEE(PLT)
@@ -24223,8 +24246,8 @@ _ZN2kj1_12_GLOBAL__N_111TestCase7863runE
 	.word	.LC123-(.LPIC737+8)
 	.word	.LC12-(.LPIC735+8)
 	.word	.LC9-(.LPIC723+8)
-	.word	.LC12-(.LPIC722+8)
 	.word	.LC120-(.LPIC724+8)
+	.word	.LC12-(.LPIC722+8)
 	.word	.LC9-(.LPIC726+8)
 	.word	.LC109-(.LPIC727+8)
 	.word	.LC12-(.LPIC725+8)
The segfault is in:
#1  0xb6c18f6c in kj::FunctionParam<bool (unsigned int, unsigned int)>::operator()(unsigned int, unsigned int) (params#1=<optimized out>, 
    params#0=<optimized out>, this=0xbeffea80) at src/kj/function.h:229
#2  kj::_::BTreeImpl::verifyNode(unsigned int, kj::FunctionParam<bool (unsigned int, unsigned int)>&, unsigned int, unsigned int, kj::_::BTreeImpl::MaybeUint) (this=<optimized out>, size=6142, f=..., pos=<optimized out>, height=0, maxRow=...) at src/kj/table.c++:228
#3  0xb6c18e78 in kj::_::BTreeImpl::verifyNode(unsigned int, kj::FunctionParam<bool (unsigned int, unsigned int)>&, unsigned int, unsigned int, kj::_::BTreeImpl::MaybeUint) (this=0xbeffeba0, size=6142, f=..., pos=<optimized out>, height=1, maxRow=...) at src/kj/table.c++:216
#4  0xb6c18e78 in kj::_::BTreeImpl::verifyNode(unsigned int, kj::FunctionParam<bool (unsigned int, unsigned int)>&, unsigned int, unsigned int, kj::_::BTreeImpl::MaybeUint) (this=0xbeffeba0, size=6142, f=..., pos=<optimized out>, height=2, maxRow=...) at src/kj/table.c++:216
#5  0xb6c18e78 in kj::_::BTreeImpl::verifyNode(unsigned int, kj::FunctionParam<bool (unsigned int, unsigned int)>&, unsigned int, unsigned int, kj::_::BTreeImpl::MaybeUint) (this=0xbeffeba0, size=6142, f=..., pos=<optimized out>, height=3, maxRow=...) at src/kj/table.c++:216
#6  0xb6c18e78 in kj::_::BTreeImpl::verifyNode(unsigned int, kj::FunctionParam<bool (unsigned int, unsigned int)>&, unsigned int, unsigned int, kj::_::BTreeImpl::MaybeUint) (this=0xbeffeba0, size=6142, f=..., pos=<optimized out>, height=4, maxRow=...) at src/kj/table.c++:216
#7  0xb6c18e78 in kj::_::BTreeImpl::verifyNode(unsigned int, kj::FunctionParam<bool (unsigned int, unsigned int)>&, unsigned int, unsigned int, kj::_::BTreeImpl::MaybeUint) (this=0xbeffeba0, size=size@entry=6142, f=..., pos=pos@entry=0, height=5, maxRow=maxRow@entry=...)
    at src/kj/table.c++:216
#8  0xb6c192fc in kj::_::BTreeImpl::verify(unsigned int, kj::FunctionParam<bool (unsigned int, unsigned int)>) (this=<optimized out>, size=6142, 
    f=...) at src/kj/table.h:1144
#9  0x00476074 in kj::_::(anonymous namespace)::TestCase786::run() ()

**Comment by kentonv** [comment]
Hmm, `FunctionParam` is a little bit of a hack:

* It has a member `void* space[2]` to allocate space for two pointers, but it actually placement-new's a different type into this space.
* It assumes that because the type it allocated is trivially-copyable, copying the two `void*`s is equivalent to copying the object occupying their space.

I suppose this is likely a violation of aliasing rules and probably other rules. Maybe it should be changed to `alignas(void*) char space[2 * sizeof(void*)];`?

**Comment by jakubjelinek** [comment]
Tried to run this under debugger and the only two hunks from the table-test.s differences that are encountered before the crash are the first one and the penultimate one.  The first one shouldn't make any difference, it still loads r2 from sp+276 and r3 from sp+280 with no other changes.
The penultimate one is suspect, because it behaves differently, in the (working) case it loads r2 from sp+284 and sets r3 to whatever r4 contains (seems to be 0x7876), while the non-working code loads r2 from sp+284 and r3 from sp+288 and from sp+288 loads 0.

**Comment by jakubjelinek** [comment]
And indeed, the object at sp+284 seems to be FunctionParam.

**Comment by jakubjelinek** [comment]
Yes, it seems to be aliasing violation, it is post-reload scheduling (sched2).  Before that we have:
```
(insn 585 566 1409 36 (set (mem/f/c:SI (plus:SI (reg/f:SI 13 sp)
                (const_int 288 [0x120])) [206 MEM[(struct Wrapper *)_11].func+0 S4 A32])
        (reg/f:SI 4 r4 [691])) "src/kj/function.h":244:35 647 {*arm_movsi_vfp}
     (nil))
...
(insn 583 582 577 36 (set (mem/f/c:SI (plus:SI (reg/f:SI 13 sp)
                (const_int 284 [0x11c])) [21 MEM[(struct Wrapper *)_11].D.95595._vptr.WrapperBase+0 S4 A32])
        (reg/f:SI 3 r3 [512])) "src/kj/function.h":244:35 647 {*arm_movsi_vfp}
     (expr_list:REG_DEAD (reg/f:SI 3 r3 [512])
        (nil)))
...
(insn 1383 591 589 36 (set (reg/f:SI 3 r3 [517])
        (plus:SI (reg/f:SI 13 sp)
            (const_int 284 [0x11c]))) "src/kj/table.h":1443:16 1 {*arm_addsi3}
     (nil))
(insn 589 1383 592 36 (parallel [
            (set (reg:SI 2 r2)
                (mem/c:SI (reg/f:SI 3 r3 [517]) [552 MEM[(struct FunctionParam *)_11]+0 S4 A32]))
            (set (reg:SI 3 r3)
                (mem/c:SI (plus:SI (reg/f:SI 3 r3 [517])
                        (const_int 4 [0x4])) [552 MEM[(struct FunctionParam *)_11]+4 S4 A32]))
        ]) "src/kj/table.h":1443:16 381 {*ldm2_}
     (nil))
```
but the scheduling modes the first store of r4 to sp+288 after the load multiple, because the alias oracle tells it that the store doesn't alias the load.  It happens also with the older gcc, but in that case we got lucky and instead of using load multiple it uses two loads and postreload CSE (postreload pass) managed to optimize the load from sp+288 into just using r4 which has been previously stored to that location.
I'd go either for the char buffer with alignas, or union of the void * two elt array and a char/std::byte buffer.

**Comment by kentonv** [comment]
Thanks @jakubjelinek, and sorry for wasting your time -- had I seen the stack trace earlier, the aliasing violation would have occurred to me and we could have tried just fixing that. Oh well.

@Conan-Kudo Can you try this patch:

```diff
diff --git a/c++/src/kj/function.h b/c++/src/kj/function.h
index a55ef3dc..59ba5f35 100644
--- a/c++/src/kj/function.h
+++ b/c++/src/kj/function.h
@@ -229,7 +229,7 @@ public:
   }
 
 private:
-  void* space[2];
+  alignas(void*) char space[2 * sizeof(void*)];
 
   class WrapperBase {
   public:
```

**Comment by Conan-Kudo** [comment]
@kentonv Confirmed that it fixes the problem: https://koji.fedoraproject.org/koji/taskinfo?taskID=42120431

**Comment by Conan-Kudo** [comment]
@kentonv The i686 test still fails as it did before (not that I expected it to be fixed by this, but it doesn't hurt to check!): https://koji.fedoraproject.org/koji/taskinfo?taskID=42120784

**Comment by Conan-Kudo** [comment]
@kentonv friendly ping?

**Comment by kentonv** [comment]
@Conan-Kudo Sorry, I lost track of my e-mail for a week.

I've opened PR #952 to officially apply the patch I suggested.

Is there something else you need from me?

**Comment by Conan-Kudo** [comment]
Something for the i686 problem too would be awesome. I get the problem pretty consistently...

**Comment by kentonv** [comment]
@Conan-Kudo I recommend you simply delete that test. I'll try to make it more reliable in the next release. Probably what I'm going to need to do is write some code that detects if the underlying filesystem supports sparse files and skips the test if not...
