### ISSUE TITLE
messageToFlatArray

### ISSUE THREAD

**Issue by ambitslix** [capnproto/capnproto#939]
Hello,

I'm trying to test serialize and deserialize to flat array but I'm getting an exception.

What is wrong?
```
capnp::MallocMessageBuilder message;
CapNProto::Record::Builder capnpRecord = message.getRoot<CapNProto::Record>();
capnpRecord.setFoo = 1234;
kj::ArrayPtr<const capnp::word> serialized = capnp::messageToFlatArray(message);
memcpy(dest, (char*)serialized.asBytes().begin(), serialized.asBytes().size());
```
Then later in another scope...
```
kj::ArrayPtr<const capnp::word> serialized((const capnp::word*)src, size);
capnp::FlatArrayMessageReader reader(serialized);
CapNProto::Record::Reader     capnpRecord = reader.getRoot<CapNProto::Record>();

terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  capnp/serialize.c++:43: failed: expected array.size() >= offset; Message ends prematurely in segment table.
```
src and dest is exactly the same ptr and data.

**Comment by kentonv** [comment]
Hi Attila,

On this line:

    kj::ArrayPtr<const capnp::word> serialized = capnp::messageToFlatArray(message);

`messageToFlatArray` returns an `Array<capnp::word>`, but you are assigning it into an `ArrayPtr`, which does not have ownership. Therefore, the `Array` is destroyed after the statement completes, and `serialized` ends up being a dangling pointer. Intsead, try:

    kj::Array<capnp::word> serialized = capnp::messageToFlatArray(message);

Or you can shorten it to:

  auto serialized = capnp::messageToFlatArray(message);
