### ISSUE TITLE
Predict message size at compile time

### ISSUE THREAD

**Issue by sunnlok** [capnproto/capnproto#946]
I wanted to ask if there is a way to calculated the probable size of messages which dont contain variable elements like pointers/lists or data blobs.

That way you could sum up the size of structs/union variants that are used in a specific known fixed message and provide a stack allocated buffer to the message builder.

So a constexpr function could be created that allows to create a size hint.
`constexpr size_t messageSize = CalculateSizeForFixedMessage<Struct1,Union1Struct2,>()`

**Comment by kentonv** [comment]
There is! Use `sizeInWords<MyStruct>()`.

Note that this returns the size of the struct itself. A complete message also includes a root pointer (one word), and a segment table (also one word, assuming the message is only one segment). So to calculate the full, final message size, assuming the message contains only an instance of the given struct with no non-null pointers, do:

    (sizeInWords<MyStruct>() + 2) * sizeof(capnp::word)

(A word is 8 bytes.)
