### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by eliaslevy** [capnproto/capnproto#948]
There have been hundreds of commits to the repo since the 0.7.0 release over a year ago. Are there plans for a new release?

**Comment by kentonv** [comment]
Hi Elias,

Sorry, I keep meaning to do it but keep having more important things on my plate.

Out of curiosity, is there a particular new feature you're interested in?

**Comment by Conan-Kudo** [comment]
@kentonv I'm also interested in a new release, mainly because I've got a request to add capnproto to EPEL 8 (for RHEL/CentOS 8 users), and I'd like to include a version based on the latest code rather than the 0.7.0 release I've been shipping in Fedora for years.

**Comment by kentonv** [comment]
0.8.0 was released on April 23. Forgot to close this, oops!
