### ISSUE TITLE
Next capnproto release (v0.8)?

### ISSUE THREAD

**Issue by germandiagogomez** [capnproto/capnproto#949]
Hello,

I would like to know when to expect the next release for capnproto. Concretely I am looking for the stream feature (a-la-grpc). This is a feature that would be really useful to support for my needs.

**Comment by kentonv** [comment]
Hi Germán,

I've been meaning to do this for a while but keep having higher-priority things on my plate. :( It should happen in the next couple months?

Note that you only need the new streaming feature if you specifically need automatic flow control for multiple multiplexed streams. If flow control isn't a concern then it's already easy to do streaming in Cap'n Proto by introducing a callback object that receives a call for each chunk of data.

**Comment by germandiagogomez** [comment]
Actually I do not need control flow at all so I will go for that. But I do have plans for streams beyond that later :D, though it is not a top prio item.

**Comment by XDjackieXD** [comment]
Idk if this already coutns as highjacking (sorry if so)
but as v0.8.0 already got released, I'd propose a v0.8.1 release (I'd need the tls/gzip fixes in buildroot and working with unreleased versions in buildroot is pretty annoying)

**Comment by kentonv** [comment]
Oops, forgot to close this on April 23 when I did the 0.8.0 release.

I opened #1001 to track a 0.8.1 relesae.
