### ISSUE TITLE
MonotonicClock readable and comparable from multiple threads?

### ISSUE THREAD

**Issue by Sarcasm** [capnproto/capnproto#955]
I'm wondering if it is safe to consider MonotonicClock thread-safe?
And if the values the clock produces are guaranteed to be comparable between threads (e.g. not something thread-local)?

More precisely, I'd like to read `systemPreciseMonotonicClock()` in some "raw" threads that do not have an event loop.
And I'd like to compare the values in the main thread, with the values produced by `setupAsyncIo().provider->getTimer().now()`.

**Comment by kentonv** [comment]
> I'm wondering if it is safe to consider MonotonicClock thread-safe?

Yes, under [KJ style rules](https://github.com/capnproto/capnproto/blob/master/style-guide.md#constness), anything marked `const` is thread-safe.

> And if the values the clock produces are guaranteed to be comparable between threads (e.g. not something thread-local)?

The `Timer` and `MonotonicClock` interfaces themselves do not provide any guarantee that the `TimePoint`s they produce are comparable with any `TimePoint`s except their own.

However, the specific `Timer` created by `kj::setupAsyncIo()` and the `MonotonicClock`s returned by `system{Coarse,Precise}MonotonicClock()` are in fact synchronized in practice, and I think we should commit to keeping it that way. (Ironically, this same question came up in some code I was writing just in the last hour!)

Keep in mind, though, that the value returned by `Timer::now()` (as implemented by `setupAsyncIo()`) only updates when the event loop polls the OS for events, whereas the system `systemPreciseMonotonicClock().now()` returns the exact current time when the call was made.

**Comment by kentonv** [comment]
Action item for this issue: document the relationship between `kj::setupAsyncIo().provider->getTimer().now()` and `system{Coarse,Precise}MonotonicClock().now()`

**Comment by Sarcasm** [comment]
Great, so exactly what I needed.

> and I think we should commit to keeping it that way

:+1:
