### ISSUE TITLE
Shared Memory IPC mentioned in Road Map and Index

### ISSUE THREAD

**Issue by dfreese** [capnproto/capnproto#957]
I found it a little confusing that both the main [index file](https://github.com/capnproto/capnproto/blame/06a7136708955d91f8ddc1fa3d54e620eacba13e/doc/index.md#L70) and the [roadmap]( https://github.com/capnproto/capnproto/blame/06a7136708955d91f8ddc1fa3d54e620eacba13e/doc/roadmap.md#L58) mention shared memory.  Is that something that can be removed from one of them?

Thanks!

**Comment by fvannee** [comment]
From my understanding one is about using the message format + serialization and the other about RPC features. If you only use serialization, you can share the messages via shared memory. However, if you use the RPC features, that's not supported via shared memory yet.

**Comment by kentonv** [comment]
Hi @dfreese,

It's already possible to use Cap'n Proto with shared memory today. But, it's up to you to create and manage the shared memory. Cap'n Proto only turns the bytes into structures and vice versa.

What the roadmap is referring to is that I'd like to design a specific protocol for using shared memory for RPC and provide all the code needed to manage it, including exchanging file descriptors, mapping the memory, expanding the shared memory region when needed, signaling the peer when a message is ready, etc. There's nothing stopping an application from doing this itself today and still using Cap'n Proto on top of it (including both serialization and RPC!), but in the future I'd like it to be "turnkey".

**Comment by dfreese** [comment]
Makes sense; thanks for the clarification!

**Comment by Sabbirshubho** [comment]
As of today is shared memory for RPC available?
Thanks

**Comment by kentonv** [comment]
My previous answer is still accurate.
