### ISSUE TITLE
Installation Page still references C+11 and GCC 4.9

### ISSUE THREAD

**Issue by dfreese** [capnproto/capnproto#958]
I was taking a look at the installation page, and noticed it mentions C++11 [here](https://github.com/capnproto/capnproto/blame/master/doc/install.md#L21) and [here](https://github.com/capnproto/capnproto/blame/master/doc/install.md#L110).  Based on the 0.7 release announcement, it looks like those references should be C++14.  Is that correct?

Also, based on [this commit](https://github.com/capnproto/capnproto/commit/c281088c3b9e0368a7776255882ae410a68e06ea), is a minimum of GCC 5.0 required?

Thanks!

**Comment by kentonv** [comment]
Indeed, we should fix that.

(Added to 0.8 milestone so that I don't forget this entirely, but obviously it would be good to fix sooner if I get a chance.)

**Comment by dfreese** [comment]
Great, thanks!

**Comment by dfreese** [comment]
Thanks for taking care of this so quickly!
