### ISSUE TITLE
Using RPC with callbacks to multiple clients

### ISSUE THREAD

**Issue by fvannee** [capnproto/capnproto#959]
Hi, I'm new to Capnproto but was impressed by the features it offers. I was trying to write a small RPC server in C++ that allows clients to register a callback. Then, upon some regular occurring event, I want to broadcast a message to all clients that have registered a callback. Something similar to proto like this:

```
interface Hi {
    registerCallback @0 (callback :Callback);
    
    interface Callback {
        onEvent @0 ();
    }
}
```

The server should store the callback in a `vector<Callback>`, so that when an event happens, it can notify every single client that has registered itself.

- Is the `EzRpcServer` still suitable for this? From the documentation it looks as if this is more suitable for strict 1-to-1 communication and less for global broadcasts like this. With `EzRpcServer` - I think it would be possible if every `HiImpl` instance kept a reference to some global state where we keep this `vector` of callbacks. Is this indeed the recommended way of using this?

I think it would be useful if there were more examples available in the repository for use cases like this. :-) I'd be happy to contribute if I have a working example.

**Comment by kentonv** [comment]
Hi @fvannee,

Yes, you can do this with `EzRpcServer`. A server can have multiple concurrent clients. What the documentation is referring to regarding it being "1-to-1" or "two-party" is the fact that if, say, you received a callback from one client, and then _sent_ that callback to some other client, calls made by the second client to the callback would proxy through the server before reaching the first client. Eventually, we plan to set things up so that the clients would create a direct connection between each other, so that proxying isn't needed, but we're not there yet.

That said, I highly recommend skipping `EzRpcServer` and `EzRpcClient` and instead using the underlying `TwoPartyServer` and `TwoPartyClient` classes. The `TwoParty` classes provide a lot more flexibility and are not much harder to use. We've found that the "EZ RPC" interfaces try to do too much and tend to become more of an obstacle when requirements get more complicated.

**Comment by fvannee** [comment]
Thanks for your quick response! Very helpful. I've created something using the `TwoPartyServer` class and it's indeed quite easily usable as well.
However, I was wondering about one more thing. Let's say I have this `vector<Subscription>` objects in my server implementation somewhere. Now, if a client disconnects, I want to get a callback so I perform my cleanup here (not only for subscriptions, but perhaps I have other per-client-connection data stored somewhere as well). I didn't find a way to get such a callback.
I guess this ties in with another thing I was wondering - how to identify *which* client is calling me. In the server, I can access function parameters and results, but I don't seem to be able to get a handle that identifies which client/socket it is that is calling me.
Would you have any suggestions how I should do this?

**Comment by fvannee** [comment]
Also, what is the lifetime of these callback interfaces? A client passes them to a server - in the server rpc method we access them with `context.getParams().getCallbackInterface()` - is it safe to just push that into a vector, or will this message be destroyed at the end of the call and do they need to be deep-copied into a `capnp::MallocMessageBuilder`? It does seem to work by just putting it into a `vector`, but I'm not sure if it's correct, because the `Calculator` example seems to have make copies of interfaces in the `FunctionImpl` class.

**Comment by fvannee** [comment]
Part of this question I can answer myself after digging through the code I think - it seems that I can create my own class similar to the `TwoPartyServer` implementation. In there, I can get a callback when the client disconnects.
The question that remains is how to identify which client is calling me inside an RPC function. From the `context` that gets passed to the RPC method, I can't distinguish the caller. Is this possible?

**Comment by fvannee** [comment]
I think I found it :-) So in my own `TwoPartyServer` implementation, I'm not bound to use just one instance of the bootstrap interface, but I can instantiate a new one for every client that connects. Then I can just pass some identifier to the constructor of that instance.

**Comment by kentonv** [comment]
`FooInterface::Client`s are essentially reference-counted pointers. The `Client` type is copy-constructible, but making a "copy" really just increments the reference count. Once all references are destroyed, a message is sent to the remote object's host saying so, and the remote object is then destroyed.

And yes, creating a new bootstrap object for each client is a good way to distinguish clients.
