### ISSUE TITLE
force disconnect of another connection

### ISSUE THREAD

**Issue by fvannee** [capnproto/capnproto#964]
With the simple rpc server implementation, I'm now trying to get something to work like 'disconnect client x', where client x is a different client than the one that is making the request. I've been looking in the code to find some kind of disconnect method, but it doesn't seem to be there. What is the recommended way to implementing this?

My server keeps an `AcceptedConnection` struct per client similar to what the `TwoPartyServer` does. However, I keep this in a map so I can find it for a specific client. This means I could have access to the `AsyncIoStream`, `TwoPartyVatNetwork` and `RpcSystem` of this client. I also tried just destroying this struct, which frees up these members and which I thought should force a disconnect, but it just leads to a core dump where it's still trying to read something from freed space.

**Comment by fvannee** [comment]
On closer inspection the core dumps seems to be just coming from when I'm forcibly disconnecting my own connection this way (the one that's telling the server to disconnect someone). It seems fine to disconnect other users by destroying the AsyncIoStream/TwoPartyvatNetwork/RpcSystem combination. If that's indeed the case, it should be fine. Could you confirm that destroying the `AcceptedConnection` struct is indeed the way to go?

**Comment by kentonv** [comment]
I believe that should be fine, as long as you're destroying them in the right order (reverse of construction order).

I fixed some bugs around teardown handling recently, so if you see anything funny, you might try building against git master to see if it's been fixed. I'm currently working on a release which will include these fixes.

**Comment by fvannee** [comment]
Ok, thanks @kentonv ! A new release would indeed be awesome!
