### ISSUE TITLE
CMake and Automake both not building all kj compat libs

### ISSUE THREAD

**Issue by XDjackieXD** [capnproto/capnproto#973]
Hi!

As far as I can tell, CMake builds do not build libkj-tls.so and Automake builds do not build libkj-gzip.so (I noticed this as with the Archlinux capnproto package, the TLS lib is missing and it is building the package using CMake. When building capnproto-git from the AUR, the GZIP lib is missing but the TLS lib is there).
Another thing is that the pkgconf files for both kj-tls and kj-gzip are missing.

**Comment by kentonv** [comment]
I took care of the autotools side of this in #978. The cmake files will require a volunteer who knows cmake. Note that the autotools build is preferred for every platform except MSVC.

**Comment by Sarcasm** [comment]
> The cmake files will require a volunteer who knows cmake.

I made an attempt at it in #986.

**Comment by Sarcasm** [comment]
#986 has been merged, maybe this ticket can be closed.

**Comment by XDjackieXD** [comment]
Yes. Thank you very much for your effort :)
