### ISSUE TITLE
kj gzip + tls

### ISSUE THREAD

**Issue by XDjackieXD** [capnproto/capnproto#988]
Hi!

Im trying to wrap Capnproto serialization in GZIP and TLS using the kj async wrappers for both and both tls and gzip is working fine on their own but the moment I layer an AsyncGzipOutputStream on top of a network connection wrapped with TLS wrapNetwork I can't write data anymore without getting `kj/compat/tls.c++:254: disconnected: ssl connection ended during write` on the client side (latest capnp version compiled from git with autotools).
I tried to debug the issue but I'm pretty much out of ideas right now.
How can I debug this further and are there gotchas with async io that I might have missed that cause such behaviour?

simplyfied sourcecode of the client:
```c++
	auto ioContext = kj::setupAsyncIo();

	kj::TlsContext::Options tlsOptions{};
	// ... open certChainFile for reading ...
	kj::TlsCertificate tlsCert{certChainFile->readAllText()};
	tlsOptions.trustedCertificates = {tlsCert};
	kj::TlsContext tlsContext{tlsOptions};
	auto network = tlsContext.wrapNetwork(ioContext.provider->getNetwork());
	auto addr = network->parseAddress("localhost", 12345).wait(ioContext.waitScope);
	auto tlsConnection = addr->connect().wait(ioContext.waitScope);
	kj::GzipAsyncOutputStream gzipOutStream{*tlsConnection};

	capnp::MallocMessageBuilder message{message_space};
	// ... init message and write data to it ...

	writeMessage(gzipOutStream, message).wait(ioContext.waitScope);
	gzipOutStream.end().wait(ioContext.waitScope);
```

**Comment by kentonv** [comment]
After `gzipOutStream.end().wait()`, can you try running `tlsConnection->shutdownWrite()` and see if that helps?

The implementation of `shutdownWrite()` is a bit broken right now since for TLS in theory it may not complete immediately, but unfortunately the KJ API returns `void`. In the next release I plan to change t he KJ APIs so that all output streams have an `end()` method like `GzipAsyncOutputStream` to fix this. But I suspect simply calling `shutdownWrite()` without waiting should help in your case.

**Comment by XDjackieXD** [comment]
simply adding a `shutdownWrite()` call after the last line in the code above did not help. according to gdb the error happens during the `writeMessage()` call.

**Comment by kentonv** [comment]
Oh I see, I misinterpreted your original report.

So what you are describing sounds like the other side is disconnecting before it has received the whole message. What is the code on the other side?

**Comment by XDjackieXD** [comment]
the other side is just socat piped to a file and I'm listening to the traffic using wireshark and there is definitely no disconnect happening from socat (the connection even stays open when I get the error and the debugger halts. only when I decide to terminate the debugging session the connection terminates (but forcefully).
doing the same without gzip (just using `writeMessage()` on the `tlsConnection` and removing the `kj::GzipAsyncOutputStream gzipOutStream{*tlsConnection};` line) works fine.

**Comment by kentonv** [comment]
Figured it out. See #989.

**Comment by XDjackieXD** [comment]
Thank you very much for the quick response! I will test the changes tomorrow and close the issue once I tested it

**Comment by XDjackieXD** [comment]
It fixed the problem. Thank you again for the fast response. It would've probably taken me a lot of time to find this ^^'

**Comment by kentonv** [comment]
Thanks for the report! I'm honestly pretty surprised we hadn't run into this bug before.
