### ISSUE TITLE
MallocMessageBuilder reset

### ISSUE THREAD

**Issue by ambitslix** [capnproto/capnproto#990]
Is there a way to reset an existing MallocMessageBuilder message? Like so:

```
capnp::MallocMessageBuilder message;

CapNProto::Record::Builder record = message.getRoot<CapNProto::Record>();
...
kj::Array<const capnp::word> a = capnp::messageToFlatArray(message);

Now reset to empty:

message.reset<CapNProto::Record>();
```
Thank you

**Comment by jclee** [comment]
I don't think there's a way to reset MallocMessageBuilders, but if the purpose of doing so is to reduce allocations, I think you can use the "firstSegment" constructor overload to reuse a preallocated block of memory for multiple builder instances:

https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/message.h#L394-L401

**Comment by kentonv** [comment]
Yeah, the right way to "reset" a `MallocMessageBuilder` is to destroy it and create a new one.

As @jclee points out, if you pass a scratch buffer to the constructor, then you can reuse that scratch buffer across multiple builders. If you do this, then `MallocMessageBuilder` won't allocate any other memory unless the message needs more space than the scratch buffer.
